### ISSUE TITLE
"Structorizer" start fails: "Error: A JNI error has occored, please check your installation and try again"

### ISSUE THREAD

**Issue by writerx1** [fesch/Structorizer.Desktop#1028]
Hi there,

I've just downloaded and installed "structorizer" Version 3.32-06 from here:
https://structorizer.fisch.lu/index.php?include=downloads

I also installed Java, Version 8 Update 311, Releasedate 19. October 2021, from here:
https://www.java.com/de/download/manual.jsp (Windows Online-Version)

When I try to start "structrorizer", it says:

```
- Java Virtual Machine Launcher -
Error: A JNI error has occored, please check your installation and try again
```

After pressing "OK", it says: 

```
- Java Virtual Machine Launcher -
A Java exception has occured.
```

What can I do?

Thanks for any help.

[I'm at a Windows 10 Pro machine, version 10.0.19043 Build 19043]

**Comment by codemanyak** [comment]
@writerx1 
You may have overlooked that Structorizer versions ≥ 3.32 require at least Java 11 to run. This had been announced since beginning of 2021, was effectuated in September last year (see [News message from 2021-09-19](https://structorizer.fisch.lu/index.php?include=news).
In the [installation guide](https://help.structorizer.fisch.lu/index.php?menu=46&page=) for Windows you may find some additional hints how to avoid trouble with OpenJDK versions.

**Comment by writerx1** [comment]
Oh, I didn't see that. Thank you so much!

**Comment by codemanyak** [comment]
@writerx1
So you have succeeded to launch it now, I guess? I am glad we were able to help then.

Apparently you used the Windows installer version because the zip package ("Latest version of Structorizer (Windows & Latex))" would have popped up a dialog box saying something more unambiguous like:
"**This application requires a Java Runtime Environment 11.0.1
The system couldn't find the entered environment option.**"
and opened the [Adoptium](https://adoptium.net) homepage then where appropriate OpenJDK installation packages are offered for free.
The error message of the (otherwise more recommendable) Windows installer download is indeed somewhat wanting in the case of an insufficient Java version. We will have a look whether we may find a way to improve the behaviour of the installer-bound launcher.

**Comment by writerx1** [comment]
> @writerx1 You may have overlooked that Structorizer versions ≥ 3.32 require at least Java 11 to run. This had been announced since beginning of 2021 and was effectuated in September last year (see [News message from 2021-09-19](https://structorizer.fisch.lu/index.php?include=news) and [release 3.32](https://github.com/fesch/Structorizer.Desktop/releases/tag/3.32)). The [Structorizer User Guide](https://help.structorizer.fisch.lu/index.php?menu=45) explicitly emphasises it. In the [installation guide](https://help.structorizer.fisch.lu/index.php?menu=46) for Windows you may find some additional hints how to avoid trouble with OpenJDK versions.

Thank you so much @codemanyak - now it works perfectly :-)
