### ISSUE TITLE
runtime error (Structorizer start fails)

### ISSUE THREAD

**Issue by raulus127** [fesch/Structorizer.Desktop#1031]
Good Morning. How's it going? I am writing to you because we are having a problem with the students when executing the app. These errors appear and it does not finish executing:

- Error: A JNI error has occurred, please check your installation and try again.
- A Java Exception has occurred.

We uninstalled the version, reinstalled it and the error persists. Can you help us?

Thank you!!

**Comment by codemanyak** [comment]
Hi @raulus127,
could you please give us more information about the platform you are working on and the Java version installed? If you are working on Windows, is it the Windows installer version of Structorizer you are trying (or just the zip package)?
First of all, please make sure a Java JRE or JDK of at least version 11.0.1 is installed. If this is the case, you might then have a look at the PATH variable (whether the Java path is correctly onvolved there). Further environment variables like in particular JAVA_HOME ought to be checked.
This is an example for a suited environment on Windows 10 (though you might of course foster a more advanced JAVA version):
```
JAVA_HOME=C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-openj9\
...
PATH=...;C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-openj9\bin;...
```
In addition you might have a look at the registry, watch out e.g. for key `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft`. There you ought to find a subtree `JDK` oder `JRE`. If so, then what's in it?

If you work on Debian then the package manager (apt) should have cared for the presence of an appropriate Java environment on installing structorizer.deb.

I gues you have already had a look into the [installation chapter](https://help.structorizer.fisch.lu/index.php?menu=45) of the [Structorizer User Guide](http://help.structorizer.fisch.lu/)?

**Comment by codemanyak** [comment]
We have fixed startup problems together on occasion of #988 together. I guess you are still using Windows. So, what happened in the meantime on your site?

**Comment by raulus127** [comment]
Indeed, the platform I use is Windows 11. The version of structorizer that is by zip package, works. Not so the one that is by installer.

**Comment by raulus127** [comment]
Before I ran it on W10 without problems but now I have changed the pc and I have w11 where the problem occurs.

**Comment by fesch** [comment]
I will need to get a newer PC capable of running W11 in order to test myself :-/

**Comment by codemanyak** [comment]
Maybe there is an issue with Windows 11 (Bob is having a look at it).
On the other hand it is a fact that the two launchers of 1. the Structorizer installer and 2. the zip package use slightly different mechanisms to identify the Java environment. So let's have a look how the Java JRE or JDK represents itself on your computers in the meantime:
Please report the answers to my former questions (contents of the environment variables JAVA_HOME and PATH) andthe status/contents of the registry subtree `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft` (try command `regedit` - without changing anything in the registry so far!), if you wouldn't mind.

**Comment by codemanyak** [comment]
@fesch 
> I will need to get a newer PC capable of running W11 in order to test myself :-/

Currently I haven't got access to a machine running Windows 11, either, and I definitely won't before next week :-( So let's hope we might be able to fix the Java settings to fit the needs of the installer...

**Comment by codemanyak** [comment]
@raulus127 
> Equipo\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8\
JavaHome: C:\Program Files\Java\jre1.8.0_321

This explains fully why Structorizer does not start - the launcher does not see a version 11 or higher but only a version 8.
What it does **not** explain, however, is how the Structorizer zip package can run -- unless it is an older Structorizer version (< 3.32).
If there is no Java bin directory in the PATH variable then `Structorizer.bat` will not be able to ask for the Java version either because it uses "jar -version" for this and it can't be executed if the path for "java" can't be resolved.
I am somewhat puzzled. Can you manually execute "java -version" at the command line? Can you please check in the programs directories of drive C: what other Java installations than the 1.8 you found may be present?
If there aren't any then you will have to install (or have installed by your admins) a Java version ≥ 11. See #988 and User Guide for details to observe.

**Comment by raulus127** [comment]
java -version

java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)

**Comment by raulus127** [comment]
The zip version I'm using is 3.26 I didn't find a more current zip version in the "download" section of the page.

**Comment by codemanyak** [comment]
Thanks, so a rather up-to-date Java version (18 !) seems to be in place, but the version string scheme has changed! It had been 1.VER.MINOR.PATCHLEVEL until version 8 (1.8), then MAJOR.MINOR.PATCHLEVEL (e.g. 11.0.6) and now (since when?) it is something like just MAJOR DATE! F***! Who anticipates such a mess?

And how does the command line resolve the path of command "java" if no Java installation happens to be referred in PATH?

**Comment by codemanyak** [comment]
> The zip version I'm using is 3.26 I didn't find a more current zip version in the "download" section of the page.

You may download the most recent version 3.32-06 as ["Download the latest version of Structorizer (Windows & Linux)"](https://www.fisch.lu/Php/download.php?file=structorizer_latest.zip) from the Structorizer Download page.
I just wonder if it copes with the new version string. The old version (3.26) had a very simple Structorizer.bat that didn't care about the Java version string at all...

**Comment by raulus127** [comment]
> > The zip version I'm using is 3.26 I didn't find a more current zip version in the "download" section of the page.
> 
> You may download the most recent version 3.32-06 as ["Download the latest version of Structorizer (Windows & Linux)"](https://www.fisch.lu/Php/download.php?file=structorizer_latest.zip) from the Structorizer Download page. I just wonder if it copes with the new version string. The old version (3.26) had a very simple Structorizer.bat that didn't care about the Java version string at all...

Perfect!

**Comment by raulus127** [comment]
> Gracias, por lo que parece haber una versión de Java bastante actualizada (¡18!), ¡Pero el esquema de cadena de la versión ha cambiado! Había sido 1.VER.MINOR.PATCHLEVEL hasta la versión 8 (1.8), luego MAJOR.MINOR.PATCHLEVEL (por ejemplo, 11.0.6) y ahora (¿desde cuándo?) ¡es algo así como MAJOR DATE! F***! ¿Quién prevé tal lío?
> 
> ¿Y cómo resuelve la línea de comando la ruta del comando "java" si no se hace referencia a ninguna instalación de Java en PATH?


Sure, it's a mess. They have to be running after changes to this route. You should leave the same route so you don't have to keep changing it.

**Comment by raulus127** [comment]
Anyway I already have the latest zip version with all the features of the version by installer. So thank you very much for your valuable help!

**Comment by raulus127** [comment]
Maybe I should open another separate query but just in case I ask you: Is there a version to download that is for android? This would come in handy for my students.

**Comment by codemanyak** [comment]
> Is there a version to download that is for android? This would come in handy for my students.

Not really. Though there is a menu entry "Android" on the home page, it offers only a totally reduced, deficient (and maybe even defective) outdated prehistoric version...

**Comment by fesch** [comment]
The Android version that is available through the website is only a proof of concept and not fully functional. Sorry.

**Comment by raulus127** [comment]
> > Is there a version to download that is for android? This would come in handy for my students.
> 
> Not really. Though there is a menu entry "Android" on the home page, it offers only a totally reduced, deficient (and maybe even defective) outdated prehistoric version...

Thank you!!

**Comment by codemanyak** [comment]
While I found out that a version string only consisting of the major number like "18" is quite okay for a fresh major release (it's explicitly in the JEP233 specification) and thus should not fool the Structorizer start scripts, we still have the discrepancy between
```
Equipo\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8\
JavaHome: C:\Program Files\Java\jre1.8.0_321
```
and
```
java -version
java version "18" 2022-03-22
```
on your computers.
This means while there is a brand-new (and suitable) Java release 18 on your machine the registry and the environment variable still report an obsolete version 8. As already mentioned, the launchers may count on different mechanisms to detect the present Java environment. The java command (miraculously?) refers to the Java 18 installation while %JavaHome% and registry lead to a (possibly no longer existing) Java 8 installation.
Please have a look whether the folder "C:\Program Files\Java\jre1.8.0_321" still exists and if so whether or not it actually contains a valid installation including the executables java.exe, javac.exe, etc.
If the Java 8 installation traces are orphaned then they should be eliminated from the registry and the environment variable set. Otherwise you should consider to uninstall Java 8 (i.e. 1.8.0_321), which should also remove the traces in the registry and set of environment variables.
On the other hand, it might be considered to establish / modify the Java installation indicators to reflect the current Java product installation (cf. [Structorizer installation guide](https://help.structorizer.fisch.lu/index.php?menu=46&page=#open_jdk_trouble)).
All of these activities will require adminstrative priivileges, no doubt.

**Comment by codemanyak** [comment]
This problem should have become obsolete with the fixing of #1100 .
