### ISSUE TITLE
"A java exception has occurred"

### ISSUE THREAD

**Issue by StrongMooncake** [fesch/Structorizer.Desktop#1078]
It is not possible to start the program. I tried it with three different pcs, but it doens´t work. I only see the loading screen and than it crash. On one maschine i get the message "A java exception has occurred". All maschines having the news updates.

**Comment by codemanyak** [comment]
Have you made sure having a Java version ≥ 11 installed and in place (because that's what Structorizer requires to run)?

**Comment by codemanyak** [comment]
@StrongMooncake 
Perhaps I should have drawn your attention to the [User Guide "Installation"](https://help.structorizer.fisch.lu/index.php?menu=45) chapter, too, where you might find further helpful information how to tackle your problem. You should know that Oracle still provides some security updates for Java 8 every now and then but no automatic upgrade to more advanced Java releases. Unfortunately the Java launcher used to start Structorizer isn't very verbose in case of an insufficient Java release, though we expected it to be. The behaviour lets me think you're working on Windows PCs with the Windows installer package of Structorizer.
In order to get an idea of the Java version exposed by your system you might simply type the command "java -version" in the Command Prompt window (to be opened via "cmd.exe"). If the reported Java version seems okay then you might download the zipped Structorizer package for Windows, unzip it somewhere and run the Structorizer.bat script from the extracted folder at the Command Prompt. This should give you either a running Structorizer or a useful error message. Even if this extracted Structorizer version runs in your system, the Windows installer package might keep failing. This is the point where you should check the various approaches to overcome the Java trouble as described in the User Guide (see labove link).

Please let us know about new findings along your analysis or if you eventually succeeded.

**Comment by StrongMooncake** [comment]
I found the problem. If you visit the java webpage, it will only show you version 8. So for me it was the newest version. I found the correct java version on a different page. Thank you for your help :)
