### ISSUE TITLE
Structorizer called via executable in windows does not run the program

### ISSUE THREAD

**Issue by csrabak** [fesch/Structorizer.Desktop#1100]
In a Windows 10 Home Single Language ver 22H2, compilation 19045.3570, 64 bits, Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz, 32 GB RAM, java 15.0.1 2020-10-20, Java(TM) SE Runtime Environment (build 15.0.1+9-18), Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing).

If I double click the Structorizer icon after the installation via the installer for version 3.32-12, the splash screen runs for a second or so about "Testing local cache", and then after issuing in the splash screen "Starting the application" nothing else happens.

The same behaviour happens if the executable "C:\Program Files (x86)\Structorizer\structorizer.exe" is run from the command line in the CMD shell window.

More than a nuisance, since the installer registers this executable to "open/edit" NSD files, this state of affairs makes the double click in the file explorer to access NSD files inoperant.

I cannot find any clue looking at the logs in the HOME/.sctructorizer which could pinpoint the problem.

Now, If in the command line I invoke via the batch file, I get the programm to work, but sometimes with the following warning in the CMD shell window:

`
java -jar "C:\Program Files (x86)\Structorizer\Structorizer.jar"
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JButton.getPreferredSize()" because "this.decrButton" is null
        at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.layoutVScrollbar(BasicScrollBarUI.java:772)
        at java.desktop/javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(BasicScrollBarUI.java:979)
        at java.desktop/java.awt.Container.layout(Container.java:1537)
        at java.desktop/java.awt.Container.doLayout(Container.java:1526)
        at java.desktop/java.awt.Container.validateTree(Container.java:1722)
        at java.desktop/java.awt.Container.validateTree(Container.java:1731)
        at java.desktop/java.awt.Container.validate(Container.java:1657)
        at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
        at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1883)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`
And then the log shows the warning about not finding some element in the locale (log attached).
[structorizer0.log](https://github.com/fesch/Structorizer.Desktop/files/13177177/structorizer0.log)

Hope with there is enough info so we can find a way of restoring the .EXE funcionality!

**Comment by codemanyak** [comment]
Thanks for your report, though I am without a clue, too, by now. The stacktrace from the batch start just reflects an inconvenient temporary GUI race on startup, as far as I can see, and thus does not explain the dysfunction of the product installed as "C:\Program Files (x86)\Structorizer\structorizer.exe". Apparently, the installed java environment version cannot be blamed, otherwise the unzipped package run from the batch file wouldn't start, either.

Your report suggests that you don't see any error message at the CMD shell window when you start the installed executable fro  the command line. Is this correct?

**Comment by codemanyak** [comment]
I un-installed Structorizer on my Windows 10 PC now and re-installed it from the latest Windows installer version just downloaded from the Structorize homepage - and all worked fine. So, the installer version is not defective in general. No idea what hinders the start of your installed product. (I use a jdk-17.0.3.7-hotspot, but the jre 15.0.1 on your computer should also be fine.)
Did you try to uninstall and reinstall Structorizer? Maybe something went wrong during the installation (though I don't imagine what it could have been)?

**Comment by fesch** [comment]
Maybe the problem was the code signing certificate that was used on the .exe which has expired. I got y new one last week and updated immediately all signed files, so maybe this made it ...

**Comment by csrabak** [comment]
@codemanyak :

I uninstalled using the uninstall of the program, checked no renmants of the program were in `C:\Program Files (x86)\Structorizer\` and rerun the installer.

As the last option in the installation process it is offered to run Structurizer, I did it.

The same thing: the splash screen, then a suggestion to update the program (as if there was an update, which I dismissed), and the screen goes off and no program run...

**Comment by codemanyak** [comment]
@csrabak 
Thanks for having tried.
What puzzled me was the reported suggestion to update the program: When I installed Structorizer last night (CET) from a fresh download this didn't happen. So my first thought was that you might have used an obsolete download. But when I started Structorizer this afternoon on a different PC, I saw the update suggestion, too. My only explanation now is that Bob renewed the launcher this morning. But I also noticed that the Structorizer.jar file grew a little (from 7.800.466 Byte to 7.805.203 Byte) as well, without any code change traced in GitHub could explain this. Bob will have rebuilt it as well. But yet, this must have happened between your download and your installation. (And this seems unlikley.)
So, you might choose to admit the update next time (any subsequent start attempt will offer it anyway). If this does not help (I am afraid it won't), then you may reinstall it again. If all this turns out to be done in vain then I'd like you to consider whether perhaps some antivirus software installed on your computer might intercept. But if so then why silently? That structorizer.exe does not get wiped off or renamed, however, makes this assumption unlikely.
In the event, I am still clueless.

**Comment by csrabak** [comment]
@codemanyak 
I thank for your comments, and I share you puzzlement about the asking for update.

I've tried the following things, all of them with no avail:

- run the program with AV paused;
- reinstalling on the `Roaming` user directory instead of the general `C:\Program Files (x86)\Structorizer\` one;
- accepting the suggestion for updating.

My Structorizer.jar has the date/time of the last run attempt, and right now in the reinstalled folder in C: drive has:
`27/10/2023  14:11         7,805,203 Structorizer.jar`

It is possible to run structorizer.exe with any command line switch so it be more verbose in the run?

**Comment by codemanyak** [comment]
@csrabak 
> Is it possible to run structorizer.exe with any command line switch such that it be more verbose in the run?

No, unfortunately it is not as far as I know. It would be possible to lower the logging threshold within Structorizer itself but this would hardly help, since we know that Structorizer.jar is runnable in your system.

I wonder if [ProcessMonitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon), a tool from Sysinternals might be of any help here. Just configure the following filter (in menu Filter > Filter...) before you start Structorizer:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/40bf64a9-4b88-4161-a0f5-1d5dbf730af1)

 Then you might inspect the event list and save the log e.g. as CSV file.

Should look at the end like this in the tool:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/82243d71-4a82-48b4-ae41-e8fcb5d456b0)

**Comment by csrabak** [comment]
Did it, got similar picture of yours, and saved the CSV file.

![image](https://github.com/fesch/Structorizer.Desktop/assets/10200568/c6e89369-26f6-414a-bb3e-c4ee16a74e18)

I don't see anything obvious. . . would posting my CSV help?

**Comment by codemanyak** [comment]
@csrabak 
Please excuse my late reaction. Yoe asked:
> I don't see anything obvious. . . would posting my CSV help?

Well, I can't say before having seen it. So this is a yes. Please post it, then I could compare the contents. The number of events might be a first hint: My successful start reports 22 events more than your failed one. So it's not unlikely to find out something important, some significant difference, certainly near to the end of the list rather than the beginning. You might decide to cut out the list of environment variable vaules from the start event, for privacy reasons, though I don't see a lot of sensitive stuff there.

**Comment by codemanyak** [comment]
@csrabak 
Something was just dawning on me: Would you mind checking whether the environment variable JAVA_HOME is set? It should contain the path to your Java installation (e.g., `C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-openj9\` on my machine). This is one of the major information sources for the launcher program (`structorizer.exe`) to check an available Java installation. The batch file, however, does not need `%JAVA_HOME%` but requires the Java installation path to be listed in the environment variable `PATH` (which is obvoiously the case).

Another important check `structorizer.exe` performs to find out whether a suited Java installation is in place is registry key `HKLM\SOFTWARE\JavaSoft\Java Runtime Environment` (or `HKLM\SOFTWARE\JavaSoft\JRE`). Is any of these registry entries configured in your system?

If neither environment variable `JAVA_HOME` nor the mentioned registry key is set in your system, then this could perfectly explain why `structorizer.exe` fails, although `Structorizer.bat` succeeds. Unfortunately, the launcher executable generated by Launch4J isn't actually verbose - to say the least. Also see the respective [section of the Structorizer User Guide](https://help.structorizer.fisch.lu/index.php?menu=46&page=#open_jdk_trouble), please.

**Comment by csrabak** [comment]
@codemanyak 
My present system has no `JAVA_HOME` environment variable, so I checked the registry keys.
`HKLM\SOFTWARE\JavaSoft\JDK` has a `JavaHome` entry whose value is `C:\Program Files\Java\jdk-15.0.1`, also I have `HKLM\SOFTWARE\JavaSoft\Java Runtime Environment` that has also a `JavaHome` with value `C:\Program Files\Java\jre1.8.0_261`.

Pertaining to your comments about opening automatically a browser, I've tried with all windows closed, so I could see the event, and no browser opened.

Please find my log file as well.

[StructorizerLogfile.CSV](https://github.com/fesch/Structorizer.Desktop/files/13197060/StructorizerLogfile.CSV).

Here is my About like the part of the manual you pointed me to:

![image](https://github.com/fesch/Structorizer.Desktop/assets/10200568/0741c7b3-e0dc-488d-8916-04f6862bcf5e)

This *about* obtained by running the batch file!

**Comment by codemanyak** [comment]
@csrabak 
Many thanks. And well, yes, the offering of an update meant that a Java subprocess (Upla) had successfully been started. Hence, the Java environment configuration was not to be blamed, either. I had a closer look into the startup program now and was reminded that the actual start of Structorizer is managed within the "Upla" application, which is written in Java. So this must have been what failed.
To get more information we must therefore now watch the `javaw.exe` process successfully created by `structorizer.exe` (it's line 401 in your log). To do this I would like you first to stop all other Java-based applications then to start FileMon again and add another include filter for process name `javaw.exe` before you try to start Structorizer again:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/6af6e773-4c5d-44d1-b3aa-3eff22801a01)

Save the log as CSV (it will be pretty large, i.e., it might contain 50.000 lines or more).

In the log you should then search for operations "Process Create" and for references to "Structorizer.jar". There should be exactly two entries with operation "Process Create" (both followed by a related operation "Process Start" with process name "javaw.exe"):
- `structorizer.exe` creating a process with command line: "C:\Program Files\Java\jdk-15.0.1\bin\javaw.exe" -jar "C:\Program Files (x86)\Structorizer\Upla.jar"
- `javaw.exe` creating a process with command line: "C:\Program Files\Java\jdk-15.0.1\bin\javaw.exe" -jar "C:/Program Files (x86)/Structorizer/Structorizer.jar"

If the latter is missing or shows lacking success we would know more.
Otherwise we should see three different PIDs in the log (one for `structorizer.exe`, another for the first `javaw.exe` process running "Upla.jar", the third for the second `javaw.exe` process running "Structorizer.jar"). We should then have a look for entries referring to "Structorizer.jar", in particular as part of the "path" column. If all worked well with Structorizer then the filtered log (apply additional filter "path contains Structorizer.jar") should look like this in FileMon:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/3022c3dc-d983-4934-af23-c5f84b2d9913)

It shows an attribute check at the beginning, then the jar file will be opened in order to execute the compiled algorithm.

**Comment by csrabak** [comment]
@codemanyak 
I've attempted to follow your directions, and surmised I only need the two filters mentioned, not all you've in your example screen.


[Logfile.CSV](https://github.com/fesch/Structorizer.Desktop/files/13198693/Logfile.CSV)

I've not included the one with the filter as the complete one includes this information.

**Comment by codemanyak** [comment]
@csrabak 
Heureka! This logfile indeed shed enough light into this mystery: The monitor logged four consecutive start attempts for Structorizer. The important finding is that each time when Upla.jar starts a Java subprocess to run Structorizer.jar, it fetches the javaw.exe from a Java jre1.8.0_261, which also resides on your computer (first logged access is a "Load Image" event in log line 8779, then many jre1.8.0_261 references follow). This always leads to a failure of Structorizer.jar with exit code 1 some 8000 event lines later (event "Process Exit"). The failure is silent because Structorizer itself does not check anymore what Java version it is running on - and if it would then I am not sure whether it could still raise a message box before it dies. I'll try to insert such a test in the first couple of lines of code.
Obviously, the way Upla retrieves the Java directory to use is flawed. We will have to fix it. Many thanks for your assistence in identifying the problem!

For the meantime, the question is whether you could uninstall Java 8 without compromising other Java applications that might strongly rely on Java 8?

**Comment by fesch** [comment]
Actually Upla uses the "Process" class to launch structorizer.jar.

In order to "see" what executable to use for this, it checks the environment variable "sun.boot.library.path" which should contain a list of bootfolders.  It looks for a "bin" folder there. So actually this should be the java version which was used to start the Upla process and not some other ....

**Comment by codemanyak** [comment]
@fesch 
> So actually this should be the java version which was used to start the Upla process and not some other ....

Well, maybe it should be, but the log file from https://github.com/fesch/Structorizer.Desktop/issues/1100#issuecomment-1784170856 tells a different story: Upla is definitively started with (and runs on) jdk15.0.1 (see line 463, "Load Image" event for the Upla process with PID 12404, furter on lines 506 ff). When Upla process 12404 then composes the Process path for the start of Structorizer.jar (PID 7592), it uses jre1.8.0_261 (see e.g. line 8742, event "Process Create").
It happens four times in the log file (PID triples 13096/12404/7592, 9524/11720/14000, 2748/11864/13400, 10764/13764/12856, where the first PID always belongs to `structorizer.exe`, the second one to its child `javaw.exe Upla.jar`, the third one to grandchild `javaw.exe Structorizer.jar`).
So, possibly `System.getProperty("java.home")` should be preferred over environment variable "sun.boot.library.path". According to the method descriptions in class `System`, these properties are derived from the current virtual machine. If `structorizer.exe` manages to fetch the required Java environment then Upla should better adhere to it. Possibly the environment variable "sun.boot.library.path" is somewhat outdated? At least its name sounds as if. On the other hand, on most systems it had worked, obviously. Perhaps Upla should check and compare both and decide for the more up-to-date directory?

**Comment by csrabak** [comment]
@codemanyak 
I'll check with my partners if deinstalling the JRE would break something.

Sometimes certain dependencies crept in, you know!

Thanks for digging in this issue and I'll be lurking this thread if any other test would be necessary, but I surmise you now can create a test environment that emulates mine which triggers this nasty behaviour.

Again thank to all for this superb project.

**Comment by codemanyak** [comment]
@csrabak 
> Thanks for digging in this issue and I'll be lurking this thread if any other test would be necessary, but I surmise you now can create a test environment that emulates mine which triggers this nasty behaviour.

Bob just provided the new Structorizer version including the revised launcher. Would you mind uninstalling and reinstalling Structorizer from the Homepage? This would be particularly valueable if your Java environment has kept unchanged.

**Comment by csrabak** [comment]
I've removed all traces of old Structorizer, including the directory under `C:\Program Filex (x86)` and unzipped the  `structorizer_latest.zip` from Homepage.

Due the necessary accommodations for team work, no change in the environment was done (so JRE and JDK maintained).

The EXE file runs like a charm!

However, for the completness of the test I've to inform:

1. As the installation is done via a simple unpacking of the program, no "file association" in the Windows environment is available, so the double clicking on a `.NSD` file cannot be tested;
2. The way this particular package is installed the EXE (or its children) looks for the `.JAR` file in the `Structorizer.app` subdir,  whereas the programm when installed via the windows installer (`.exe`) looks for the jar in the same folder as the launcher is.

Hope this is contributive and helps!

Thanks everyone involved in the chasing of this gnat!
