### ISSUE TITLE
Importing C code with nested comments fails

### ISSUE THREAD

**Issue by csrabak** [fesch/Structorizer.Desktop#1108]
The minimum reproducible code, albeit contrived, but that replicates the production code where we find this behaviour follows:
```
///*
// *********  Platform A version *********
#include "project.h"

void
func(int data)
{
    do_something(data);

}
//*/

/*
// *********  Platform B version *********
void
func(int data)
{
    do_else(data);
}
*/
```
On the onset I want to stress I'm not advocating this style of coding, but rather "accept" it, as is a legacy code from an old project. . .

If we run this code to a check with gcc we get:

`D:\>gcc -fsyntax-only example.c`

I.e. no warnings nor errors.

However, Structorizer complains and give the following (which it allow to collect to the clipboard):

> error.lexical in file "example.c"
> 
> Preceding source context:
>     1:   ///*
>     2:   // *********  Platform A version *********
>     3:   » #include "project.h"
> 
> Found token (Error) (#)
> 
> Expected: 
> 

Since Structorizer uses C99 as paradigm for parsing C code, I think this is a bug.

PS.: If it helps, other tools chew in this construction and generate the diagram. . .

**Comment by codemanyak** [comment]
Indeed. I have to beg your pardon for this bug. In the file preparation phase indeed many line comments were overlooked due to a defective test, and in this specific case the following comment block that should have been disabled appeared as active such that the necessary preprocessing of the `#include` directive was omitted and let the parser crash. Fix is ready and will be delievered with the next version.
