### ISSUE TITLE
Suggestion for improvement of HLL code import if feasible

### ISSUE THREAD

**Issue by csrabak** [fesch/Structorizer.Desktop#1115]
I would like to suggest that for languages like C that can have constants defined in header files, that an option be allowed to have the imported NSD with the macro (names) of the constants kept.

Presently, the imported diagram leaves only the actual values computed, which in the majority of the cases, in my experience, is less informative than the original names.

Also it would be nice if in the import of HLL some kind of annotation could keep the variable types, as if the code preview pane is opened the message is a TO DO left, as this info is lost in the process.

**Comment by codemanyak** [comment]
Thank you for suggestions. They are plausible and somehow I anticipated them with issue #1087.
In order to offer a C import at all we had to concentrate on making the source files pass the parser in some way. Therefore some kind of preprocessor was written to fetch enough information about otherwise ambiguous names from the referenced header files, no more. It was to give an impression about the algorithmc structure of the imported C file itself without dumping all the external stuff from the headers (including standard C headers?) into the diagram.
No we should think about more to do. And, yes, these enhancements should be optional. The definitions included from headers are not to flood the target diagram but to form one ore more Includable diagrams. Some decisions are to be made: Shall all parsable stuff from the header files be imported or only the actually needed subsets (both have their pros and cons)? Shall the recursive header hierarchy be structurally reflected by a large number of interdependent Includable diagrams, or is it sufficient to pour all constants, types et. into a large single Includable diagram? Where in the depths of the standard C headers may we prune the search? Might a recursive application of the C99 parser to all the header files contribute to a solution or would it just multiply the difficulties on end?
I can't say by now, will have to try several approaches. But this will cost time and heavy efforts as my first attempts to tackle #1087 showed.
My current priority is to come to terms with #800, which requires a very fundamental code revision or redesign and is already pending for years. Complex tasks on the main development or bugfix branch are prone to induce massive version conflicts. So I hesitate a little. But enough with apologies.
The C import is on my agenda, too. I will have a look into it every now and then. Though please don't expect a satisfying solution too soon.

**Comment by csrabak** [comment]
Thanks for the insightful remarks and sharing the reasoning with us!

I'll attempt to contribute with my humble, but tenable in the light of the original intent of the NSD.

The main "message" if you wish or the main objetctive when it is the onset of the creation of an algorithm of NSD is to enlighten the structure of the logic, as the decision making of the program (be it in analysis, be it the building of a brand new solution).

So in my opinion this puts more weight in the side with the "... only the actually needed subsets ...".

NSD has not an expressiveness (lest a standard for it[!]) to help to engineer (or reverse it) the structural parts that could come from importing a full header file, especially for C/C++ ones.

HTH

PS.: I undestand that certain ideas may be more complex to implement that the concept!

**Comment by codemanyak** [comment]
Discussions like this are very useful to enlighten things. I highly appreciate it. Thank you! Pondering this issue made me realise (or remember) that the simulation of the C preprocessor (i.e. simple textual replacement) is the only safe way to a successful parsing. Only some of the `#define` directives have the character of a workaround for constant definitions (originally otherwise not possible in the C language), others control conditional translations and so on. Some heuristics will be necessary to distinguish between `#define`s that try to state a constant in the old-fashioned way (though true constant definitions have now been supported in ANSI-C for decades) and others that don't and would make the parser crash if we don't substitute them. It is even possible that define substitutions of the second kind are a prerequisite for a `#define` intended to introduce a symbolic name for a constant to become syntactically complete and functional. Perhaps in rare cases only, but a lot of guesswork still remains. A possible criterion might be that the substitute has literal or constant expression syntax (with operators involved, ideally within parentheses). While this selective conveying of `#define`s is optional (as requested) the user may of course abstain from it when the trial fails - so why not offer an imperfect approach?
The identification of the "actually needed subsets" requires recursive probing for references not only in the actual source file to be imported but in the visited headers as well. (Which doesn't make it impossible, of course, but tricky at least.)

**Comment by codemanyak** [comment]
A first implementation approach creats a common Includable diagram with the convertibke `#define`s that is blindly included from any other generated diagrams:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/3ab48502-9b76-4ea0-8786-fbc2e3eb8d23).
The option was added to the C99-specific import preferences:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/83f7efde-feeb-459c-ace5-3044ebaa4f56)


Will be delivered with next Structorizer version (3.32-15), together with bugfix #1116.
