### ISSUE TITLE
BUG: Comment of case is not shown 

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#145]
@fesch @codemanyak Hi Bob, hi Kay,

I found, that the comment of a case structure is not shown when I switch between text and comment.

Fiine regards
Rolf

**Comment by codemanyak** [comment]
That's because the original implementation resulted in a damaged structural shape. It's the same with Parallel sections, by the way.
The reason is that the text in CASE and PARALLEL elements isn't just multi-line but its structure has a specific function for the layout of the element. So a different approach is necessary to achieve a useful result.
I will think of a sensible solution.

**Comment by codemanyak** [comment]
Problem solved for both CASE and PARALLEL elements. Large multi-line comments in a CASE header may trespas the triangle in a somewhat ugly way, though. I will think of a better algorithm to restrain the text within the borders, but for the time being it must be sufficient.
