### ISSUE TITLE
Syntax enhancement for bash scripting

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#146]
Hi.

I see the problem to detect uninitalised variables or shell commands. So I propose a possible syntax where the executer and the code generater can detect, that it is a shell command.
A command line may look like: 
_returncode <- command({list of options and parameter})_

So like a function call in a computer language the command is marked with parentheses to be executable or external. The enclosed comma separated list of options and/or parameters should be surrounded by curly brackets. This make it detectable as a bash construct - which can be ignored by the executer. Function calls of a computer language have the parameter not surrounded by curly brackets.
Example **ret := ls({-1, *})** or **cp({-p, a, b, 2>/dev/null})**
Because the parentheses surounds the complet set of options and parameters another command can follow as in a pipe.
Example: **ls({*}) | sort({})** where as a parentheses only can be followed by | or || or &&. A semicolon is not allowed because an independend command should go in a new instuction field. If a command should go in background it should be coded in the parallel nsd element.

Hope this helps to better detect the elements for bash scripts and at least get a better code exported
Fine regards
Rolf

**Comment by codemanyak** [comment]
For me, it doesn't look sensible. It doesn't look natural either. Executor can't execute it anyway. Ignoring all commands means that the algorithm still can't be tested. So what for?
On BASH export, a function call is already dissolved to a command sequence (since this is the way a function is invoked in bash). The trouble is of course that Structorizer would recursively try to convert the arguments, e. g.
```
ret := ls(-l, *)
```
should be translated to:
```
ret=`ls -l *`
```
but produces:
```
ret=`ls $(( -l )) $(( * ))`
```
because the raw heuristics meant to find arithmetic operators `-` and `*` there. If the expressions would adhere to usual HLL paradigms, all would be fine - both hyphen and asterisk can't occur outside of arithmetic expressions pointers aren't supported by Structorizer.
As you obviously realised, Structorizer won't expect shell syntax, but hey, wouldn't you have to mark your entire code as shell syntax, not just the parameter lists?
Let's sort out what Structorizer may be expected to do and what not:
It CAN (within restrictions)

- execute some ordinary (HLL-like) algorithms
- export some ordinary (HLL-like) algorithms to different languages including bash
- let you write into the elements what you want and export it with the future export option to do as few content adaptations as possible (when version 3.24-05 will be ready).

It CANNOT

- execute bash scripts
- convert element texts written in bash or some hybrid between bahs and HLL syntax into bash scripts under the wrong assumption they were HLL instructions

This doesn't exclude that in some future there might be a second interpreter based on shell to support shell development in Structorizer. It is an interesting idea. But this won't be ready tomorrow. It won't even be begun tomorrow. It's not just the executor, its also a second version of the analyser, and so on. And still there will hardly be much possibilities to convert between HLL and shell.

**Comment by reks99** [comment]
@codemanyak Hi Kay.

First of all many thanks to the new version, it is great!
I see the differences. For me structorizer is a development tool, so I don't need the executer. If the exported programm has a correct structur and some goodies (like variable initialising or detecting) its good. 
You have a more generally view focused on testing algorithms for example with the executer.
Possibly only separate parser (not only for the bash) can solve the export problem.

Fine regards.
Rolf

**Comment by codemanyak** [comment]
On April 2, 2016 you (Rolf Schmidt) wrote:
> First of all many thanks to the new version, it is great!

Many thanks.

> For me structorizer is a development tool, so I don't need the executer.

This is a funny argument, indeed. (Okay, your point of view followed.)

> If the exported programm has a correct structure and some goodies (like variable initialising or detecting) it's good.

Here's the crux. Both at a time is difficult or even contradictory, at 
least and in particular with respect to Shell, I'm afraid.

> You have a more generally view focused on testing algorithms for example with the executer.
> Possibly only separate parser (not only for the bash) can solve the export problem.

That's it. Separate parsers, interpreters, cross compilers. All that 
could be fine, but expensive, enhancements for the future. At the time 
being no way.
