### ISSUE TITLE
export of IF constructs to bash uses parentheses instead of square brackets

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#148]
Hi @codemanyak Kay.

An export of decisions with if (without the new option "no conversion of expressions...") enclose the conditions in a double pair parenthese instead a (double) pair of square brackets. What is the reason for the bash code generater not to write square brackets.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I think I had mentioned it earlier.
Well, the code generator must be based on some assumptions. If the new export option is not active, then one of these assumptions is that it is exporting executable code following the HLL syntax paradigm.
This means that the occurrence of arithmetic operators is a sign that arithmetic operations may be involved. Tests on arithmetic operations work easier with (( )) because not only the arithmetic operators themselves are interpreted but also the comparison operators may be left as is, i .e. `==`, `!=`, `<`, `>`, `<=`, `>=` work fine.
With [[ ]] or just [ ], in contrast, all arithmetic comparison requires conversion of the comparison operators to something like -eq, -ne, -lt, -ge etc. (whereas comparison operators between strings are not to be converted). That would of course be feasible somehow, too, but the way to convert arithmetic expressions to (( )) looked favourable for me.
Whatever is tried here, relies on guesswork, as I had outlined in earlier comments. Otherwise a real compilation would have to be done, which would require strict variable typing etc. Let us keep it simple and live with some manual post-processing if Structorizer guessed wrong.

If you continue to formulate your boolean expressions with shell symbols and options, however, you should do it consequently and consistently all over the text, forget about variable detection and make use of the export option "no conversion..." (issue #144).
It just doesn't make sense and won't lead anywhere to concoct some kind of mixed syntax and hope it could work. It can't.
Therefore these (( )) enclaves in bash. Within double parantheses, there is an island of HLL syntax.
I know, in issue #146 you proposed exactly the inverse idea to create some shell syntax islands within Structorizer, marked by ({ }). The difference is, that in shell standards the [[ ]], (( )), and other syntactic workaround notations are well-established, whereas in Structorizer this proposal would always remain a bizarre oddity. There is no single HLL I know of where shell syntax islands were ever introduced. Please teach me better if I'm wrong. (Perhaps someone could qualify Perl as such a hybrid?) And if it were introduced nevertheless, then in my humble opinion it would have to work with Executor, Analyser etc. in a maximum consistent way. I just can't do that in near future, and I'm not even inclined to try because actually I have severe doubts that a large community of users out there would be appreciating or even demanding it.
It wouldn't be flesh nor fish in my eyes.

**Comment by codemanyak** [comment]
I forgot to write clearly that in the absence of arithmetic operators you will obtain the doubly bracketed conditions (i.e. enclosed in [[ ]]) you want. Not only in alternatives but also in loops.
Of course this isn't consistent either, because if you compare two variables then Structorizer wouldn't know what data type they are supposed to represent and just use [[ ]] (without conversion of the comparison operators), which would lead to a wrong (i.e. lexicographic) comparison in case the variables will contain integer literals and arithmetic comparison is intended.
Structorizer is just a bunch of algorithms, not a genius. I can't help it.

**Comment by codemanyak** [comment]
@reks99 May I close this for now?

**Comment by codemanyak** [comment]
@reks99 I'm going to close this issue if you don't veto.
