### ISSUE TITLE
Bug: When deleting an element with the "del"-key the nsd loses focus

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#164]
Hi,
if I delete an element of a nsd with the del key, the nsd losts it focus so I have to make a mouse click inside the nsd to work with keyboard movement or to delete another elemente or to insert a new element.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Structorizer doesn't lose focus. It's just that, after having deleted the selected element(s), there is no selection anymore (because the selected element(s) is/ are gone. This is not a bug from my point of view. It was just some sort of precaution against accidental collateral damage. Well, it might be an old-fashioned opinion to hesitate facilitating unwanted mass destruction...
Of course, in a sequence of elements, the element following the doomed one might adopt the selection. But what if you deleted the last element of an instruction sequence (e.g. in one of the branches of an alternative) - where should the selection go to, now? (In the example case: To the other branch - if not empty - , to the alternative as a whole, or to the next element folowing the alternative?) Certainly, some candidates for selection inheritance will be more intuitive than others, but have you thought about it? It will rather not be the same traversing order as in the key-driven selection moves just implemented for issue #158, will it?

**Comment by reks99** [comment]
Hi Kay,

Lost focus means that no key action is accepted until you klick into the nsd - so working with keyboard becomes interrupted

For the delete problem: IMHO the next element should be selected and if it was the last element, the previous is the next to operate with.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> Lost focus means that no key action is accepted until you klick into the nsd - so working with keyboard becomes interrupted

Okay, this is the consequence of the absence of a selected element.

> For the delete problem: IMHO the next element should be selected and if it was the last element, the previous is the next to operate with.

Sounds simple, but is ambiguous again as soon as you instect the 
consequences into more detail: Would this have to hold within each 
subtree sequence (e.g. in a branch of an alternative or selection) or 
only for the outermost sequence (on procedure level)? (In the first case 
it would mean you first empty the entire subqueue before selection 
leaves this level, which might be okay.
Where is the selection to leap to after having emptied a sequence at a 
subtree level? Sibling (if there is any; if there are more than one, 
first next right sibling, then next etc., then left siblings)? Parent 
node? Successor of the parent node? Possibly all these in exactly this 
priority order?
I'm still in doubt whether this would be so good, but it might make 
sense if sound rules can be found.

I wil think about such a set of rules.

**Comment by codemanyak** [comment]
A viable compromise could be to keep the rules as simple as this:

1. If the deleted element (or subsequence) has a successor at its own nesting level (within the Subqueue) then this will be the selection heir.
2. Otherwise if the deleted element (or subsequence) has a predecessor at its own nesting level (within the Subqueue) then this will be the selection heir.
3. Otherwise the emptied Subqueue will catch the selection, this way stopping the repetetive deletion sequence (an empty element cannot be deleted).

**Comment by reks99** [comment]
Hi Kay,

this sounds good.
For me it will be ok, if the nsd (i.e. the main frame) keeps the focus, so I can continue to work with the keyboard - i.e. have not to use the mouse to select the nsd.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 So you may look forward to version 3.24-08

**Comment by reks99** [comment]
Hi Kay,

delete works nice now. No more lost of focus.

Thank you very much.
Rolf
