### ISSUE TITLE
No focus set, when structorizer is started or code was exported

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#169]
Hi,

when structorizer is started the nsd is not selected, so no operations with the keyboard is possible. You have to click with the mouse into the nsd, to start working (with the keyboard).
Also when code of the current nsd was generated, the focus is lost and you have to click into the nsd to continue working with the keyboard

Fine regards
Rolf

**Comment by codemanyak** [comment]
For some earlier version, the clearing of the selection on operations like execution start, image or code export etc. had explicitly been introduced. For the executor this had been sensible because earlier there had not been a different highlighting for the currently executed element. On image export (by Ctrl-D, Ctrl-E etc.), some users might have been annoyed that the selection was also exported, though I personally hadn't been unhappy about the opportunity to export / print diagrams with a selcted element - but well, a screenshot with selection had still been possible.

On starting the Structorizer with an empty or a given structogram it had justed seemed the most logical thing to initialize it without a selected element. Of course, it might be possible to select the outer frame (the Root element) on starting.
In analogy to up-to-date office applications it might even be an idea to store the selection on saving and to restore it on loading (scrolling to that element). But perhaps this may not hold for everybody. And it would cause some difficulties with multiple selection.

**Comment by codemanyak** [comment]
By the way, you will certainly have observed that the selection will always get lost after undoing or redoing recent changes, too? Should that be changed as well? Possibly be reestablishing the last selection before the undoable / redoable action?

**Comment by reks99** [comment]
Hi Kay,

when the outer frame is selected after start, it is ok, because cursor and keybord will work.

Fine regards
Rolf

**Comment by reks99** [comment]
Hi Kay.

Deselect on export: Does any thing speaks against to keep the selected element "in mind", deselect it, export the nsd and select the element again?

Problems with undo: Last time I did an undo structorizer dies. Because I can not reproduce the situation so no bug report is written.

I think structorizer was primarily a drawin program which implies, that most of the work will be done using the mouse. But in real no lines will be drawn by the mouse, so a keybord interface will be faster especially there is always a need for text input. Switch between keyboard and mouse is unproductive.

So, where ever possible,  the nsd should stay selected either the outer frame or an element, to continue working with the keyboard. Just my though.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Solution available on bugfix branch (including selection restauration on undo/redo), due for integration (-> version 3.24-09)

**Comment by codemanyak** [comment]
The provided fix still fails to select the default diagram on start. Will have to be accomplished in the next version.

**Comment by codemanyak** [comment]
Accomplished fix available on bugfix3.24 branch.

**Comment by reks99** [comment]
Hi Kay,

now work with the keyboard is superb. I once again would say thank you and I thing the keyboard interface is a big enhencement to structorizer. I like it very much.

Fine regards
Rolf
