### ISSUE TITLE
Enhancement. The ins-key may open the menu to insert an element

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#170]
Hi,

When an element is selected and the ins-key is pressed the submenue (i.e. as a context menue) as in "Diagram | Add" might pop up, so the element can be choose with mouse movement.

Fine regards
Rolf

**Comment by codemanyak** [comment]
You know that Alt-A opens the add menu?

**Comment by reks99** [comment]
Hi Kay,

I didn't know that.

The idea came up, when I worked on a nsd. "Suddely my fingers go to the insert key and I thought, why can I insert a new element this way - it was intutive for me"

Fine regards
Rolf

**Comment by codemanyak** [comment]
Usually the insert key has a toggling effect in text editing nowadays - it switches between overwrite and insert mode. Therefore I hesitate to add this additional key binding because it wouldn't be consistent to this behaviour or might have unwanted side-effects.
The Alt-A mechanism s not a secret on the other hand. The Alt key is a generic method to activate menu short keys. The respective letters appear underlined in the menu bar (if they occur within the menu caption).
Hence I suggest to live with this opportunity. Moreover, there are accelerator keys for almost all specific insertions both below and above the selected element now (cf. #142). This should be enough, I'd say.
@reks99 Do you agree?

**Comment by codemanyak** [comment]
Wondering why there is no mnemonic for the Help menu, I just detected that the Alt-A was originally preserved for the Help menu (formerly named "About") and erroneously overrides the mnemonic of the Diagram menu - being Alt-D!
I'm going prepare a fix for these mnemonics for the next version and an enhancement for the language files such that the mnemonics may be adapted on localisation.

**Comment by reks99** [comment]
Hi Kay.

I can live with this. 

BTW: a key can have different functions in different situations. So the insert key may toggle insert and overwrite modus in a text area and another function for example in the nsd manoevering 

May we close this issue?

Fine regards.
Rolf

**Comment by codemanyak** [comment]
From my point view I'd close it now...
