### ISSUE TITLE
unable to save a struct

### ISSUE THREAD

**Issue by sepp2gl** [fesch/Structorizer.Desktop#178]
Hi all,
being new to structorizer, I played around a bit with it creating a tiny structure.
I saved it first time as "beispiel.nsd".
After I added further elements, the program refused any further saving, no matter which name I gave.

> Error-Message: "Error on saving the file: Null!"

The files were created, but they contained only the starting struct.
Thanks for any proposal,
sepp2gl

**Comment by codemanyak** [comment]
@sepp2gl:

1. Can you please name the Structorizer version you are working with?
2. Would you please export the created diagram (the one causing the 
saving problem) as PNG and upload this file here?

This would help a lot in identifyin the problem. Thanks in advance.

**Comment by codemanyak** [comment]
@sepp2gl Some hints welcome?
The title bar of Structorizer should display a version number. If not - then your version is definitely obsolete. Get the latest version (3.24-10) for your operating system from the Download page of the [Structorizer home page](structorizer.fisch.lu). Secondary download sites usually offer outdated releases.
You certainly know how to get Structorizer started on your computer, otherwise you wouldn't have sent this issue. For more help, the on-line [User Guide](http://help.structorizer.fisch.lu/index.php?menu=44&page=) may be useful, though most of the basic functionality is self-explaining.
In order to export an image of your diagram (rather than the failing nsd file) go to the menu **File => Export => Picture ... => PNG** (or just press Ctrl-E).

**Comment by sepp2gl** [comment]
@codemanyak:
thx for fast response.
I am currently using 3.23.00.

Unfortunately I killed the trial-model, that I was not able to save yesterday in the meantime,
and I am not anymore able to regenerate the error.
So we should close this thread (unfortunately). I beg your pardon for consuming your time.
kr, sepp2gl

**Comment by codemanyak** [comment]
Thank you for answering and closing the issue. Nevertheless I recommend to use the most recent development version. Against the usual attributation, it is definitely more stable than 3.23-00.
A look at the [changelog](http://structorizer.fisch.lu/index.php?include=changelog) on the Structorizer homepage ought to convince you that a lot of bugfixing and functional improvements has been done since 3.23-00 to the benefits of the user. 3.23-00 is 27 versions back, actually!

**Comment by codemanyak** [comment]
Actually, this issue was identical to the bug #82 solved with 3.23-08.
