### ISSUE TITLE
BUG: Function key F10 does not insert case element below

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#233]
Hi

I found that the function key F10 opens the file menue instead  to insert a new case statment below the current element.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I can reproduce the behaviour, though I have not found an explanation 
for it so far. The code seems to be okay. Maybe there are some hidden 
correlations behind the scenes that the accelerator kay is mistakenly 
confused with a menu menomic. Interestingly, the choice of the file menu 
mnemonic (as induced by a language change) has absolutely no influence.
In addition, the malfunction seems to be very old (or it's a Java Swing 
bug): Structorizer version 3.19 reacts in the same way!
I will care about this after my vacations have ended.

**Comment by codemanyak** [comment]
A little research effort revealed that this is indeed a Java Swing effect - by default, F10 is caught by the menu bar to obtain the focus such that the (correctly) configured key binding for insertion of a CASE element won't work as it has lower priority. F10 can be deleted from the menu bar input map quite easily. This will re-establish the documented Structorizer functionality. I just hope that no one adamantly insists on the Java Swing standard behaviour of F10 in order to move the focus to the menu bar... I think the configured menomics (Alt+some menomic letter) for the menus be an acceptable workaround.

**Comment by codemanyak** [comment]
At least since enhancement #305 the function keys F6 and F8 don't insert the associated elements (Alternative and WHILE loop, respectively) anymore but are snatched away by the SplitPanes to move the focus around work area, arranger index, and report list or select a divider and avert the cursor keys to move the divider.
F6 isn't needed to circle the focus around since tab key and Shift-tab do it already. The key control of the divider positions might be sensible in certain contexts but can be handed over to Ctrl-F8.

**Comment by codemanyak** [comment]
Fix prepared for version 3.26-02 (already in bugfix3.26 branch)
