### ISSUE TITLE
BUG: When export nsd to bash there is rubbish in the code

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#234]
Hi,

When export a nsd to bash code, there are always the following lines in the script direct down the line "# (generated by Structorizer 3.24-14).

' # chr() - converts decimal value to its ASCII character representation 
' chr() {
'  printf \\$(printf '%03o' $1)
' }
' # ord() - converts ASCII character to its decimal value 
' ord() {
'  printf '%d' "'$1"
' }

I use latest version for download available which is numberd 3.2.4-14
When test the nsd with version 3.24-11 the export is ok - non of the reported rubish.

Fine regards
Rolf

**Comment by codemanyak** [comment]
This is not exactly rubbish. It's a removable precaution for the possible use of one of the functions `ord` or `chr` as are provided by Executor as character to code (and vice versa) conversion functions borrowed by Pascal. These implementing shell functions were introduced by version 3.24-06. The change wasn't regarded as harmful.
Of course, it must not be produced in case of activated export option "no conversion of instruction/expression contents". This is a bug.
Moreover, the code expression might be restricted to cases of actual usages of one of these functions in the diagram. But this would have required an extra translator pass to detect the occurrance of these functions which I thought then was unnecessary overhead - as the user might more easily remove the code (if superfluous) than add it (in case of necessity).
For the next release (3.25), however, a configurable detector pass for the generator was added anyway, so it might be used to avoid the expression it not necessary.
Both will be fixed with the pending release.
