### ISSUE TITLE
Request: Structorizer User Guide

### ISSUE THREAD

**Issue by mtstorm** [fesch/Structorizer.Desktop#235]
We wish to use the application in one of our courses. Can we integrate the guide in the course? We use docbook and we did not find the documentation in git. If you wish we can help to do the conversion :-)

**Comment by codemanyak** [comment]
What kind of conversion do you ask for? You know that you can download a PDF version of the User Guide from the [Structorizer home page](http://structorizer.fisch.lu)? Moreover, selecting the menu item `Help -> User Guide` or pressing button `F1` in Structorizer itself opens the online user guide in the browser, at least in the latest version (3.24-14).

**Comment by codemanyak** [comment]
Oh, sorry, you already wrote that you want to integrate it in DocBook format. I overlooked it.
Still, the question remains what DocBook version (5.0?).
By now, the user guide is authored in a proprietary CMS based on HTML. So it would have to be rewritten (at least partially) unless tools like [DocParse](http://www.xml.com/pub/p/423) or html2db might be tried for an automatic conversion from HTML to DocBook.
I also found the following advice in the [oXygen XML forum](www.oxygenxml.com/forum/topic2049.html):

> You can copy and paste from a browser to a DocBook 5 file and if that is open in the Author editing mode then oXygen will trigger its smart paste conversion to DocBook5

We haven't checked any of these possibilities by now.

**Comment by mtstorm** [comment]
Yes I know, but you can not integrate it in other documentation. We use docbook for this, and that can generate documents to any kind of format, like pdf, epub, html eg.

**Comment by codemanyak** [comment]
Well, from my point of view, your offered help will certainly be very welcome. I can't imagine Bob objecting ;-)
We both just returned from vacation, and he will certainly have found a similarly high pile of work to be done ASAP, too. As the originator of the CMS the User Guide is being maintained in, he had made a noticable effort to establish a way to derive a PDF document. I'm sure he will appreciate your experience in the development of a conversion to DocBook.
A different decision will then be whether to continue editing the User Guide it in the CMS and regularly to derive the DocBook version by script (in order to allow various further conversions) or to switch to maintaining the User Guide in DocBook primarily where at least I have no experience).

**Comment by reks99** [comment]
Hi,

I find it a good idea to have the documentation in docBook, so everybody who wants can translate or enhance it by itself - if wanted.

Just my 2 ct.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 I think we understood that. Bob's looking for solutions.

**Comment by codemanyak** [comment]
@mtstorm Hi, are you able to convert the [single-HTML version](http://structorizer.fisch.lu/Export) of the User Guide as offered by the Structorizer homepage to DocBook or do you still need further support?

**Comment by mtstorm** [comment]
Sorry for the delay. I can start converting the existing documents to docbook format version 5. I will start it this weekend. It will take some time for me, but I will keep you posted.

**Comment by GitMensch** [comment]
@codemanyak If I understood this correctly it is a one time conversion to DocBook (at least partly a manual process) and then place the DocBook in the source tree and make changes there + easily generate a HTML version from the file when preparing a release - no further documentation would be done in the HTML file.

**Comment by mtstorm** [comment]
Yes that is correct.

**Comment by fesch** [comment]
Just to notice: this would kill the online help, wouldn't it?

**Comment by GitMensch** [comment]
No, you just need a build-step in your IDE or in the make-scripts and the online help would be regenerated from the DocBook.

**Comment by fesch** [comment]
Cool, didn't know that DocBook could generate SQL code :-D

**Comment by GitMensch** [comment]
You've stored the content of http://help.structorizer.fisch.lu/index.php in a database?
I think this shouldn't be necessary any more when the conversion to DocBook is finished. GCC generates it documentation from texinfo files to PDF, HTML single page and HTML multi page - I think DocBook should be able to do the same conversions. If I remember correctly the images are stored external, therefore the final source wouldn't be stored in the database but in a subfolder at github.

Before this big work is started can I suggest to think about using [reStructuredText][1] instead of the the Docbook format? It can be converted to many output formats, too and with [Read the docs][2] there is a nice online frontend for browsing the docs which are stored at the project's GitHub repository under a doc subdirectory. Therefore people can easily (if they know how to use GitHub) do a change and pull Request (Read the Docs includes a "Edit on GitHub" button). For an example see [here](http://opencobolide.readthedocs.io/en/latest/getting_started.html), browse the page and click the "Edit" button in the upper right corner.

[1]:https://en.wikipedia.org/wiki/ReStructuredText
[2]:http://readthedocs.io/

**Comment by fesch** [comment]
http://help.structorizer.fisch.lu/index.php is the front end.
All content, except for the images, is stored in the database and edited via CMS.

I have no need to change anything. What is in place, is fine for me.

**Comment by GitMensch** [comment]
> I have no need to change anything. What is in place, is fine for me.

The nice thing if it would be changed to RST:
* manual is easily versioned and tagged along with the version, people always get the "correct" version -  especially important is "master" and "last release" of course
* manual can be easily updated by others, they can simply add a pull request, you still decide what is in
* manual can be more easily translated
* manual is directly available offline and can be generated in multiple formats with multiple layouts

You can still use the old frontend and/or (maybe additional for versions other than the latest release) something like Read the Docs,

Please give this a thought - the conversion isn't worth the work if you won't do the changes in-tree later.

**Comment by GitMensch** [comment]
I've just checked the [current user guide](https://structorizer.fisch.lu/index.php?include=userguide). It is just marvelous!

But still I'd like to be able to provide PR for it, which would only be possible if the sources are kept 100% in Git instead of a CMS.

Re-Reading this topic @fesch and @codemanyak seems to have different views about the "import once and provide export option [done by @mtstorm], only work on the repo, export from the repo on (sub-)releases".

Am I right that this part is already rejected? I don't think the export to PDF would be that beautiful as the current version is, but @mtstorm can likely say something about this.
The biggest benefit would still be that people can easily translate the manual and the translated versions could be integrated in the repo, too...

@fesch If you reject the move from CMS to "different", does the used CMS supports staging and if yes, would you add me to the editor list with stage-only rights allowing to suggest minor edits directly?

**Comment by fesch** [comment]
No, the CMS has no staging. All changes applied are immediately online. But I can add you as editor if you want to.

I have no problem with the fact that somebody wants to move the content of the CMS to something different, but I clearly want to announce that this person will not be me and that whoever will do this job has to provide a new PDF on each sub-version.

I don't want to see forks on the user guide, so either everything is moved of nothing. For me, this will clearly be binary ;-)

**Comment by codemanyak** [comment]
@GitMensch Just some remarks from my part without ambitions to give a comprehensive
evaluation of your suggestions.
> The biggest benefit would still be that people can easily translate the manual and the translated versions could be integrated in the repo, too...

I think this benefit might be limited, as I have my reservations about automatic translation in the first place and about the future maintenance of linguistically updated ranslations in combination with added or modified master content.

> manual is easily versioned and tagged along with the version, people always get the "correct" version - especially important is "master" and "last release" of course.

Usually, the user guide updating is evolutionary i.e. the guide specifies what features are new (from which version on) and which ones are deprecated. The version references vanish over the time, of course, when the current version can be regarded as sufficiently spread. Butv also tries to explain old stuff in a better way. From my point of view it makes absolutely no sense to read an obsolete user guide when working with an obsolete version of Structorizer. And though I try my best to have all relevant news in the user guide when the next Structorizer version is due, I cannot guarantee that. So, updating the user guide is a somewhat gliding process, even between the versions.

Just saw @fesch answering...
> I don't want to see forks on the user guide, so either everything is moved of nothing. For me, this will clearly be binary ;-)

I absolutely agree.

>  I clearly want to announce that this person will not be me and that whoever will do this job has to provide a new PDF on each sub-version.

Having just checked how many competetive document markup languages and tools there are, I'm absolutely sure that whatever one might fancy here will annoy many others. End users will usually by fine with a PDF and/or Html version and won't give a fart by means of which technology it was prodiúced as far as it is instructive and up to date. I'm fine with Bob's CMS and don't have the least ambitions to rewrite all the stuff in this or hat cryptic markup language, either.

**Comment by GitMensch** [comment]
@mtstorm So the next step is all to you. Do you want to invest the effort to:

* do the one time conversion to "something" (I assume DocBook, something I personally didn't used before)
* automated conversion to at least single page html, all-in-one html and PDF from the resulting document (= the current formats), more possible if you like to by calling a script which calls necessary tools (hopefully not too much / too big dependencies)

?

Otherwise we should close this issue.


@fesch Yes, please add me to the CMS and point me to some basic instructions.

**Comment by fesch** [comment]
@GitMensch : May I get your email-address please?

**Comment by codemanyak** [comment]
I think we may close this issue now. The initiator seems to have lost interest.
