### ISSUE TITLE
Request Turtleizer Background Color

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#302]
It would be nice to have a way to set the Turtle Background either by a property, or even better by a turtle command i.e. "backgroundColor(255,255,255)" or somethink the like.

**Comment by codemanyak** [comment]
Interesting idea. If it is to be a turtle command then I'd suggest the background is to be reset to white on every program start (i.e. whenever a new main diagram execution is started). Would you agree?

**Comment by codemanyak** [comment]
The requested enhancement is prepared for the next version (3.25-09). The procedure added to he Turtleizer API is named setBackground(red, green, blue) where the three arguments my range between 0 and 255 each.

**Comment by newboerg** [comment]
Very Nice, how about an setPenColor(R,G,B) then too? It could override the Color setting set by the diagramm color.

**Comment by fesch** [comment]
We are getting closer to Logo ;-)

**Comment by codemanyak** [comment]
> Very Nice, how about an setPenColor(R,G,B) then too? It could override the Color setting set by the diagramm color.
Well, I had already thought about that, too. But I would rather suggest otherwise: setPenColor ought to set the (permanent) default pen colour (to be used instead of black by forward/backward statements in standard white Instruction elements) that can be overidden temporarily by the diagram element colour. Makes more sense in my eyes.

**Comment by codemanyak** [comment]
In analogy to setBackground, the impact of setPenColor is to be lifted on next execution start because a main diagram execution must not influence the way the next diagram execution works. As a bugfix, a previous hideTurtle effect must also be undone on execution start. The same holds for the effect of penUp().
