### ISSUE TITLE
Not seeing the menu

### ISSUE THREAD

**Issue by sebastiaanspeck** [fesch/Structorizer.Desktop#304]
I don't see the menu:

![javaw_2016-12-06_11-21-10](https://cloud.githubusercontent.com/assets/12570668/20921840/36425a24-bba6-11e6-9ce7-56112d9ee53d.png)

**Comment by codemanyak** [comment]
That' s pretty strange.
Is it reproducible on every start, or does it sometimes appear, sometimes not? 
Apparently you are working in a Windows OS version. Could you pleace specify the Windows OS release and the Java RE version?
Next I would like to ask you to to start Structorizer from an MSDOS shell window (cmd.exe), using Structorizer.bat in order to see possible error messages or stacktraces at the console (standard or error output stream). I know that there are often GUI initialization races on start resulting in some erratic NullPointerExceptions. Maybe it ha to do with it, maybe not.
Thanks in advance for your efforts to identify he problem.

**Comment by sebastiaanspeck** [comment]
It is that way every start and also if I download the .zip-file again. I got Windows 7 Enterprise SP 1 and Java 6.043.1. If I start Structorizer.bat I get the following Errors: 
![cmd_2016-12-06_12-22-03](https://cloud.githubusercontent.com/assets/12570668/20923838/a519a2c4-bbae-11e6-9649-f3e369353c1a.png)

**Comment by codemanyak** [comment]
Okay, I see. A method requiring Java 1.7 is the show stopper. Could you update your Java RE, or will it be necessary to downgrade the application code?

**Comment by sebastiaanspeck** [comment]
I can't update Java RE. How can I downgrade the application code

**Comment by fesch** [comment]
You cannot. We need to do that ... :-/

**Comment by sebastiaanspeck** [comment]
I wish you luck

**Comment by codemanyak** [comment]
Many thanks. This is not going to be easy. Unfortunately, there has not been a sensible substitute for method KeyEvent.getExtendedKeyCodeForChar(char) in legacy Java versions. To circumvent it in a secure way would require some really ugly workaround. I'm afraid I will have to set up an own reverse key code map which is likely to fail with different OS versions. :-(

**Comment by codemanyak** [comment]
@sebastiaanspeck 
Okay. I think I can offer you a workaround. As the error is related to a rather subordinate task - the menu mnemonic localization -, I just skip it if the needed method isn't available. I would like to ask you to test this approach by replacing your Structorizer.jar (situated in subfolder Structoizer.app/Contents/Jar) by the Structorizer.jar contained in the file attachment. If this fix works at your site then we will make it part of the next version. Hence it would be very helpful if you could give us feedback whether it works.

[Structorizer.jar.3.25-09x.zip](https://github.com/fesch/Structorizer.Desktop/files/637121/Structorizer.jar.3.25-09x.zip)

**Comment by codemanyak** [comment]
@sebastiaanspeck
Please excuse the misspelled folder path in my last reply - I meant `Structorizer.app/Contents/Java`, of course.

**Comment by sebastiaanspeck** [comment]
Yes, this works! Many thanks
