### ISSUE TITLE
Unexpected For-Loop behavior

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#307]
I've noticed a strange behavior when trying to show my students that every Loop type could be expressed as the other. Most notably that the FOR-Loop is an WHILE-Loop.

In Structorizer you cannot access the Counter Variable from within in Loop. It seems the Variable inside resides in another scope EVEN when declared beforehand.
![strange](https://cloud.githubusercontent.com/assets/7376421/21098141/05c67198-c068-11e6-8c70-1a8a81376034.png)
The First Example yields 10, the latter 1.
Is this intended?

**Comment by fesch** [comment]
No I don't think this is intended ...

**Comment by codemanyak** [comment]
I would like to contradivct. Actually it is intended. The manipulation of the for loop variable is deemed illegal (as is in Pascal). It breaks the expectations of a FOR loop. The Analyser complains about it, the Executor just ignores it.
In a WHILE loop, in contrast, we rely on explicit changes to the loop variable in order to have a chance to get out of it. This is also checed by the Analyser.
With this regard, both loops are indeed not equivalent. To trasmute a "defective" FOR loop may result in unexpected behaviour. The fact that such a for loop variable is accepted in some languages doesn't make it a good programming style. Please have in mind that if we allowed for loop manipulation in Structorizer we couldn't export the code to languages like Pascal and Oberon any longer.
Maybe the Executor should even raise an error?

**Comment by newboerg** [comment]
I see, if its not allowed in Pascal,  from where Structorizer lend the "<-" operator i guess . then an executer error would be nice to have. No Problem to "code" around if you want C-Like behavior but an error would be good.

**Comment by codemanyak** [comment]
Indeed even an inconsistency arises on execution: Since the Executor isn't aware of the manipulation of the loop variable (not at least by now ;-), the assignments and alterations will last till the end of the loop body (e.g. the manipulated X value can even be output within the loop), but then ignored and effectively undone when the loop mechanism takes control again.
So I will introduce a mechanism recursively to keep track of counter variables in order to reject the manipulation at run time.

**Comment by codemanyak** [comment]
Code fix is prepared for version 3.25-10
