### ISSUE TITLE
Structorizer on Windows 10

### ISSUE THREAD

**Issue by lhoreman** [fesch/Structorizer.Desktop#323]
I just installed the latest version of Structorizer on Windows 10. Everything is too small, the buttons, the menu, code, ... I installed the latest verion of Java.
Do you know how I can solve this?

Lieve

**Comment by codemanyak** [comment]
What you may try is described in the User Manual in section [Preferences / GUI Scaling](http://help.structorizer.fisch.lu/index.php?menu=123&page=).

**Comment by lhoreman** [comment]
It workst for the buttons but the window with the code stays very small. 
My menu's also don't work.

**Comment by lhoreman** [comment]
Opening an existing nsd-file does not work. The window doesn't change, only the file name is put in the caption bar

**Comment by codemanyak** [comment]
> It works for the buttons but the window with the code stays very small.
My menus also don't work.

1. Could you please upload a screenshot of your Structorizer with something in the diagram work area?
2. Would you mind opening a console (via cmd.exe) and start Structorizer from there by executing Structorizer.bat (situated in the Structorizer installation folder), such that we might get possible error messages? (Send these error messages hitherto, please.)
3. Please specify the Java RM version. Is ist 1.8.0_111/1.8.0_112 or even newer?
4. The Structorizer version in the title bar should be 3.25-11, right?

> Opening an existing nsd-file does not work. The window doesn't change, only the file name is put in the caption bar

Very strange. No error message, nothing? How did you try to ope the NSD file without a menu? By dragging the fle into the Structorizer work area? By double-clicking an NSD file? Or by Ctrl-O?
Well, I guess, something went really wrong on initializing Structorizer GUI such that not only the menu is damaged but also the work area or some necessary components. I expect you'll see further errror messages in the MSDOS console when you try to open an NSD file.

**Comment by codemanyak** [comment]
@lhoreman 
As your report about the missing menu reminds me to issue #304, I would also like you to test whether a preliminary workaround sent when that issue was raised would work w.r.t. the menu visibility at your site:
[Structorizer.jar 3.25-09x](https://github.com/fesch/Structorizer.Desktop/files/637121/Structorizer.jar.3.25-09x.zip)
Make a copy of your Structorizer folder and replace the copy of the Structorizer.jar found there in subdirectory Structorizer.app/Contents/Java by the file conteined in the zip file referred to above. This is an earlier version, of course, but the workaround tha solved the problem there was redesigned a little for versions 3.25-10 and 3.25-11. Possibly the simplified code isn't as effective as the original workaround.

**Comment by lhoreman** [comment]
I installed everything once again. Most problems are solved, except....
The title bar now shows 3.25-11
After adding scaleFactor to .ini:
![afbeelding](https://cloud.githubusercontent.com/assets/11858847/21715605/d1df8a0c-d405-11e6-8d0b-0149b6fdbeb9.png)
It is still impossible to read the text.

**Comment by codemanyak** [comment]
Okay. You should have two fine buttons at the very end of the toolbar for free configuration of the diagram font size. In the preferences menu you may also choose a different font if you like.
Please forget my previous recommendation. You don't need that preliminary Structorizer.jar file, obviously.

**Comment by lhoreman** [comment]
Thanks! It is not perfect but it will do
