### ISSUE TITLE
Windows 10 Pro problems

### ISSUE THREAD

**Issue by DonRoberto123** [fesch/Structorizer.Desktop#334]
![2017-01-14](https://cloud.githubusercontent.com/assets/25156269/21991561/63f6ae60-dc13-11e6-9a5b-5de05f079431.png)
i have problems with windows 10 pro structorizer ... .

if i use web start structorizer, or regular app it distorts structorizer ... .

i am on w 10 pro x 64 dutch ... .

**Comment by fesch** [comment]
Did you try to play fir the Look and Feels?

**Comment by DonRoberto123** [comment]
i dont understand :s

**Comment by DonRoberto123** [comment]
i used my mouse, to hover on ok, and the whole screen distortend :s

**Comment by fesch** [comment]
In the menu: Preferences > Look & Feel

**Comment by codemanyak** [comment]
@DonRoberto123 
Just some additional questions from my part (it looks as if some unhandled exception stalled the Structorizer GUI):

- What Java version are you running? (Start the Java configuration panel and look either into the "Info..." on the left-most tab or click on the "View" button on the "Java" tab  in order to see which JavaRE is actually running).
- Could you try to start Structorizer from the command line via Structorizer.bat (to be found in the Structorizer folder) in order to see possible error messages or tracebacks - send us the error output in this case, please.

Thanks in advance.

**Comment by codemanyak** [comment]
@DonRoberto123 
Hi Don Roberto,
maybe the deadline of your homework has already expired and you don't see the need for our help anymore, but nevertheless we are interesting in identifying and possibly solving the problem you experienced. What we are not, however, is clearvoyants; you were the first and only one so far who reported this kind of trouble, so we depend on your co-operation to find out what's going on at your site.
Therefore please inform us if the problem has gone or try to answer the questions asked otherwise (Did you try with a different Look & Feel? What Java version is used? Are there error messages at the console output of Structorizer?). This would be of great help for us and for the benefit of other users.

**Comment by DonRoberto123** [comment]
Hi, the java version used is java 8 version 111 64 bits ... .

my windows is 10 pro 64 bits ... .

i tried searching, the structorizer map, it used to be on my desktop, and from there, i used the .exe, but with the recent update, to windows v 1607 ... . It seems to have disappeared ... .

I can not find the folder ... .

But i have tried, the look & feel thing, and so far, i put it to windows classic, and so far, i see no problems, although, i only tested it once, in my course, on programming, i follow, at vdab, which is a site for searching work in belgium, but they also offer tutorials, but i have been kind of busy a bit lately, so i could not continue, my course, but as soon, as i reinstall structorizer, and open it with the .bat file, the batch command, i will then put in any errors, if there were any ... .

**Comment by DonRoberto123** [comment]
hello, there has been a new java update 121 and now it seems like my problem is gone ... .

i am gonna c if there is any improvemenbtn, in my structorizer, and if there are no problems within the week, i'll close this issue, thx for helping me out ... .

it seems, like the java update 121 did the trick ....  .

**Comment by codemanyak** [comment]
Thanks for the status update and the apparently good news. Maybe there was an incompatibility issue between Java 1.8_111 and Windows 10 Pro we had neither been aware of nor would we have been able to circumvent it easily, I'm afraid. But it's good to know there is a critical constellation and that it seems to have been overcome. Thank you again.

**Comment by codemanyak** [comment]
Seems the issue may be closed now. Just reopen it, please, in case there are still problems.
