### ISSUE TITLE
Add more Javadoc in lu.fisch.structorizer.generators.Generator

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#361]
codemanyak's [howto.txt](https://github.com/fesch/Structorizer.Desktop/files/813411/howto.txt) actually provides a nice description the the abstract configuration methods.
Please include them inlu.fisch.structorizer.generators.Generator.java enabling creating new generators more easily.

**Comment by fesch** [comment]
nice idea ;)

**Comment by GitMensch** [comment]
If it is a nice idea to include the documentation of @codemanyak in the Javadoc for these functions shouldn't the issue be open until it is done?

**Comment by fesch** [comment]
Did sou see the line "fesch added a commit that referenced this issue 3 hours ago"?
I've integrated the file. After having pushed the commit to the server, I've closed the issue.

**Comment by codemanyak** [comment]
@GitMensch 
Are you kidding? Major parts of the howto file are copies from the Javadoc method comments. Okay, some of them might be missing or incomplete, but most of them are there.
But I understand that you want it to be Javadoc class comment of `Generator`, right? Because it's hard to find the distributed method comments? Okay, it will be done, eventually. Just give me some time, please. I'm wrestling with the parser...

**Comment by GitMensch** [comment]
I see, not all but many are included in the Javadoc already. I now see them in Eclipse, too...
Yes, please update where appropriate, I won't find the time to work on the generator until end of next week.

But if you have a parser to test from Git I have some nice C (and COBOL) stuff laying around ;-)
It is definitely a good idea to put the efforts in this place.
