### ISSUE TITLE
Proposal: Add invert True False on if

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#367]
Could we get an invert "True/False" option button in the if block?

**Comment by fesch** [comment]
Why would you like to do this?

**Comment by newboerg** [comment]
purely cosmetic reasons :-)

**Comment by fesch** [comment]
Then I'll classify this as "nice to have". Actually there are no plans to invert this, but there is a good reason why it is like it is and I think Nassi & Shneiderman defined it that way for the same obvious reason:

Did you ever see an "if" with just an "else" part? I never did ... because it should be avoided! If you get such a case, please invert the condition and leave the "else" part blank.

Reading diagrams is like reading books: from the left to the right side. So empty blocks should stay a the most right side, not at the left side. Do you agree?

**Comment by newboerg** [comment]
I Agree, absolutely. It would not be easier to read if it would change frequently too.

But sometimes it is way more understandable if you dont invert the logic but draw the blocks the other way around. Then the False would be on the Left side for the whole diagramm and you would avoid "!"-s

**Comment by fesch** [comment]
@codemanyak : What do you think of this?

**Comment by codemanyak** [comment]
Thanks for asking. I would reject any intension to leave an If block with empty TRUE branch, too. But what I could imagine is a little **transmutation** :wink: that facilitates the inversion of a mal-designed IF, i.e. if the user formulated the condition so awkwardly that the alternative ends up with an empty TRUE branch. Then why not try to help turning it around and inverting the condition automatically? If both branches are filled then it might also be a welcome help to have a tool to swap the logic. The trivial way would be to put a `not` operator in front of the former condition; the more ambitious approach would be to invert comparison operators, to apply deMorgan's law or something the like rather than to blow the condition up with `not` prefixes.
But before I try to do this, I will have implemented an expression grammar for Structorizer elements. I will definitely not fiddle around with regular expressions etc. in sentences of a context-free language...
It's clearly a MINOR NICE TO HAVE on he priority list.

**Comment by codemanyak** [comment]
> But sometimes it is way more understandable if you dont invert the logic but draw the blocks the other way around. Then the False would be on the Left side for the whole diagramm and you would avoid "!"-s

This is something we should NEVER do. It is a well-established convention that the TRUE branch be always on the left side and the FALSE branch on the right-hand side. In the code you won't start with the else branch either. It would be utterly confusing - like ghost drivers on the wrong lane.

**Comment by codemanyak** [comment]
The implemented transmutation to swap IF branches didn't correctly reshape the diagram because the invalidation had the wrong direction (went tree down instead of up).
Will be fixed with version 3.28-10.
