### ISSUE TITLE
Keyword refactoring on file open must be enforced, otherwise load destroys the file

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#370]
This was highlighted when testing with the provided samples at https://github.com/fesch/Structorizer.Desktop/issues/357#issuecomment-284074857

* the nsd files contain the keyword settings
* the loaded nsd file ignores them, says the words used as keywords (if they differ from the global setting) are not initialized variables
* when saving the nsd the current keyword settings are saved, not the ones from the file opened

**Comment by codemanyak** [comment]
Have you checked that the import option "Replace keywords on loading a diagram (refactoring)" is enabled?

**Comment by GitMensch** [comment]
I'll check tomorrow - but even if it isn't it should still "understand" the ones that are stored in the file and not replace them on save if refactoring is not enabled.

**Comment by codemanyak** [comment]
Well, this is a different idea than the one I implemented. I had only thought that the user would like to adhere to his or her settings. So te world looks always consistent and you can port NSD fles to where you want the receiver will immediately recognise his/her keywords, no matter who wrote the diagram in what language.
Particularly on executing a hierarchy of dfferent subroutines it seemed to make sense not always to swap the set of keywords on subroutine calls etc.
On editing a new diagram you would have to use the keywords inadvertently set by the last loaded diagram etc. I'm not quite convinced that your idea is really better and more convenient.
Maybe sometime the user might be offered the choice between these both modes (and none of them).

**Comment by GitMensch** [comment]
I'd suggest the following:

* have the keywords in the diagram class, too, additional of the application wide setting
* for new diagram constructor: set the diagram attribute from the application wide setting
* settings: change the current refactoring checkbox to drop-down: always, ask (if not identical - default setting), no

This way all the ideas of your original thought is in but it is no problem to share NSD files.

**Comment by GitMensch** [comment]
For implementing this the NSD property dialogue must have keywords that are used for this specific NSD as options, too (this came up when writing #372 ).

**Comment by codemanyak** [comment]
Thank you for this remark. It shows that it wouldn't simplify but complicate all. I think we better leave it as is. Tt's of no use to create confusing multi-dimensional property configurations.

**Comment by GitMensch** [comment]
OK, in this case opening a NSD should do the following:

* check if keywords match with the global setting
* if yes: load
* if no: ask "Keywords differ, must be converted for opening the file - Do you want to continue?"
* No --> file not opened, Yes --> file opened and keywords replaced

Should I open a new ticket or is it OK to change the title of this one and reopen it?

**Comment by codemanyak** [comment]
Okay I'll consider it again.

**Comment by codemanyak** [comment]
Now there is a new implemented strategy for the keyword refactoring on the [development branch](https://github.com/codemanyak/Structorizer.Desktop/archive/master.zip):

- Full refactoring is now always the default setting (both on loading a file and on changing the Parser peferences).
- If the automatic refactoring is switched off and a diagram with differing keyword set is loaded (via the menu) then the following dialog box will pop up:
![refactoring_question_1](https://cloud.githubusercontent.com/assets/15326471/24431537/a9a66176-141c-11e7-9a50-49ead8b93ca7.png)
- The user may now choose among the three offered opportunities.
- If he/she opts for c), i.e. to postpone a measure, then the first attempt to change something at the diagram will pop up a slightly modified dialog:
![refactoring_question_2](https://cloud.githubusercontent.com/assets/15326471/24431579/fc32de06-141c-11e7-9010-6562420c4682.png)
- Now the postponed refactoring may eventually be done (such that the editing is based on a consistent content) or the keyword information may be abandoned in order to do all changes manually. Last but not least, the change may be cancelled and hence the solution of the problem postponed further.
- If "Save as..." is used for an (unchanged) diagram with postponed refactoring then the original keyword set will be saved. After a change the original keyword set will be lost in Structorizer.

I hope this strategy addresses the justified criticism and induces the necessary awareness of the users.

**Comment by GitMensch** [comment]
Marvelous! Can be closed when merged to upstream.

**Comment by GitMensch** [comment]
As other items that were coded for https://github.com/fesch/Structorizer.Desktop/milestone/2 are closed already this can be closed, too.
