### ISSUE TITLE
[FR]: Add File->Close

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#371]
The only way to get an "emtpy" Structorizer is currently to close and reopen the application again.

**Comment by codemanyak** [comment]
What about the "New" button? Or do I miss some decisive information what you actually intend?

**Comment by GitMensch** [comment]
New button works and opening a new file seems identical to the "open a new application instance". I have to check how the new button works in combination with the Arranger, but we can close this for now.

**Comment by codemanyak** [comment]
> New button works and opening a new file seems identical to the "open a new application instance".

It's definitely the light-weight version in comparison to the latter.

> I have to check how the new button works in combination with the Arranger, but we can close this for now.

There are three cases:

1. The former diagram was not on the Arranger. Then teher is no side-effect. The Arranger will stay open and all the diagrams placed there remain.
2. The former diagram was also placed on the Arranger and was not pinned. Then it will also be cleared. All other diagrams on he Arranger remain untouched.
3. The former diagram was "pinned" on the Arranger. Then it will stay there and can be got back to the Structorizer at any time by double-clicking on the index enzy or on the diagram itself because it still maintains ist association to the Structorizer instance though it is no longer updated from he new diagram.

If you double click a diagram in the Arranger, while its favourite Structorizer instance holds a "dirty" diagram then you will be asked to save its changes. If you do so it will simply be replaced by that from the Arranger. If you decline then a new Structorizer instance is opened for the Arranger-bound diagram such hat both diagrams can be edited independently.

**Comment by GitMensch** [comment]
@codemanyak 
Thank you for the notes on the Arranger.
