### ISSUE TITLE
[FR]: Add more attributes for NSD format

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#372]
The current version includes:

* Structorizer version used for saving the file
* keywords used in the file [currently ignored on open, destroyed on save, see #370]
* name - mixed with parameters
* comment
* color
* type (program/sub)
* style
 
Nice: as NSDs are saved in xml-format new attributes will just don't show up in old versions but don't hinder the open at all.

I want to suggest adding other (optional) fields:

* header (relevant if you want to import/export --> for example C includes, java imports, ...)
* footer (relevant if you want to import/export and have something out of the nsd)
* realname (first part of name field)
* parameters (everything within `()` from the current name attribute)
* author (a global program configuration would be nice for this, on the first creation pre-set with `System.getProperty("user.name")`)
* last change by
* license (can be relevant for samples) and when people generate sources for open source software

**Comment by codemanyak** [comment]
@GitMensch 
Thank you for your proposals. I see, we won't have difficulties to inflate NSD files to several MiB... :wink:.

> keywords used in the file [currently ignored on open, destroyed on save, see #370]

Well, again: This is a misconception. The keywords ARE used, but for the contrary strategy. This way, the used keywords are identifiable and may be replaced and adapted to the current user context automatically. The saving with a different keyword set is no problem because the diagram would automatically adapt itself to the original context again when loaded there - provided in both user contexts the input option "Replace keywords on loading..." is active. Semantically the diagram will not be changed at all, but every user sees it in his/her keyword context he/she is accustomed to. So you will always have a consistent set of diagrams e.g. for a presentation. No need to adapt anything because Structorizer does it for you.
With your proposal, evey diagram would look different - a mess in my eyes. Still I understand that some people might prefer it this way, and possibly there will be the requsted choice list among the strategies.

**Comment by GitMensch** [comment]
I'm reverting my proposal with the file specific keywords - but the refactoring should be enforced as the file gets useless otherwise on load+save (see #370).

Thank you for taking the attribute changes into your assignments.

**Comment by codemanyak** [comment]
@GitMensch to your attribute enhancement proposals:

> header (relevant if you want to import/export --> for example C includes, java imports, ...)

Well I guess, as this is also a diagram-specific issue, it should be an editable field in the Root editor. Problem is: it is dependent on both the content of the diagram and the target export language - this is a multidimensional problem! I'd prefer to derive the necessary standard headers from the used functions by the respective generators (for input / output, the FleAPI, and the Parallel section support, this has already been implemented. The  current language-specific, but diagram-independent entries configured in the export option dialog might be included. But should they override the global settings on loading. Rather not, I'd say. So there are we again with the n x m matrix (n diagrams x m taget languages). I'd say the user might mention the includs in the comments field and should be able to manually activate them after the export.

> footer (relevant if you want to import/export and have something out of the nsd)

For example?

> realname (first part of name field)

Would be redundant, Structorizer can automatically derive it. But not arbitrary XML raders, of course. So it's unstructured information. One could think about replacing the header text by the structured information and only re-compos the header automaticaly. On the other hand, I wouldn't like to lose the original header style, either.

> parameters (everything within () from the current name attribute)

Ditto. Well, with the FOR elements I actually did the same. But this was necessary to overcome the deficiencies of desperate attempts to get the loop parameters out of diffeent syntacic flavours in different modules of Structorizer (Executor, generators, parsers, editor, etc.). The dificulties to keep both the text and the isolated parameters consistent are still evident.
The procuedure header has way less kexwords and syntactic peculiarities. So I would leave it a s is.

> author (a global program configuration would be nice for this, on the first creation pre-set with System.getProperty("user.name"))

Well, why not.

> last change by

Fine with me.

> license (can be relevant for samples) and when people generate sources for open source software

In the latter case they should rather rely on the target IDE configuration. But well, there might be a "license preference" of Structorizer where you may add a standard license text, which might be copied on export (export option) or saving and it might stay a fix attribute of the Root element - unless it is explicitly overwritten. Of course you culd simply copy it to the Root comment, but a separate field will certainly be better.

**Comment by GitMensch** [comment]
header:
If the root editor gets a tab pane for the header (with each export language being a tab) then this works fine - you have the standard parser includes + standard user includes + program includes. I'd not override anything, just export them in this order with an appropriate comment where they come from.

footer:
I don't know if this would be done often for other languages but at least for COBOL you'd have includes (copybooks) in the program end often - but this can be achieved by an instruction, too - which leads to the idea to extend the "deactivate element for generation" to "deactivate element for generation in the following target languages :-).

realname / parameters: It looked like a better structuring to separate them in the xml as these are separate information - but it is OK to leave it as it is.
From the GUI perspective it wasn't obvious for me how to enter parameters, I just got the information (likely in the doc, too) from an error message that a sub needs parameters in parenthesis. Adding this information in the tooltip for the name field in the GUI would solve this, too.

Nice to see you accepting the others :-)

**Comment by GitMensch** [comment]
It is nice to have the author in the NSD as a first step, can we have a GUI element to change this?

**Comment by codemanyak** [comment]
You mean, on creating a new diagram the user could be presented the system-derived user name and get the opportunity to change it?
Or would you allow to change the author name at any time?

**Comment by codemanyak** [comment]
@GitMensch ... and what about the license field? Should it contain the full license text (as required by many licenses) or just the name and possibly a link?

**Comment by GitMensch** [comment]
@codemanyak 
> You mean, on creating a new diagram the user could be presented the system-derived user name and get the opportunity to change it?

No. Add the user name to the preferences, with the initial value being the system-derived user name (which may be "fesch" while the Author want it to be "Bob Fisch (fesch)".

> Or would you allow to change the author name at any time?

Not or, but *and* :-)

> and what about the license field? Should it contain the full license text (as required by many licenses) or just the name and possibly a link?

If you add a multi-line property it is up to the user to decide what he wants to enter there.

**Comment by codemanyak** [comment]
Well, now the prototype for the license management is on branch [codemanyak/Structorizer.Desktop/master](https://github.com/codemanyak/Structorizer.Desktop/archive/master.zip).

**Comment by codemanyak** [comment]
I should admit that there may be some overdone tricky mechanisms implemented. So the license editor invokable both from the "Save Options Dialog" and the Root editor behaves differently in each context.
From the Save Options you can add new license files (they will automatically be stored in the user-specific structorizer.ini directory with a naming schema lic+name+.txt) and edit the license text of the currently selected license (there is a combo box with the - sensibly abbreviated - names). Licenses may be cloned, renamed or deleted. The name left selected in the combo box of the Save Option Dialog will serve as default license for all new diagrams. The license text will be saved as root attribute in the NSD file.
From the Element editor for the diagram Root, however, you may only choose among the previously configured licenses and view them (the editing of the repository licenses is disabled in this mode). The locally stored copy of the license text, however, may be modified. Here the combobox in the editor offers a practically fix choice of the pool licences (with a "(pool)" appendix to their name for besser distinction) and the locally saved license name (without "pool"), which is associated to the locally saved copy of the license text. For an unsaved (new) Root, however, the license text may still be empty in the editor - because it will only be cloned on saving the file the first time.

The beasty mechanism with the author name is that you change it while it equals either the configured default author name or your current user name. In any other case the editing is disabled. So fater the author may have "hand over" his/her creation he/she will have some diffculties to change the name again. There are of course simple workarounds (e.g. the author name impersonation in the save option dialog). And we do not of course prevent the modification of the NSD file itself. No cryptography involved by now :wink:.

**Comment by GitMensch** [comment]
Just checked this - Very nice. It would be good to ship (some) pool licenses, at least gpl and the ones that are used for the samples - and then add the samples to the git repository (and ideal to the source tarball, too - I'm still trying to figure out how to create it and add something).

**Comment by codemanyak** [comment]
Well, to add such a license to the user's Structorizer environment is most utterly easy:
Go to `Preferences -> Saving ...` dialog, enter the name of a license, say "GPLv3", in the combo box, brwose to the Gnu GPL home page, copy the text (or just the URL), to the clipboard, press the "License file" button and paste the text or URL. save and close the Licence editor. Ready.
Would cost way more efforts to ship al that stuff with Structorizer and find an extra way to copy it to the user's ini directory (in particular, considering the assumption that most users won't use this feature, I assume.)

**Comment by codemanyak** [comment]
Btw: I would always prefer to fetch the license text from the original source, not from third party (which would be the Structorizer in this case).

**Comment by GitMensch** [comment]
OK, then just add the "How to add a license entry" to the manual and this one is fine.
If I see it correctly you declined the header/footer idea, we both declined the realname/parameter idea. Author and license are in.

The only things that are open with this ticket:
* maybe add the option to override the author as you've mentioned (removing the need to do this in the NSD file)
* maybe add the "last changed by" attribute

Do you think about implementing this? Should we close this issue already or maybe leave it open until it is merged to main repo?



The

**Comment by codemanyak** [comment]
@GitMensch 
>  maybe add the option to override the author as you've mentioned (removing the need to do this in the NSD file)

I thought I had explained that this is possible while the author name is among "your's". Otherwise impersonation in the "Saving" option dialog would help to change the value. This is a not really nifty but hey! if anyone can change the author attribute without any hurdle then what is it good for after all?

> maybe add the "last changed by" attribute

The attribute is in the fle ("changedby") and will automatically be set on every diagram modification. It's just not visible in the Root editor. Neither are the dates that are automaticaly tracked as well.
Will find a layout concept for it later, may be some pulldown menu, extra "attributes" button or the like.

**Comment by GitMensch** [comment]
I see. And yes, I agree that we don't need another author override mode (we can set them manually in the sample NSDs).
So all requested entries are already in, the issue is just open because if their presentation.

An extra menu option "File" -> "Attributes" or an "attributes" option when changing the root element is the proper way (I'd move the author license part there, too).

**Comment by GitMensch** [comment]
As far as I see this the only part missing is showing the "hidden" diagram attributes `created`, `changedby` and `changed`, maybe additional ``version`.

I suggest to have a new dialog "diagram properties" that can be opened from context menu on the diagram ("most outer element") and from menu diagram for showing these and from a button in the "Edit element" for the diagram.
If we move the input field "author" and the license to this dialog, too the "Edit element" dialog would likely be "cleaner".

After we have this done the issue can be closed.

What do you think of me doing this in a feature branch of my repo (moving all properties to this new dialog in the new file DiagramProperties.java)?

**Comment by codemanyak** [comment]
The work on an "AttributeInspector" is in progress.

**Comment by GitMensch** [comment]
ok, so I do nothing here but testing late

**Comment by codemanyak** [comment]
@GitMensch 
`AttributeInspector` class is ready now and integrated in the most recent commit. Open for late testing ...

**Comment by codemanyak** [comment]
Remark: I'm planning to compute software complexity measures for te diagrams and to add the results to the statistics group for a later version. I'll open a new issue for it when time is ripe.

**Comment by GitMensch** [comment]
@codemanyak 
Just tested - this looks really nice! *Maybe* add the version attribute, too.

Nonetheless this is fine, only needs a merge to the release version.

**Comment by codemanyak** [comment]
> Just tested - this looks really nice! *Maybe* add the version attribute, too.

What version info do you mean? You want an automatic change counter or a 
version string manually to be set?
Or do you refer to the Structorizer version of the file the diagram had 
been loaded from?

**Comment by GitMensch** [comment]
> What version info do you mean? You want an automatic change counter or a version string manually to be set?

Interesting idea but I don't think this matches an NSD well.

> Or do you refer to the Structorizer version of the file the diagram had been loaded from?

Yes. At least this is the only `version` attribute I've found in the NSD.

**Comment by codemanyak** [comment]
> Yes. At least this is the only version attribute I've found in the NSD.

Sure, but the title of this issue was to add more attributes... So what do I know?
Back to the subject. I'm not quite sure what benefit it might bring to show the Structorizer file version after loading was successful. It is not a diagram attribute at all but a file information for the case some inconsistency is to be reported or if certain XML schema details might differ. Ideally, the NSDParser should have addressed all that. It forgets it the moment the diagram is reconstructed. It's somehow ephemeral.
If it is yet of interest, then it might be equally or even more helpful to show the origin of the diagram in general: It might have been imported from C, Pascal, or COBOL (or Struktogrammeditor, PAP Designer etc.). This information might even be stored with diagram. But how long then, over how many change and save cycles? Should the next loading replace such an information or be appended to form a monotonically growing history?

**Comment by GitMensch** [comment]
You're right, the NSDParser should be the only one that needs the version info (ideally parsed with an xsd as discussed in #404).
And you're right about the "originating" document, this would be a "originated_from" attribute. It would be nice to have this as "removable" attribute (= it is in and you can click on "remove"). No need to specify the parser, better specify the file name. So something along "Structorizer 3.65", "Structorizer 3.65 COBOLParser yoursource.cob" / "Structorizer 3.65 yoursource.cob" "Structorizer 3.65 COBOLParser yoursource.cob" (add in how much you like, elements may be created different with newer versions, at least when the Parsers are taken into account).

**Comment by codemanyak** [comment]
@GitMensch 
Attribute "origin" added (and automatically filled as proposed).

**Comment by GitMensch** [comment]
+1 :-)

**Comment by codemanyak** [comment]
Fixed an attribute inconsistence when loading legacy diagrams (i.e. diagrams without or with rudimentary author attributes) from an arrz file - in this case the diagrams obtained the current date as "modified on" value which didn't make sense. This explains by the fact that the parsing is done from a temporary extracted file copy. Now (version 3.28-08), the file attributes of the arrz file will be inspected instead.
