### ISSUE TITLE
[FR]: add option for renaming variables

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#373]
This is especially useful when sources are imported and variables may be named x1, x2 etc instead of reasonable names.
Current workaround: save to NSD, open with text editor and replace the variable with search and destroy (at least if you don't use regex to "match whole word only" and "replace only within attribute values").

**Comment by codemanyak** [comment]
I would like to subsume this request under a more general enhancement request to provide a find/replace dialog: #415.

**Comment by codemanyak** [comment]
As an interims solution, the meanwhile implemented find/replace dialog (due with release 3.27) may be used to rename variables throughout a bunch of diagrams.

**Comment by GitMensch** [comment]
Closed as "wontfix" because of "in favor of #415", correct?

**Comment by codemanyak** [comment]
@GitMensch 
Right. I think, for a while the Find & Replace dialog with settings "Whole word" and "Case-sensitive" should aleviate the need for a separate variable renaming tool. In most cases you will even be able to avoid the inconvenience of "Replace/Next" since "Replace All" can do the job.
As soon as enough examples would be raised where the general Find & Replace tool is of no help we might easily reopen this issue. Okay?

**Comment by GitMensch** [comment]
@codemanyak I'm perfectly fine with "only" having search-and-destr... replace option. For tracking "it isn't solved directly" I'd add the wontfix label but the current status of the code is fine for me.
