### ISSUE TITLE
BUG: When exporting to python - charset should be set

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#378]
Hi,
when a nsd should be exported to python and the charset is set to utf-8 the second line have to be
`# -*- coding: utf-8 -*-`
[See:http://stackoverflow.com/questions/6289474/working-with-utf-8-encoding-in-python-source](http://stackoverflow.com/questions/6289474/working-with-utf-8-encoding-in-python-source)

Fine regards
Rolf

**Comment by GitMensch** [comment]
Hi @reks99, if you want to change this (until @fesch or @codemanyak fixes this) then

* open project from git checkout
* go to https://github.com/fesch/Structorizer.Desktop/blob/master/src/lu/fisch/structorizer/generators/PythonGenerator.java#L766 and change it (I assume the surrounding spaces are needed, otherwise comment the line)
```patch
+ 	Ini ini = Ini.getInstance();
+ 	ini.load();
 	code.add(_indent + "#!/usr/bin/env python");
+ 	code.add(_indent + "# -*- coding: " + ini.getProperty("genExportCharset", Charset.defaultCharset().name()) + "-*-");
```
* start with `Structorizer` class

@fesch Would it be a good idea to add a `getEncoding()` function to the `lu.fisch.structorizer.generators.Generator`?

**Comment by codemanyak** [comment]
No problem.

**Comment by GitMensch** [comment]
@codemanyak Is the approach from me the correct way?

**Comment by codemanyak** [comment]
@GitMensch 
Sure.
