### ISSUE TITLE
BUG: Python export: not equal is wrong

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#379]
Hi,
when a nsd is exported to Python a `!=` expression is converted to `<>`, which is not recogniced by the python (2.x) interpreter. An export as `!=` should be used.

Fine regards
Rolf

**Comment by GitMensch** [comment]
Hi @reks99, if you want to change this (until @fesch or @codemanyak fixes this) then

* open project from git checkout
* go to https://github.com/fesch/Structorizer.Desktop/blob/master/src/lu/fisch/structorizer/generators/PythonGenerator.java#L244 and change it (I assume the surrounding spaces are needed, otherwise comment the line)
```patch
-	tokens.replaceAll("!="," <> ");
+	tokens.replaceAll("!="," != ");
```
* start with `Structorizer` class

**Comment by codemanyak** [comment]
@reks99 
You are right. It will be fixed as soon as possible.

**Comment by codemanyak** [comment]
Fix is avialable on the bugfix branch and will be delivered with the next version.
