### ISSUE TITLE
[FR]: GUI-Option to move selected elements to a sub-nsd

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#380]
As discussed in #377 bigger code parts should be placed into subs as this helps to reduce the complexity of a single NSD and allows to re-use them.

#377 shows a way how to do this with the help of Arranger but is is still manual work, if you add used variables to this it will be more work on both the source and the target NSD.

This FR is about:

* new GUI option "move elements to sub"
* inspect the used variables in the elements --> place in a list
* inspect the other elements of the NSD for the variables in the list, if they don't occur --> remove from list
* open the "add a new call" window and pre-fill the variables from the list
* abort on "Cancel", otherwise go on
* cut the selected elements
* add the CALL instruction, store the name and parameters
* add current file to Arranger (if not in already) and open it if it is closed
* create/open new NSD as sub with the stored name and parameters
* add new NSD to Arranger
* insert the elements that were cut before

**Comment by codemanyak** [comment]
This is a really great enhancement idea!

**Comment by codemanyak** [comment]
There is a first prototype (with still somewhat incomplete heuristics for argument / result detection) for [download](https://github.com/codemanyak/Structorizer.Desktop/archive/master.zip).

**Comment by GitMensch** [comment]
One thing I've recognized:

* open Structorizer (no file open, nothing in the arranger)
* open file (still nothing in the arranger)
* outsource something (works like a charm and the new file is unsaved in the arranger)

Problem: the original file wasn't added in the arranger which is likely a good idea :-)

**Comment by GitMensch** [comment]
Tested with Messwert5.nsd:

* open file
* marked "varianz <- 0.0" (comment STANDARDABWEICHUNGSBERECHNUNG) until end
* clicked "outsource" and used "Standardabweichungsberechnung" as name
* in the original file we have the call to `Standardabweichungsberechnung(messwert; mittelwert; anzahl)` while in the sub-file we have `Standardabweichungsberechnung(messwert; mittelwert: ???; anzahl)` - what are these `???` and are they intended?

**Comment by codemanyak** [comment]
Well, obviously the type identification mechanism got into a dubious situation: On the one hand it seems to have found some type hint for argument `mittelwert` but then it wasn't unambiguous (there may have been contradicting type findings) such that the type description was replaced by "???". I will have a look at this example in order to find out whether this behaviour can be mended.

**Comment by codemanyak** [comment]
@GitMensch 
> Problem: the original file wasn't added in the arranger which is likely a good idea :-)

This leaves me somewhat puzzled: Is it a problem or a good idea? Or do you mean it would be a good idea automaticaly to put the base file to Arranger, too? I didn't see a reason for it. The user may do this any time. Since both diagrams are left in changed state, you would be asked to save it as soon as you select another one, anyway. So there is little risk to lose the changes inadvertently or unnoticed.

W.r.t. the argument type detection: The expression analysis is still incomplete since I haven't changed it to a grammar-control parser. By means of a mere lexic scanning and some isolated methods with very limited parsing capabilities the type information of operator-combined expressions is too vague to find out that `mittelwert` must be a variable of type double.
I'm planning to write a very tolerant grammar for Structorizer expressions in order to be able to decide the type of expressions, given the type of their operands. Unfortunately, the more tolerant the grammar is (or is to be) the more difficult conflicts you will obtain. So it's open whether I may use the GLODParser for instruction analysis.

**Comment by GitMensch** [comment]
Yes, if the sub is put in the Arranger I'd like to have the base file in the Arranger, too.
I've double clicked on the sub file in the arranger (was prompted to save the changed base one) and the sub was opened - but there wasn't the same way back to the base one.

Concerning the argument type detection: If the NSD is "run" / debugged Structorizer "knows" of a type for arguments - couldn't the same logic be used for the "Outsource" feature? Why should Structorizer parse the NSD different in two places?

**Comment by codemanyak** [comment]
> Yes, if the sub is put in the Arranger I'd like to have the base file in the Arranger, too.
I've double clicked on the sub file in the arranger (was prompted to save the changed base one) and the sub was opened - but there wasn't the same way back to the base one.

You could simply have loaded it again from the recently opened diagrams. If you want to avoid the overriding of the current diagram you might shut the save prompter ("X" button), then the double-clicked diagram would be put into an additional Structorizer instance, so both are available, too. The only irreversible loss occurs if you press "No" in the save prompter.

> Concerning the argument type detection: If the NSD is "run" / debugged Structorizer "knows" of a type for arguments - couldn't the same logic be used for the "Outsource" feature? Why should Structorizer parse the NSD different in two places?

Because the run-time values (and hence types) are only available during execution i.e. they require the diagram having been executed before. And they depend on the way the algorithm takes (a variable may be assigned a value of a totally different type at any time.
When you outsouce code, a static analysis is required. So you must look for declarations of variables (but these are optional), otherwise you may have a look for the last assigment before and analyse the expression in the hope it gives you the decisive information. By now only three kinds of expressions provide unambiguous type information: a) literals, b) variables with already analysed type (declaration), c) built-in functions the rsult type of which is known. To be able to tell the result type of other kinds of expressions requires a syntax tree of the expression (operator precedence, parenthesis nesting and all that stuff). You don't have the values but must derive the infor over the structure of the expressions and the type information of heir operands. It's completely different from the incremental interpreter knowledge 
during debugging.
Structorizer has already learned to gather static type information when identifying used variables and constants (i.e. I taught it Structorizer) but this information is incomplete and may be ambiguous.
An example - at different places in the algorithm there might be the following assignments: 
```
myVar <- 0
myVar <- sqrt(myVar)
```
So the first assignment suggests int type, the second double type. Formally different types. An input instruction doesn't give you any clue (on execution, in contrast, the entered value is obvious, but not predictable either). So even with improved syntax analysis, we will never have a 100 % reliable type information.
In the Messwertstatistik5.nsd diagram, you might find out that `messwert` is an array variable, but the values are set by an input instruction. Now you could see that they are added to a double variable, such that you might deduce that they may be meant to be double values as well. But you see how many sophisticated deduction and vague guesswork there is in (requiring expression structure analysis).

**Comment by codemanyak** [comment]
I will of course fix the nonsense expression of "???" in case there isn't enough type information.

**Comment by codemanyak** [comment]
Implementation improved.

**Comment by codemanyak** [comment]
In case the selected element sequence contains JUMP elements targeting outside the sequence (return and leave jumps in particular), the user should be presented a confirmation dialog vividly warning off outsourcing the code because it would compromise the program logic (a return would now only leave the new subroutine though it previously returned from the parent routine, a leave instructionmight lose its matching loop context if this remains in the parent routine).
If the user insists, however, then we shouldn't prevent the conversion though, maybe the user has an idea how to mend it afterwards.

**Comment by codemanyak** [comment]
Warning mechanism implemented (branch codemanyak/Structorizer.Desktop/master).
