### ISSUE TITLE
python header in version 3.25-05 (handling of argument defaults)

### ISSUE THREAD

**Issue by usernameisthis** [fesch/Structorizer.Desktop#385]
Changes the listing in the method definition when exported, for example:

def __init__(self, 
                INSTANCE_NAME = "", 
                TIMESOURCE = None,
                SUPPRESS_PUBLISH = True,
                MAGNITUDE = 0,
                VALIDITY = False,
                KNOWN = False,
                TIMESTAMP = 0,
                RANGE = [0,1], 
                NUMBER_OF_SETS = 0,
                BAD_HIT_LIMIT = 1,
                RANGE_ERROR = False,
                NUMBER_BAD_HITS = 0,
                SUBSCRIBER_VARIABLE = [],
                SUBSCRIBER_ALERTABLES = [])

becomes:

def __init__(self, "", None, True, 0, False, False, 0, [0, 1], 0, 1, False, 0, [], [])

**Comment by codemanyak** [comment]
Please be aware that Structorizer cannot support any non-agorithmic peculiarity of any programming language. Structorizer syntax analysis in the program header has never expected the occurrance of default values. Indeed it has already to cope with three and a half different argument syntax paradigms: Pascal, VB, C/Java.
We will ponder how much effort it'll make to enable default settings according to C++ or Python syntax.
A problem is, however, that many export target languages (like Pascal, C, Java) won't cope with default values in function definitions. So what should happen on export then? Practically the default values could only be ignored then.

**Comment by codemanyak** [comment]
@usernameisthis Some additional comments:

- To accept default values for parameters would have heavy implications for the Executor: Instead of a single signature, actually a bunch of signatures would be declared, which would require a way more complex subroutine identification mechanism (possibly including argument type analysis). By now only name and (fix) argument number are significant.
- By the way, you could have seen from the Analyser warnings in the report area that the parsing of the function head fails to interpret your signature specification in the intended way. Well, it seems sensible at least to do a more specific scanning for equality operators in the argument list.
- Though it's irrelevant here and just for the record: The most recent version is 3.***26***-05. Did you refer to this version?

**Comment by codemanyak** [comment]
Provided the usual convention that argument defaults must be contiguous from end, it seems feasible to add default argument support with the following implications (this is the plan):
# Syntax analysis
Equality signs are okay as indicators for defaults in parameter lists, while we don't allow arbitrary expressions but literals as default arguments. This way, they can't be mistaken for comparison operators.
The Root elements of subroutine type will have to provide a method returning the list of default literals (in addition to the list of parameter names and the list of parameter types).
The signature strings of routines with default arguments are to express an arity range, e.g. "foo(3-7)".
Because typing of variables and parameters isn't mandatory in Structorizer, there won't type distinction for routines with matching or overlapping arity.
# Analyser
There ought to be a check for default contiguousness from end.
A signature ambiguousness check among available routines might also be added.
# Executor
## Call execution
The retrieval of subroutine Roots with matching signature will have to the following precedence strategy to resolve possible conflicts:
  1. Routine with a singular arity exactly equal to the argument number of the call (fast);
  2. Among the routines with an arity range containing the call argument number prefer that routine with smallest upper bound (slow).
  3. If there are still several candidates prefer that one sharing most groups with the caller's Root.

When a routine with arity range is chosen than use the respective default arguments for the missing arguments, obviously.
## Top-level execution
On executing a routine diagram with default arguments at top level, preset the input dialog text field with the respective default literal.
# Code export
The code generators must classify their target languages into the three following categories:
1. supporting default arguments (e.g. C++, Python);
2. supporting at least signature overloading (e.g. Java);
3. not supporting overloading (C, shell).

Code generation for category 1 is straightforward.
Code generation for category 2 should be the production of delegate routines.
Code generation for category 3 must expand the call with the required default arguments of the available subroutine with closest matching arity range (cf Call execution).

**Comment by codemanyak** [comment]
With code export, a difficulty arizes with overloading levels 1 und 2: In batch mode, Arranger isn't available as routine pool, so there is no argument inference for the called routines.
