### ISSUE TITLE
Case struct element crashes on ArithmeticException: / by zero

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#39]
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
	at lu.fisch.structorizer.elements.Case.draw(Case.java:416)

Place at first element a case struct with default values, cause this exception.

**Comment by codemanyak** [comment]
This is a bug, indeed. In one place the draw method divides something by the line number. Usually, the text of a Case element isn't empty, of course. The structural preferences aren't usually empty, either.
Many thanks for the report, anyway. Of course it will be fixed with the next version.  A simple workaround (and sensible setting) would hence be to put something into the default.texts for the Case structure.

**Comment by elemhsb** [comment]
Yes you are Right, it happens when show comments is activate.

**Comment by codemanyak** [comment]
Oops! The text setting and getting in "exchanged text/comment" mode turns out to be heavily inconsistent. Will need a more thorough clarification how this mode is meant to operate. At first glance one might guess ANY access to text and comment must be swapped. But obviously this doesn't make sense for Call and Parallel elements, at least. Should it only to apply to instructions (like the similar export option?). Does it make sense for loops?

At the moment, however, the methods setText() / getText() / setComment() / getComment() handle this very differently, even depending on the argument type! Additionally, it somehow interferes with the mentioned code export option, which independently swaps again. Ok, we'll sort it out somehow.

**Comment by codemanyak** [comment]
My severe recommendation for now is: Make sure you NEVER edit in swapped text/comment mode!
I think the best will be to disable editing in this mode! It might be fine for presentation but turns out to be strongly confusing.

**Comment by fesch** [comment]
I agree on this: editing should only be enabled / possible when "show comments" is _not_ active.

**Comment by elemhsb** [comment]
I think, "show comments" or "not" should only be a different view to the user, switching and editing should always be possible, for prototyping and learning. A perfect enhancement would be to place the cursor into the right "code" or "comment" field when editing. ;-)

Export works always ok, Executer has a problem with "show comments", it 
should run always the "code" part even it's "comments" are displayed.

Thanks for makeing structorizer, it's a outstanding tool. :-)

**Comment by codemanyak** [comment]
Then the bugfix I just finished will please you:
Editor, executor, and generators will work as usual without ANY change compared to the normal mode, just the drawn diagrams will show the comments instead of the texts, whereas the comment bars and popups then mark or show the true contents, instead. I.e. in the editor, the true text will ALWAYS be presented in in the upper text field, the comment field will ALWAYS be the lower one. Nothing will be mixed up, this way.
Additionally, it will nevermore be possible to empty the Case text, i.e. if the user has emptied it, the number of lines will automically be enlarged to the minimum number of 3 (i.e. selection expression and two branches, though they will just contain question marks).
By the way, you owe most of the thanks to Bob Fisch, being the inventor of Structorizer. I'm just enhancing and improving it.

**Comment by elemhsb** [comment]
I tested bugfix3.22 git branch from fesch. Good job :-). 
btw. for editing i mean to place only the cursor FOCUS into the right code or comment section.
Is there a ant build command to make a release? I have copied Structorizer.jar into old hierarchy but got ClassNotFound error.

**Comment by codemanyak** [comment]
Bob has got a release script. I use to compile with Eclipse, and my jar files expect the referred libraries in a different folder, too.
If you can wait a little until the remaining open bugs be fixed then Bob will publish release 3.23.

**Comment by elemhsb** [comment]
No time to wait, this bugfix release runs today in the evening with 30 students ;-).
I get ist work, I fixed the distributed Stuctorizer.sh:
java -cp $(find $(dirname $0) -name \*.jar -print0 | xargs -0 echo | sed 's/ /:/g;') Structorizer "$@" &

**Comment by fesch** [comment]
Wow ;-)

**Comment by elemhsb** [comment]
bugfix3.22 run perfect this evening laboratory session. :+1:

**Comment by codemanyak** [comment]
Glad to read this. Unfortunately there is still some problem with Element selection when the Arranger happens to hold a root being currently updated by Structorizer: The mouse gets confused among the cached drawing rectangles. This is because in the Arranger the diagram is always shown in normal mode. So the diagran is always drawn twice: first in the Structorizer (in swapped mode), then in the Artanger (in normal mode) such that on attempting to select the elements still remember their normal mode extensions.
I bumped into this while I tried to set the editor input focus according to your suggestion.

**Comment by codemanyak** [comment]
Okay, Arranger now fully reflects the switched text/comment mode. In a way, this is sound (Element.E_TOGGLETC is a static field) and it avoids remnants of different drawing content without dramatically degrading reaction time by exorbitant redrawing (it really happens frequently enough).

**Comment by codemanyak** [comment]
Addendum: I didn't manage to control the focus in the InputBox. Maybe the Layout interferes. Both methods requestFocusInWindow() and requestFocus(boolean) constantly returned false and don't show any effect.
I think we can live without thos focus thing.

**Comment by codemanyak** [comment]
Solution for the proposed focus control found and prepared for next version (3.24-13).

**Comment by elemhsb** [comment]
Good job, works fine now! @codemanyak
