### ISSUE TITLE
Question about NSD export to BASH

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#396]
Hi,
I have two questions with the following NSD where I call the linux programs with a subroutine call.  

![rename1](https://cloud.githubusercontent.com/assets/18035140/25741146/c3e844ac-3189-11e7-8ea0-6350586ae0c8.png)
1. Why are the program calls surrounded with back ticks instead of $( )?
2. Why is a list of arguments completely surround by quotes and a single argument not?

Find attached the nsd - renamed as *.txt to be acceped by GitHub

[rename1.txt](https://github.com/fesch/Structorizer.Desktop/files/978659/rename1.txt)
Fine regards
Rolf

**Comment by GitMensch** [comment]
I suggest to edit the title to "Question about NSD export to BASH"

**Comment by reks99** [comment]
Hi,
as a third question I would like to know, why the first statement (LISTE :=...) is surrounded by two pairs of parantheses even it is the same construct as the other two function calls.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Just to answer this:

> 1. Why are the program calls surrounded with back ticks instead of $( )?

Just old-style command execution as expression, rather dysfunctional. No problem at all with replacing this by `$( ... )`.

> 2. Why is a list of arguments completely surround by quotes and a single argument not?

Simply due to a very simple heuristic assumption that the Structorizer element content is more or less HLL, such that the occurrance of operator symbols like '-' or '*' are interpreted as indication of an arithmetic expression. Maybe, I just forgot to disable this heuristics in "no translation" mode.

> 3.  why the first statement (LISTE :=...) is surrounded by two pairs of parantheses even it is the same construct as the other two function calls.

As told before, they are __not__ exactly the same construct - the other two calls don't contain operator symbols... I just made sure that this conversion does __not__ take place if mode "no conversion of the expression/instruction contents" is enabled.

So excuse me: If you write hybrid code that partially adheres to Structorizer syntax conventions and partially not and let Structorizer convert it - what do you expect, actually?

**Comment by codemanyak** [comment]
Will fix item 1 of this issue for the next release.

**Comment by reks99** [comment]
Hi,

It's still unclear, what mathmatical operation structurizer  find in the call "DATEI := basename (A .JPG)" and why the parameters are sourrounded by quotes - or need the parameters separated by colons.

About the third question: Why is the complete comand and not only the parameters - which may need evaluation - are sourrounde by two pairs of parentheses?

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> It's still unclear, what mathematical operation structorizer find in the call "DATEI := basename (A .JPG)" and why the parameters are sourrounded by quotes - or need the parameters separated by colons.

An expression `basename(A .JPG)` is syntactically illegal in an HLL (unless it means a component `JPG` of a struct variable `A`, but structs/records haven't been supported by Structorizer). If a function `basename` existed as subroutine then it would have to accept a string argument (either a literal or a string variable or some string expression) and the call would have to look like:
`DATEI := basename("A.JPG")`
(Structorizer has a raw input scanning mechanism used for input instructions where all that cannot be interpreted as numbers or array initializers is regarded as string and therefore enclosed with quotes. I'm not quite aware why it should get active on translation a subroutine call at the moment, though.)

> About the third question: Why is the complete command and not only the parameters - which may need evaluation - are sourrounded by two pairs of parentheses?

Simple because no detailed syntax analysis is being done. This may be changed with a later release, perhaps. Then it might get possible to have a better guess how to convert expressions in a more meaningful way.

**Comment by reks99** [comment]
Hi,

> An expression basename(A .JPG) is syntactically illegal in an HLL (unless it means a component JPG of a struct variable A, but structs/records haven't been supported by Structorizer).

1. There is a space between A and the dot, so JPG is not part of a structure. 
2. Quoting the string ".JPG" and make it a different argument, didn't prevent structurizer for sourround the expression with (another) pair of parentheses.
3. Parameters passed to subroutines may also consits of numbers or strings. So the numbers may not have been quoted
4. A call to a external program in BASH is simular to a function call in a programming language. 
5. Until there is no clear definition for the HLL you use, I cannot follow their rules.
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> 1. There is a space between A and the dot, so JPG is not part of a structure.

The space doesn't make it a different argument. Argument separator is a comma. There is no toke consisting of a dot and letters (`.JPG` is no valid expression, `A.JPG` might have been but is not what you intended). Depending on the specific HLL, spaces between a function name and the opening parenthesis or between an array name and the index bracket or between a struct idenifier and the dot operator might be tlerated by the respective parser. Java and C allow synonymously to write `data . comp` instead of `data.comp`, though it's not recommended to put spaces there.

> 2. Quoting the string ".JPG" to make it a different argument, didn't prevent structorizer for sourround the expression with (another) pair of parentheses.

Of course not, because `A ".JPG"` isn't a valid argument nor a valid argument list, either. Depending on what you want, you might have written `basename("A", ".JPG")` (two arguments) or `basename("A.JPG")` (one argument).

> 3. Parameters passed to subroutines may also consist of numbers or strings. So the numbers may not have been quoted.

A number literal is a number literal, a string literal is a string literal and a dubious bunch of characters not matching any literal syntax might perhaps graciously be handled as if it should mean a string literal. If you don't honour tolerance here, I would agree.

> 4. A call to an external program in BASH is similar to a function call in a programming language.

Sure, but syntax differs.

> 5. Until there is no clear definition for the HLL you use, I cannot follow their rules. So it lookes like you reference the HLL as you like.

This is a somewhat simplified point of view. But again: In HLL there are some data types. And among the valid tokens there are literals (the syntax of which associates it with one of the types) and identifiers (which use to be declared or may be categorizied by their current value). Expression lists are separated by separators, usually commas. Thes are some of the common rules HLLs adhere to. Structorizer is VERY tlerant but that doesn't mean you can write whatever you want if you expect Structorizer to make sense of it on execution or export.

**Comment by reks99** [comment]
Hi,
Please give a refence for the used HLL.

**Comment by codemanyak** [comment]
Okay, let's go back to the basics.
There is no exact grammar, but some common-sense concepts rules regarding [expressions](http://help.structorizer.fisch.lu/index.php?menu=94&page=#supported_syntactic_elements).
Roughly in bottom-up manner:
A sequence of digits possibly preceded by a sign is an _integer_ __literal__: `(+|-)?[0-9]+`
An integer literal followed by an 'L' character is a _long_ __literal__.
A sequence of digits with a decimal point or an exponential postfix is a floating-point __literal__: `(+|-)?[0-9]+.[0-9]+((E|e)(+|-)?[0-9])?` (one variant).
A single character in apostrophes is regared as _character_ __literal__.
Other character sequences enclosed in quotes or apostrophes are _string_ __literals__ (if it's not a character literal).
Literals are __expressions__.
A sequence of letters, digits and underscores, not beginning with a digit, is an __identifier__: `[A-Za-z_][A-Za-z0-9_]*`.
Identifiers are valid expressions if they refer to a defined variable or constant.
An identifier followed by a comma-separated list of expressions in parentheses is a __function__ or __procedure__ reference (call). Functions return a value, procedures don't. You find a list of provided built-in functions and procedures in the [user guide](http://help.structorizer.fisch.lu/index.php?menu=94&page=#supported_syntactic_elements).
Function references are expressions, procedure references are not.
Expressions joined by suited __operator symbols__ are __expressions___. You find a table of accepted operator symbols in the Structorizer [user guide](http://help.structorizer.fisch.lu/index.php?menu=94&page=#supported_syntactic_elements).
An expression enclosed in parentheses is an __expression__.
An identifier followed by an integer expression in brackets is an array element reference and as such an __expression__ (if the array is defined).
There are no other expressions.
The type of an expression is derived from the used operators and operand expressions and functions. A boolean expression may be constructed with comparison operators or consist of operands with boolean value etc. On execution, the syntax is context-sensitive i.e. the actual variable and constant types decide whether the expression is well-formed and can be evaluated. But then its result type is unambiguous.

A procedure reference is a __statement__ (instruction).
Further statements are: input statement, output statement and assignment (see [Instruction](http://help.structorizer.fisch.lu/index.php?menu=50) in the user guide).
Return, leave, and exit statements are [Jump](http://help.structorizer.fisch.lu/index.php?menu=58&page=) __statements__,
Any composed statement is represented by a structogram element and doesn't need a syntax explanation therefore, with the exception of [FOR loops](http://help.structorizer.fisch.lu/index.php?menu=53).

Any more questions? Do you know now why `find(/home -name \*.JPG)` is not a valid expression in Structorizer or usual HLLs?

**Comment by reks99** [comment]
Hi,
now it is much more clear, how to construct valid expressions in structorizer. I will test it and see, what code will be generated.
Thank you very much.
Rolf

**Comment by codemanyak** [comment]
@reks99 
You should be aware, of course, that it might be impossible to formulate a valid expression in Structorizer that achieves a specific desired shell command on export. For example `find("/home -name *.JPG")` would be a valid expression in Structorizer but the export result will not only suffer from the quotes not vanishing, but also from the poor heuristics to guess an arithmetic expression (slash, minus symbol, and asterisk still trigger a wrong $(( )) encapsulation in version 3.26-05): `find $(( "/home -name *.JPG" ))`.
But I promise to improve the syntax analysis for release 3.27 (at least ignoring operator symbols within string literals). The crux is, however, that quotes - in HLLs delimiting string literals, the contents of which should practially be sacrosanct for the parser, - have a quite different meaning in shell syntax, where they simply control the _degree_ of substitutions and expansions. Never ever would an HLL compiler try to evaluate a substring being equal to variable identifier inside a string literal.
Structorizer rather tries to convert HLL-typical algorithms in something more or less equivalent in shell syntax. Since there is no equivalent to the `find` command among the built-in functions or procedures nor to a wild-card pattern like "*", a correct shell find command can hardly be achieved by converting valid HLL expressions.
HLL and shell are simply different worlds, both in the subjects they are chiefly concerning (HLL: numbers, strings, data structures, objects etc.; shell: files, search patterns, and commands) and in syntax.
So it would certainly be possible to define and implement built-in functions and procedures for some frequently used tasks in shell scripts (like the search for files), the calls of which might then be converted into something short, neat, correct and equivalent in shell scripts; but then there would be the trouble how to export this to HLL export languages that do not dispose of such functions in their language standard - we may not rely on the availbility of some non-standard third-party libraries.
Somehow it's a mission impossible. We'll try the possible, though.

**Comment by reks99** [comment]
Hi,
I know that a NSD is not for real program coding. And my idea is, to _test_ how I can formulate program structures in Structorizer which export to bash as good as possible, before to switch to the nativ export option. The test should end in a tutorial for bash programing, so I have no (real) need for the simulation capabilities of Structurizer - perhaps later.
So that was the reason to open this "question" issue.
Fine regards.
Rolf

**Comment by reks99** [comment]
Hello,

what about the idea to add the description of the HLL to the documentation? For example as "Summary of the HLL used in Structorizer" in the appendix.

I made a libreOffice dokument from the entry and can give it away if needed.
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> what about the idea to add the description of the HLL to the documentation? For example as "Summary of the HLL used in Structorizer" in the appendix.
D'accor! I had already decided this after having answered your question.
