### ISSUE TITLE
Parsers: What do you think about changing the parser constants from private interface to enum?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#402]
I suggest to change it from something like

```java
	@SuppressWarnings("unused")
	private interface RuleConstants
	{
##RULES
		final int %ID.Padded% = %Value.Padded%;  // %Description%
##END-RULES
```

to

```java
	private enum RuleConstants
	{
##RULES
		%ID.Padded%(%Value.Padded%, "%ID.Padded%", "%Description%"),
##END-RULES
		ENUM_END(-1, "", "");
```

This way we can directly use the ID.Padded and Description in the source (for logging) and there are no unused `final int` any more.

Just asking (I'm still quite new to Java and don't know if it has a bad effect on the performance) - if the answer is "yes", then I'd change the StructorizerParserTemplate.pgt, generate a COBOLParser.skell.java and update COBOLParser.java with merge + fix errors, Maybe the same with the CParser.
Any hints and/or opinions?

**Comment by codemanyak** [comment]
Of course the performance wouldn't be improved by this approach. A "final" declaration avoids entries in the virtual address table and reduces late binding. And of course we need only a small subset of all the RuleConstants. To equip all of them with "heavily" loaded enumerator entries is certainly not the best of all ideas.
If we want to save overhead we could even drop all unused constants from the interface after the parser development is nearly accomplished. The current System.out writings are not meant to be there for the eternity. They are rather a quick hack for the development phase. I will decide later, which of them to make durable log entries and which to comment out.
Of course, the enumerator approach would also allow to delete many unused entries but this something that should not happen before the respective parser is utterly stable.
(Of course the entries can reproduced at any time by deriving the tables with the templates again.)

**Comment by GitMensch** [comment]
Yes, dropping or better commenting the unused entries after finishing the base work is a good idea in any case. If you don't think the performance drop is too significant (I personally *guess* it isn't) - or dislike the idea because of other reasons - I'd change the parser template and the COBOLParser to use two `enum`s and `switch`. What do you think about this?

**Comment by codemanyak** [comment]
So go ahead if you like, for Christ's sake.

**Comment by codemanyak** [comment]
@GitMensch 
Despite of my "go" yesterday, I'm still not quite happy.
What you should have in mind:
- The private interface with final constants is the leaner approach. It's several thousands of strings you are going to put into data structures - most of them won't ever be used.
- If you insist, then please first pull my most recent commits before you start your redesign.
- Be aware that - depending on the structure of the grammar - in some cases it's more convenient to select by the rule head instead of by rule id (e.g. D7Parser, hybrid: CParser). Of course this could still be done in the default branch of the intended switch.

**Comment by codemanyak** [comment]
@GitMensch 
Having pondered the fact that the rule description (which is anyway more verbose for the potential log than the id name) is available in the parent production object of the respective reduction, I'd say: Your intended conversion to enum doesn't make any sense.

**Comment by GitMensch** [comment]
OK, thank you for the response. Looks like a wontfix label then ;-)
Can you please change the logging in the COBOLParser allowing me to easily see what you meant? Thanks.

**Comment by codemanyak** [comment]
@GitMensch 
> Can you please change the logging in the COBOLParser allowing me to easily see what you meant? Thanks.
You can see it in CParser.buildNSD_R(...), just over the first selecting if statement: `logFile.write("buildNSD_R(" + rule + ", " + _parentNode.parent + ")...\n");`. The variable `rule` contains the grammar rule as string and is derived from `reduction.getParent().toString()`.
During development, however, it was more instructive for me to see the id label on the console output. In the release these writes will have gone.

**Comment by codemanyak** [comment]
@GitMensch 
Addition: To be helpful during debugging, the logging mechanism will have to be rewritten such that the log file is reopened and closed on every logging event, otherwise the log file will just be missing in case of an error.

**Comment by codemanyak** [comment]
I modified the logging mechanism, but in a slightly different way:
1. A new method `void log(String, boolean)` on class CodeParser now facilitates the writing of text to the log stream. Explicit access to field `logFile` is no longer necessary and therefore no longer possible.
2. Instead of closing and reopening the log stream each time, an exception handling now ensures that the log file is closed on any otherwise unhandled exceptions like severe errors e.g. NullPointerExceptions etc.
