### ISSUE TITLE
CASE instruction: add option to change the drawing style

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#405]
While the current drawing is nice as it is according to DIN 66261:

![grafik](https://cloud.githubusercontent.com/assets/6699539/26098653/c027ca0c-3a28-11e7-8b23-5bdbef3deda0.png) 

Imported from [worldcities/checkfilestatus.cpy][1]

it leads to *very* wide NSDs that are in fact not usable (the capture above is from two extended monitors and it still doesn't show the CASE statement completely).
I suggest to add an option that changes the drawing style to something like this:

![grafik](https://cloud.githubusercontent.com/assets/6699539/26101628/1f44dd00-3a32-11e7-8242-a6fd9bbd7738.png)

This would make the NSD much more easy to read (actually even to view).

[1]:https://sourceforge.net/p/open-cobol/contrib/HEAD/tree/trunk/samples/worldcities/checkfilestatus.cpy

**Comment by codemanyak** [comment]
Is this style your invention? I haven't found anything like that in the DIN.

My proposal would rather be to reactivate some dead code approach to rotate the case selector texts by 90 degrees to the left either
a) if the accumulated widh exceeds a certain (configurable) limit or
b) in general if a new structure preference requires that.

**Comment by GitMensch** [comment]
Yes, this was my "invention". I dedicate that to the public domain :-)

I've seen a rotate flag in the nsd, I'd say lets reactivate the code and see what the result looks like. A configurable limit (which may be set to 1 = always) sounds like a good idea.

**Comment by codemanyak** [comment]
Well, I just realised that the rotation proposal wouldn't really help a lot. In the example it's not actually the selector texts that spread the Case element but the instruction texts of the branches. But there rotation doesn't make much sense if the branches don't just accidently consist of a single instruction line each.
It might be checked, however, if the width of the drawn Subqueues significantly exceeds their height. In this case they might be rotated perhaps. But that will cause new trouble on navigating through and editing such a rotated diagram part. So it might be best to limit this option to single-line instruction branches.

**Comment by GitMensch** [comment]
> So it might be best to limit this option to single-line instruction branches.

In this case I wouldn't put effort in the rotated version but put the work in the "invented" variant above as this allows many instructions in many branches with multiple nesting perfectly.

**Comment by codemanyak** [comment]
I started yet with the rotation aproach and it doesn't look so bad. All branches that consist of a single instruction element or a collapsed element are rotated if the branch number exceeds the configured threshold. For the example from [worldcities/checkfilestatus.cpy](https://sourceforge.net/p/open-cobol/contrib/HEAD/tree/trunk/samples/worldcities/checkfilestatus.cpy) it became surprisingly handy:
![rotated_case_branches3 27](https://cloud.githubusercontent.com/assets/15326471/26181395/0aecc752-3b70-11e7-8947-6414ac246df6.png)
The configuration may be done via a spinner on the Structure preferences dialog:
![preferences_menu3 26-06](https://cloud.githubusercontent.com/assets/15326471/26181828/84bac842-3b73-11e7-84d2-f90a0b3c3781.png)

**Comment by GitMensch** [comment]
Yes, this one looks much nicer. But in most cases a `switch` or an `EVALUATE` won't consist of a single instruction, may consist of multiple inner `switch`, too.
How much work would be the "invention approach"? Is there any chance that I can add this without knowing the inner parts of Structorizer? [all approaches I've tried so far, including the reduction handling for the drawing did not worked out so far :-(]

**Comment by codemanyak** [comment]
> Yes, this one looks much nicer. But in most cases a switch or an EVALUATE won't consist of a single instruction, may consist of multiple inner switches, too.

Which way ever: though theoretically an infinite nesting is possible, for practical reasons it should be limited, e.g. by outsourcing to routines. So if the algorithm doesnt fit into a soccer field it should be decomposed, shouldn't it? (Method `buildNSD_R(...)` in the COBOLParser is such an example :wink:).
There are several tools to help regaining overview in Structorizer (and generally in Nassi-Shneiderman diagrams) already: You may collapse large elements (as long as their internal layout temporarily isn't of interest), on your helpful suggestion we have an "outsourcing" function as well, and we have this new rotating option now, which is selective: it rotates just those branches that are atomic or collapsed. To outsource a branch replaces it by an atomic Call.)
From my experience, on designing an algorithm, such huge element nestings are rather rare. That's why I am hesitant to integrate non-standard elements just to support diagrams of exorbitant complexity. The code import may of course produce such huge monsters as we can see with the real-world COBOL examples. But from my point of view, without decomposition the graphical representation will be of little use anyway - no matter if it's a kilometer wide or a kilometer high. (Excuse the exaggeration.) This sounds a little ignorant and harsh, I know, but I still think it should actualy hurt to produce agorithms that exceed a certain size and direct nesting depth.
So Structorizer should continue motivating a concise algorithm structure, wouldn't you agree?

**Comment by GitMensch** [comment]
> So Structorizer should continue motivating a concise algorithm structure, wouldn't you agree?

Yes, I agree - but we don't have the same approach (we don't need to btw): While I don't want to encourage people to create new NSDs with that big decision depth it will very likely occur when importing from an existing source file (the reason for the import is likely to structure a source which is otherwise hard to understand). I'd personally like the import to work quite good for the mentioned goal and by this enable people to outsource parts, do logic cleanup - this is again quite hard for big if/else constructs and very wide CASE statements - and yes I think having the same complexity with the mentioned vertical layout is easier to understand (and the complete final drawing needs much less space).
What about coming back to the original suggestion to use the non-standard vertical case construct?

**Comment by codemanyak** [comment]
@GitMensch 
I see. This is a serious no-nonsense task you elected Structorizer for. Wow. I take it as an honour having contributed to something potentially useful for professional purposes. (This also explains for me the enormous efforts and many excellent ideas you invested in the enhancement and improvement of our "little tool to draw Nassi-Shneiderman diagrams".)
It's certainly a reasonable thing to support different views of complex algorithms. This may have the potential to change my mind, though I'm still not happy with the transposing of structured elements because it partially invalidates the clean and convincing concepts of structograms: strictly vertical control flow and horizontal branching (this way showing the "real" structure).
Personally, I find deeply nested if-then-else hierarchies even harder to deal with than the relatively regular CASE statements. On the other hand, the more you coerce horizontal spreading into a vertical pseudo-sequence, the closer the similarity between the "optimized" graphical representation and the shape of the imported code grows the less elucidation you can achieve, I'm afraid.
So what would you do with widely spread alternative trees? The asymmetric if-then-else-if chains are more or less equivalent to Case statements and might be represented in a similar or even the same way as your transposed CASE drawing proposal. But symmetrically (exponentially) expanding alternatives? To transpose them would be totally absurd. My empirical opinion is that typically there are either many lean or few large branches, rarely a very large number of fat branches which you can't outsource. But well, existing code can always prove you wrong...
There are more ways to reduce a diagram to its bare structure in Structorizer, on the other hand: You might swap text and comments (particularly if there are few comments, see screenshot - maybe we add a mode to switch off any text...) or reduce font size to a minimum for instance, not to mention selective collapsing.
![checkfilestatus-2](https://cloud.githubusercontent.com/assets/15326471/26250148/71b8b7ae-3ca9-11e7-8cab-3ab402426052.png)
Well, I imagine all this won't convince you... Maybe I'll give in at last.

**Comment by GitMensch** [comment]
Coming back to this with two questions:

1. Is it possible to generate a CASE with an expression to prevent many nested if else ?
![grafik](https://user-images.githubusercontent.com/6699539/28062159-575d3dbe-662d-11e7-90b3-64c2e745f5ed.png)

Removing the compared value doesn't work
> Parse error at line 1, column 1. Encountered: ?

Replacing it by a white space or semicolon leads to
> Parse error at line 1, column 3. Encountered: ==

Just placing true in the compared value results in
> Sourced file: inline evaluation of ``true == a == b;``": Type mismatch in operator.

The goal is to allow a nicer drawing than nested if-else as these are (with > 5 cases) not only looking weird, they start to be very unreadable.


2. Was there a final objection to my "optional, has to be manually activated" non-DIN "invention" of visualizing CASE statements? This makes even relative "simple" CASE statements like the filestatus sample much more readable...

**Comment by codemanyak** [comment]
> 1. Is it possible to generate a CASE with an expression to prevent many nested if else ?

No. The CASE element offers the basic functionality that is compatible with Pascal, C, and Java.

> The goal is to allow a nicer drawing than nested if-else as these are (with > 5 cases) not only looking weird, they start to be very unreadable.

May I remember that a structogram is not a maximum convenience programming tool but a (semi-)formal description of an algorithm structure?
Your diagram example may be readable for a COBOL-accustomed programmer, but for the rest of the world it is utterly confusing: How many different enumerable values may the discriminator expression `true` have? Right: exactly one. So it's simply not a case selection. Over and out.

**Comment by GitMensch** [comment]
The "true" reference was just an example, replacing it by "eval" would be the "more general readability" version. I've thought about replacing it to if/else constructs for the Executor and the code generators, but I accept a "won't be in Structorizer".

Can I hope for an implementation of 2 (different drawing for CASE upon explicit request)?

**Comment by codemanyak** [comment]
> Can I hope for an implementation of 2 (different drawing for CASE upon explicit request)?

Definitely not with release 3.27, I'd say.
I'd like to concentrate on #423 and #354 (and I have to admit that I still have reservations).

**Comment by GitMensch** [comment]
> Definitely not with release 3.27, I'd say.

Sounds good, I'd change the milestone to 3.28 if I could ;-)

> I'd like to concentrate on #423 and #354 

Sounds good, too.

**Comment by codemanyak** [comment]
>  I've thought about replacing it to if/else constructs for the Executor and the code generators...

Well, the COBOL import already replaces such kind of EVALUATE statements with if/else constructs. And this is the only possible source where such twisted CASE statements might come from (unless some COBOL programmer tries to form a CASE element this way in Structorizer).
