### ISSUE TITLE
COBOL import: Convert "wordy" comparisons with and/or to multiple comparisons

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#407]
![grafik](https://cloud.githubusercontent.com/assets/6699539/26101798/b7da58e2-3a32-11e7-8a31-6d0bdac10323.png)

As the Executor knows what type file_status is it would be nice not only to replace `=` in comparisons by `==` or even `.equals()` [see #406 ] but translate the "more natural for speaking" version `a = b or c or d` to multiple comparisons `a == b || a ==c || a == d`.
While this would especially help with NSDs imported from COBOL (where we could change the import to expand it to multiple comparisons already) the type of writing seems to be more language-agnostic, natural, easier to understand (you see that the comparison evaluates only a single variable without the need to optically check if the variable names are only similar or identical) and and make the NSDs "shorter" especially when `a` is not a one byte name but a long name instead (you can even see the result with the given sample `file_status`.

**Comment by codemanyak** [comment]
As already outlined in #406, I would have done so if the COBOL grammar gave me more help to to so.

**Comment by codemanyak** [comment]
I don't think we should leave the secure ground of synactically unambiguous logical expressions with clear operator precedence hierarchy. The COBOL compiler may have found some way to interpret "wordy" expressions but they are highly ambiguous.
What would be meant by `a = b or c` if all three variables are boolean ones if we don't restrict the syntax? Depending on operator precedence this might already mean `(a = b) or c` (in C, Java and the like) or `a = (b or c)` (in Pascal). In wrdy COBOL style this might also mean `(a = b) or (a = c)` now? No, thanks.
More than that, what about expressions `a or b = c`? And so on and so on.
I won't open another Pandora's box. If you have an idea how to make strict syntactical sense of COBOL conditions on parsing then please come forward.
BTW there are still other extremely nasty expressions in COBOL: those with infix "not" or negated tests like `IS <not> <condition_or_class>`. Typically I can't easily identify where that damned expression actually begins (i.e. where to place the `not` operator instead, particularly when it's not clear whether a simple "not equal" operator would do here). In particular because that <condition_or_class> is not necessarily a complete condition but may be some "wordy" fragment.

**Comment by GitMensch** [comment]
I completely agree with you - as Structorizer keeps many languages in mind (which is good) it is best to have the most clean expressions within NSDs only.

> If you have an idea how to make strict syntactical sense of COBOL conditions on parsing then please come forward.

Just posted this to the other issue: use the same approach that the compiler does which grammar I've used.

**Comment by GitMensch** [comment]
I'm side-merging #406 in here as this is the correct place for handling the issue. the important parts for the TODO are:

@codemanyak wrote:
> I have already invested some efforts to mend many of the "defective" COBOL conditions on import. This works more or less fine if there is at least an orphaned comparison operator like in test > 3 and < 15. Unfortunately I haven't had a good idea how to do anything meaningful with expressions like [`file_status = "00" or "10"] where the only chance is to test upon guessed types. But even then it isn't trivial in the given parsing context to produce the correct expression: `file_status = "00" or file_status = "10"`. The damned COBOL syntax defines conditions simply as lists of tokens, there is no operator hierarchy in the grammar (other than for arithmetic expressions)!

@GitMensch wrote:
> It may help to have a look at the way GnuCOBOL handles nearly the same grammar tokens:
>
>The main entry point for this is in [cobc/typeck.c][1],  `cb_build_expr()` which gets a list of token trees that are simply iterated. The main part it is doing is handling the class checks first (and generates function calls for these), leaving most of the other parts to `cb_expr_shift()`.

[1]:https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnu-cobol-2.0/cobc/typeck.c

I'd like to suggest the following for this issue:

**Postpone this one**

While the execution and code export would need a fix for this issue and both are very nice features:

* expressions like these can be manually-solved after the import and therefore can be even targeted after the https://github.com/fesch/Structorizer.Desktop/milestone/2
* other parts are much more important (see suggested list below) as these cannot be manually solved
* implementing a translation of the expression tokens like the GnuCOBOL compiler does and resolve them for the NSD generation looks like the best thing I'm able to commit to the COBOL import when the general export of "simple + clean" expressions work and I'd "only" have to do the translation

Things I suggest to prioritize for the COBOL import instead:

* import of `PERFORM section` - I'm not 100% sure but think the approach of the sub-nsd with no variables passed directly but with an IMPORT of all the vars the program has (we could name the import NSD something like `$programname + _data`) we've discussed could be currently done without further extensions (the IMPORT part #389 seems to be nearly finished) and would work fine
* import of comments - these have been found to be returned as token `(comment)` with the actual comment as the token's `value` (see https://github.com/fesch/Structorizer.Desktop/issues/354#issuecomment-301443992) and would be important for the Pascal and C parser, too

Does this sound like a plan?

**Comment by codemanyak** [comment]
@GitMensch 
> Does this sound like a plan?

Of course. It coincides more or less with my ultimate remarks for #354. As outlined there, I would add the import of COBOL tables (arrays), which are already better supported in Structorizer.

**Comment by codemanyak** [comment]
@GitMensch 
Do you think this issue is sufficiently addressed by the current version? Then I'd suggest to close it.

**Comment by codemanyak** [comment]
Well, I think, all the prioritized import issues discussed above in https://github.com/fesch/Structorizer.Desktop/issues/407#issuecomment-302314808 have been solved sufficiently in the meantime. So I close this issue now.

**Comment by codemanyak** [comment]
While there had already been support for conditions like `a > 6 and < 21", I added added some heuristic support for conditions like the one in this issue description (`file_status = "00" or "01"`), but it is limited to integer or string literals on the right-hand side, since it's getting hard to tell whether more complex operands happen to be of boolean type or not. The parsing strategy of GnuCOBOL hasn't been adopted yet.
