### ISSUE TITLE
Add import from Java

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#410]
Moved from #354 to not forget about it but also to explicitly *exclude* it from the [milestone 3.27](https://github.com/fesch/Structorizer.Desktop/milestone/2)

The COBOL and C import should be in the focus first as both "work" (if the expected way of sources are used for input) and both raise general issues like import of the comments and record/struct handling in NSDs in general.

**Comment by codemanyak** [comment]
I succeded to construct a usable grammar for Java SE 8 (with some restrictions wrt. to annotations and lambda expressions, though), such that the Java import project is on the way now.
The major challenge, however, is how to represent the class context, particularly nested classes, in a more or less adequate way. The class itself might be represented by an main diagram (either rathe empty or with the Main method - if declared - as algorithm content), for types, fields, and initialization, an Includable diagram may be used, of course. The latter could even contain the standard constructor. Further constructors and the remaining methods can be built into subroutine diagrams.
This is fair enough without nested classes, but what if the code contains nested classes? What about inheritence?
It would hardly make sense to integrate UML class diagrams into Structorizer (though this seem to be the only really adequate way to express the relation among classes and between class and methods).
So, in a first version we will certainly have to concentrate on the mere structural representation of the methods without the aim to ensure executability - OOP support is (and will certainly remain) just out of reach.

**Comment by codemanyak** [comment]
To address the context problem a new field "namespace" for the diagrams is proposed, which would be filled with the package for global Java classes and with the respective class path for member or local classes, methods etc.
This namespace field will be used als qualifier prefix in the Arranger index and may be edited by the user:
![grafik](https://user-images.githubusercontent.com/15326471/108913241-fcaf0f80-7629-11eb-8928-450a15ea06db.png)

The namespace (path) might also be used for additional disambiguation in Executor (a maximum path coincidence might then decide about the favourite subroutine among several ones with matching signature, but this is of rather academic value as diagram imported from Java code will usually not be executable, due to too many OOP stuff Structorizer can't make sense of...)

**Comment by codemanyak** [comment]
Via a context menu item in the Arranger index the user may switch between names space prefix (long, but linear presentation) or a tree reprsentation of class / method nesting:
![grafik](https://user-images.githubusercontent.com/15326471/109454985-da682800-7a55-11eb-9159-3ab0cacd9f5a.png)
