### ISSUE TITLE
Scrolling Performance: Drawing functions seem to be called too often

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#417]
Here is at least one reproducible place:

* open NSD (all drawing is complete)
* set breakpoint in lu.fisch.structorizer.elements.draw (around line 171)
* click on File->Save as...
* breakpoint is reached as the NSD is re-drawn (before the save-as dialog pops up)

[when the reason is found and fixed we may find other places using the breakpoint technique ]

**Comment by codemanyak** [comment]
I will analyze this. I also got the impression that re-drawing might be done slightly too often.
Somethimes, however, re-drawing might be due because a selection is temporarily made invisible or because a comment popup is to be suppressed or the like.
B.t.w. the use of breakpoints is not altogether unknown to me. One must of course be aware that there are concurrent threads and re-drawing is often done as a possibly delayed thread ("do later"), such that breakpointing within it might not reveal the actual initiator (but fool the tester with retorted behaviour). My experience was rather (to my surprise) that redrawing is not as performance-critical as I expected - and in certain cases re-drwaing too few times caused defective images.

**Comment by codemanyak** [comment]
A first analysis shows that the apparently superfluous redrawings are induced via the overridden method `Diagram.paintComponent(Graphics g)` inherited from `javax.swing.JPanel`. The logic when and why this method is called is entirely up to Java Swing.
In the case you described it is just the raising of a `JFileChooser` instance, which causes the owning Component (here the `Diagram` instance) to repaint itself.
It is possible but imposes obvious risks to have this method doing nothing when it is called. The method might decide it by means of some status field set before certain Structorizer actions are performed. Or we could try to find out what exactly the damaged region was and only to repaint the actually damaged parts (e.g. the ones eclipsed by the menu). But these selective activities might require even more time than simply to repaint the diagram as requested.
At least I can't see that the repainting has a vastly degrading effect. (The use of the scroll bars is a quite different thing, though: within huge diagrams you should better navigate with the cursor keys, this is as performant as with small diagrams, which means that it is not the drawing that causes the lacking responsiveness).

**Comment by GitMensch** [comment]
Thank you for the interesting points. I've came to the conclusion that the drawing it is likely auto-triggered but I had no idea where.

You are correct that there is surely no use in trying "to find out what exactly the damaged region was and [to only] repaint the actually damaged parts" (even if there wouldn't been the complexity to find out where this would be necessary).

The "real" issue where the lacking occurs is surely using of the scroll bars, if this doesn't have to do with this here than I suggest to close this issue as invalid.

Should I create a new issue for the scrolling performance or is this something we can't change otherwise than outsourcing code parts to IMPORT + callable NSDs?

**Comment by codemanyak** [comment]
> The "real" issue where the lacking occurs is surely using of the scroll bars, if this doesn't have to do with this here than I suggest to close this issue as invalid.

I thought so. Actually it has to do with the frequency of the redrawing, but during scrolling. This is also OS-dependent (in Windows the scrolling-induced redrawing is about five to ten times higher than in some Linux distributions, at least when run in a virtual machine).

> Should I create a new issue for the scrolling performance or is this something we can't change otherwise than outsourcing code parts to IMPORT + callable NSDs?

We might further pursue this problem under this issue, I think, but would have to concentrate on the scrolling hyperactivity. I can't say whether we may have a chance to solve it, though. It seems that the system is really inflating by generating redraw requests way more frequently than can be executed. If the event pumping happens entirely within the Swing framwork without a Structorizer method getting the opportunity to detect the hyperventilation then we are rather helpless in the face of the phenomenon. Otherwise we might perhaps suppress a certain percentage of the paint requests. According to some quick tests, the drawing requests don't interrupt each other, so the queueing seems to be done in the Swing framework, which lets it appear rather unlikely that we can get hold of the detention whithout questionable hacks.

**Comment by GitMensch** [comment]
> According to some quick tests, the drawing requests don't interrupt each other, so the queueing seems to be done in the Swing framework, which lets it appear rather unlikely that we can get hold of the detention without questionable hacks.

Questionable hack as suggestion: store the last time of the drawing and only draw if the last drawing occurred longer than 0.1 seconds ago [real hack but can show if it is useful to further investigate - and if it is leaves an option to tweak performance + resources vs. stuttering]

**Comment by codemanyak** [comment]
I'm not sure whether this hack makes sense. If the drawing happens to last longer than the proposed 100 ms (with huge diagrams) then it's unlikely that we would see the request more frequently if the queueing works without preemption. I just made a test with writing the result of `System.currentTimeMillis()` on every call of `Diagram.paintComponent()` - and there are arbitrary elapsed times between two calls ranging from 20 ms to several seconds __without__ visible congestion. So this doesn't seem to be a helpful criterion. But it's a point to start the analysis with in order to detect patterns of correlation.

**Comment by codemanyak** [comment]
I managed to set the scrolling unit proportionally to the diagram size, which takes one order out of the polynomial drawing complexity and thus improves scrolling performance remarkably.

**Comment by codemanyak** [comment]
The scrolling unit adaptation had been missing or ineffective on loading or importing diagrams of all things. Not only the invocation ofthe method was forgotten, it usually failed to work because the first drawing preparation of the fresh diagrams is delayed such that the obtained extensions seem to be (0, 0).
A heuristic workaround based on the number of contained elements can help here.
