### ISSUE TITLE
Performance: Element.writeOutVariables doesn't cache ioSigns / jumpSigns

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#418]
The comment "// These markers might have changed by configuration, so don't cache them" is surely correct

The current approach is: we never cache them with the result that *every* access to this function reads them again and again. And the function is called often, therefore this minimal performance tweak may even have a measurable result (in any case it makes the code easier to read and `writeOutVariables` tighter.

I suggest to

* have `specialSigns`, `ioSigns` and `jumpSigns` cached 
* create two functions `private setupSpecialSigns` and `public setupConfigSigns`
* call the first in the case `if (specialSigns == null)	// lazy initialisation`, similar for `setupConfigSigns`
* call `setupConfigSigns` from on configuration change, too

If someone tells me where "configuration change" is finished and if the approach is OK I'd give the change a try.

**Comment by codemanyak** [comment]
The 39 so-called "specialSigns" ___are___ cached (initialized on the first call of `writeOutVariables()` and never changed or reset during the session).
The so called "ioSigns" and "jumpSigns" are just six keywords in total to be retrieved, which is few in comparison to the many tokenization and reconcatenation actions the element texts undergo, but well, what's done within a frequently performed loop is always worth an optimization attempt.
The keyword configuration can change whenever the ini file is reloaded (more occasions than one would expect, watch out for `CodeParser.loadFromIni()`) or when the parser preferences are changed (`Diagram.parserNSD()`) or adopted from a just loaded NSD with differing keyword set. At the end of these methods the proposed static fields `ioSigns` and `jumpSigns` of class Element should be reset in order to induce lazy re-initialization.
I guess, though, that the performance gain will hardly be measurable.

**Comment by codemanyak** [comment]
Well, this is not a crucial point for drawing performance.
