### ISSUE TITLE
Executor (and GUI) doesn't recognize variables by declaration or sub-program call

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#427]
I *think* I have asked this before but I'm in any case confused:

It looks like the executor doesn't defines any variables during variable declaration (neither does the GUI). Variables are only recognized when values are assigned to them:
![grafik](https://user-images.githubusercontent.com/6699539/29166291-14b8c95a-7dc6-11e7-9bc1-4a61683ec943.png)

This is especially bad if the variables are passed to another diagram:
![grafik](https://user-images.githubusercontent.com/6699539/29166368-64151a58-7dc6-11e7-9cdf-c51452350d11.png)

leading to:

![grafik](https://user-images.githubusercontent.com/6699539/29166425-9505f8f8-7dc6-11e7-9f57-12239dc5cd55.png)

**Comment by codemanyak** [comment]
Just as explanation: I explicitly designed this behaviour after introducing the tolerance of variable declarations (issue #335) because otherwise the existing mechanism of detecting un-initialized variables didn't work anymore. (Or at least the font style wouldn't make visible anymore whether an initialization was present or not.) Issue #335 was a mere tolerance! Not even the associated type has been enforced on subsequent assignments (in Structorizer, variables can always be re-typed by assignments).  I wanted to maintain the traditional assignment freedom used in Structorizer. By then, we had never had the case of routines passing values into un-initialized parameters.
This isn't even a good practise to pass un-initialized variables, I think. In Java, you would usually initialize such an "out" parameter with null. I recommend an initialization even in C++, otherwise you couldn't detect whether the routine did its job to set the reference argument. (In C, you would have to pass a definite pointer - which may point to an uninitialized storage region, though. This frequent practise is often an indicator for backward information flow, but an unambiguous routine comment is always better.)
So far the explanation for the current behaviour.
This is one of the points that may have to be reviewed on occasion of and with regard to #423. Maybe, declarations will have to impose more restrictive effect in order to give them more potential. Structorizer hadn't statically detected, either, whether a found assignment occurred too late (i. e. after the first reference to a still un-initialized variable). Indeed, the implications of #423 are more complex that I had hoped. I had no chance to accomplish the enahncement before my vacations, therefore.

**Comment by codemanyak** [comment]
After having revised my wobbly answer to a precise and definite statement, I dare to close this issue.

**Comment by GitMensch** [comment]
Thank you for the explanation. With the Java view it all makes sense and the original code definition from COBOL would have to be imported/changed as `char[2]` in any case.
I'll likely recheck this sample program when I find the time to review the current code state (hopefully in the coming week).
