### ISSUE TITLE
FOR loop should accept float numbers for stepping like "0.1"

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#43]
Thanks for the nice Entry fields in for loop, but step entry should accept also float numbers.
EDIT: Oh, i see, in the text field mode, there is an error warning <0.1 isn't a valid integer constant>.
Then it's like more an enhancement to all parts, includes executor, than a but fix. Locking forward.

**Comment by codemanyak** [comment]
I'd like to object. Though often used diferently, e.g. in C or Java and the like, the idea of a For loop is mere counting, i.e. to perform an exactly predictable number of steps. With real numbers, however, this will never be the case, due to rounding, limited precision, etc.
To do floating-point "steps" ought to be left to while loops, sincerely.
I even decided against variable step widths because e.g. for code generators its very uncomfortable to implement a testing mechanism that is sign-proof - how do you guess whether the loop value will grow or descend?

**Comment by codemanyak** [comment]
Bob and me decided in unison to reject this enhancement request. For loops ought to remain restricted to cardinal types by design.
