### ISSUE TITLE
Drawing of Structorizer continuation doesn't work in evaluations

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#447]
Continuation via `\` works fine in normal single instructions but not in a if/switch:

![grafik](https://user-images.githubusercontent.com/6699539/32219799-b61ecfb6-be2f-11e7-9322-70f000293d6f.png)

Actually I don't have a real good idea how to draw this but the current drawing needs a lot of space.

**Comment by codemanyak** [comment]
Actually, I didn't bother to implement line continuation in loops and alternatives because it's simply not necessary there: If you write the condition over several lines (without backslash at the end) then Structorizer concatenates the lines anyway. But I should have considered the case anyone tries it nevertheless, in this case producing a syntax error. So the code should ignore or better eliminate endstanding backslashs in conditions.
With CASE elements I also backed off because I was afraid of confusing the evaluation.
But okay, I'll mend the inconsistency.
With regard to the shape: less is more here. The best is to avoid too complicated conditions in the head of alternatives. You might e.g. assign the expression to a logical variable in advance and put this into the alternative head instead. Or you might try to construct the condition lines in triangular shape (many terms in the first line and very few in the last one...)

**Comment by GitMensch** [comment]
> You might e.g. assign the expression to a logical variable in advance and put this into the alternative head instead.

Sounds reasonable and the line breaks work there, too.
Is this something the code import may could do automatically if the expression contains any line break (or is longer than N chars)?

**Comment by codemanyak** [comment]
@GitMensch 

> Is this something the code import may could do automatically if the expression contains any line break (or is longer than N chars)?

Of course the import could do so. But this would enlarge the bias to the original code. So I am not entirely  sure whether we should really spend so much effort to merely beautify the resulting diagram.
If you say yes, then be it so.

**Comment by codemanyak** [comment]
Line continuation in Alternatives is fixed (bugfix branch). In the drawn diagram the backslashes are suppressed (in loops now as well), in Executor they won't cause harm anymore.
CASE elements and FOR loops haven't been touched yet. Their fixing is a little bit more complex, but it will have been done before 3.27-01 will be published.

**Comment by GitMensch** [comment]
@codemanyak Thank you!

**Comment by codemanyak** [comment]
Up to version 3.32-27, there have still been some vuleribilities against Case elements with broken text lines on drawing and code generation (particularly in BashGenerator)
