### ISSUE TITLE
New startskript for Linux

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#451]
Hi.

Because the structorizer package has no "release notes" or "readme" file with informations about the requirement I had problems to start the version 3.27. Even the changelog has no information about the change of the requiered java version.

So the start-skripts may/should check for the right java version.
For Linux I did it as follows:

```
VERSION=$(java -version 2>&1 | head -1 | cut -d. -f 2 )
if [ $VERSION -ne 8 ]
then
  echo "Your Java Version is $VERSION, but version 8 is required. Please update."
  exit 1
else
  java -jar $(dirname "$0")/Structorizer.app/Contents/Java/Structorizer.jar "$@"
fi
```
How to do similar in Window or Mac I don't know
Fine regards
Rolf

**Comment by codemanyak** [comment]
Thanks. That's a good point. We should have altered the Java requirement specification.
I don't know, either, whether for Windows the start wrapper would have to be changed or if it is sufficient to specify it in the build and project scripts (in nbProject) where the specification is still (due to bad experiences with openJDK in the past):
```
javac.source=1.6
javac.target=1.6
```
I don't know what tools Bob uses to build a release so I must leave it to him to do the necessary updates.

**Comment by fesch** [comment]
I just use NetBeans to build ... using JDK 1.8

**Comment by reks99** [comment]
Hi Bob,
of course the used java version reported is 1.8, but i cut off the leading 1.

Fine regards
Rolf

**Comment by fesch** [comment]
Sorry, I missed out the first message.

Structorizer.sh and Arranger.sh are now updated.

For Windows and Mac, I still need to check ...

**Comment by fesch** [comment]
Build a new Windows-Wrapper ;)

**Comment by codemanyak** [comment]
@fesch 
Hi Bob, have you had the chance to check whether the start on Mac OS is free of trouble?

**Comment by fesch** [comment]
Not yet ...

**Comment by hans005** [comment]
> VERSION=$(java -version 2>&1 | head -1 | cut -d. -f 2 )
> if [ $VERSION -ne 8 ]
> then
>   echo "Your Java Version is $VERSION, but version 8 is required. Please update."
>   exit 1
> else
>   java -jar $(dirname "$0")/Structorizer.app/Contents/Java/Structorizer.jar "$@"
> fi
> 

This script is a bad idea! I got this together with Structorizer v.3.28 and after updating my Ubuntu to 18.04 it (of course) did no more start.
Issues:

1) You should NOT check for $VERSION -ne 8 but rather it should be equals or greater than -ge 8
2) Even that is not sufficient since for OpenJDK the versioning name schema changed. Current version is 10.0.1 so above script will have "0" as a version.

How about just do 

echo "In case Structorizer does not start, please check that your Java version is 8 or newer (type "java -version" in a terminal).

Greetings,

hans

**Comment by reks99** [comment]
Hi,

I changed the script, so that it should run with ubuntu as well 

#! /bin/sh -x
VERSION=$(java -version 2>&1 | head -1 | cut -d. -f 1 | cut -d'"' -f 2)
if [ $VERSION -eq 1 ]
then
  VERSION=$(java -version 2>&1 | head -1 | cut -d. -f 2 )
fi
if [ $VERSION -lt 8 ]
then
  echo "Your Java Version is $VERSION, but version 8 is required. Please update."
  exit 1
else
  java -jar $(dirname "$0")/Structorizer.app/Contents/Java/Structorizer.jar "$@"
fi
So try it, because I have no Ubuntu running.

Fine regards

**Comment by GitMensch** [comment]
Works on Trisquel, I'll add a PR that uses @reks99 two-step check within the next minutes.
