### ISSUE TITLE
Enhancement for C-Code exporter

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#453]
Hi Kay,
I played a littel bit with the new code importer with files exported from structorizer. Here a few "Ungereimtheiten" I found.

1. I don't know, how to declare a string variable (perhaps with a given length) in the HLL. Structurizer always export "String" and not something like _char VAR[]_. The importer works with a correct definition of a char variable, but not with the "String"-export.

1. I think the first argument of a scanf command can derived from the varible type to store the result in, if it is not an array. For a string variable it might be "%s". Clear for me is, that not all aspects can be handled, but a simple version may be helpful for beginners.

1. Variable substitution in a printf-statement is wrong. There need to be place holders like %i or %s and the variable name should be listet at the end of the format string. Also here not all possibel format options can be generated - the developer should still have to do something, but beginners get a hint.

1. Last, but not least, a additional 'printf("\n")' in an output-statement is not a so good idea, because \n is usually part of the format string and if the programmer would like to concatenate its output with more than one printf statement he has touble.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf,
you are right in general. But let's go to the details.

> I don't know, how to declare a string variable (perhaps with a given length) in the HLL.

Here HLL is not equal to HLL, e.g. C++ has a `std::string` class (you will see in the export, that "string" is already lower-case - what's missing is the include directive and the using clause), Java has a `String` class. In C, however, there is no such thing as a string type, you would indeed have to use character arrays. But now, how should they be declared? They might be defined with fixed length like `char text[40]` or as `char*`. But now the troubles go loose: What about memory management? What about assignments, concatenation etc.? All this would require additional reservations and `string.h` functions. Way too complex by now for the C generator. So it seemed better to provoke a compiler error right away in the first place than a thousand runtime errors or even silent catastrophes with apparently correct declaration. The user will have to intervene here. Therefore the TODO comment above the variable declarations. And the deliberately placed "String" type name to show what the original intent of the variable was. We might add a more specific comment to all the variables of this type.

> Structurizer always export "String" and not something like char VAR[].

Again, this is within the decision of the specific generator. And it's not always exactly "String".

> I think the first argument of a scanf command can be derived from the variable type to store the result in, if it is not an array. For a string variable it might be "%s". Clear for me is, that not all aspects can be handled, but a simple version may be helpful for beginners.

Again we talk about C, obviously. You and I know that the correct choice of format specifiers for scanf is anything but trivial. Even little mistakes here tend to compromise neighbouring variables, the stack frame, or even the entire process. So we better backed off, left the format string empty and placed an associated TODO comment at the file top. Structorizer had acted this way all the time. Meanwhile type guessing has significantly improved but is still very limited. Should we insert some specifiers and others not? This would be even more confusing. The user has to check and revise it anyway and must consult the example URL to start with. Okay, the format string could be filled with "TODO" to draw the attention more intensively. Variables are already equipped with address operators but even this isn't always correct (e.g. for "string" variables it would have to be omitted).

> Variable substitution in a printf-statement is wrong.

No, it's not wrong, it's by choice incomplete again.

> There need to be place holders like %i or %s and the variable names should be listed at the end of the format string.

We perfectly know that. It's less dangerous than for scanf but, again, it's not quite trivial. The things to be output may not only be variables but arbitrary expressions. And they ARE listed as further arguments after the (empty) format string.

> Also here not all possible format options can be generated - the developer should still have to do something, but beginners get a hint.

They get. There is the TODO comment at the beginning of the function etc. And well, we might fill a TODO into the format string. I thing it's better to leave it completely to the user than to try a vague percentage. Maybe we add a C-specific export option whether to try it - at the risk of the user.

> Last, but not least, a additional 'printf("\n")' in an output-statement is not a so good idea, because \n is usually part of the format string and if the programmer would like to concatenate its output with more than one printf statement he has touble.

Technically, it makes no difference whether we place the `\n` at the end of the (now empty) format string or into an additional `printf()` statement. It is there because of the equivalence to the Structorizer output instruction. Each output instruction in Stuctorizer generates a newline at the end. If you want to put several results in the same line, you will have to put the expressions into a single output instruction. This is what the C generator truly reflects.

**Comment by reks99** [comment]
Hi Kay,
many thanks for your explanations. 

Under this circumstances you should stop trying to export more than just the control structures (if, while, case. function...) nothing else or only as comment.
An search for all the shortcomings is more time consuming (of course one always will mis some), then write the code in the structure frames.

The problem is, that the promise of the possibility of an export into different language only works good for the structures out of a nsd.

At least one comment for your argument against the additional 'printf(" ", "\n")': Very offen I (and other programmers) build screen messages out of more prints for example to print out a list of modules in a row where every module prints its name by itself - which is impossibel if there is alway a "\n" printed. If a programmer (i.e. user of an exported nsd) wants this separate print, he may/can add it later. 
BTW insteed of the empy file descriptor in the printf it can contain "stdout" what is the most often path usually in the development phase.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> At least one comment for your argument against the additional 'printf(" ", "\n")':

The actual structure is: `printf("TODO: specify format", expr1, expr, 2, ...); printf("\n");`, by the way.

> Very offen I (and other programmers) build screen messages out of more prints for example to print out a list of modules in a row where every module prints its name by itself - which is impossibel if there is alway a "\n" printed. If a programmer (i.e. user of an exported nsd) wants this separate print, he may/can add it later.

No poblem. If you can add the newline later, then you will also be able to remove a superfluous newline, or wouldn't you? So I adhere to the closer equivalence with Executor behaviour, if you don't mind.
In Structorizer, you might compose the line to be printed in advance by string concatenation. This is of course hard to export automatically to C, as outlined earlier.

**Comment by codemanyak** [comment]
@reks99 
> Under this circumstances you should stop trying to export more than just the control structures (if, while, case. function...) nothing else or only as comment.

Rolf, all these modes exist already.

**Comment by codemanyak** [comment]
Two "workarounds" prepared: Type names "string" and "String" will now be converted to `char*` (though this causes the described risks), scanf and printf format strings aren't left empty but now filled with "TODO: specify format".
Attempts to guess correct format place holders in format strings will (export option) postponed.

**Comment by reks99** [comment]
Hi Kay,

I would like to opt for `char VAR[]` with no length as export output for a string variable. It is a more often used way to declare a string in C and the compiler will print an error, to remind for write a value.

Fine regards
Rolf

**Comment by reks99** [comment]
Hi.

Again some words/questions about variables in print statements.
Bash and PHP allow inline variable expansion Perl, C, C++ and other do not. So for example (in bash) 'echo "my name is ${name}."' is valid, where this needs to be translated into 'printf("stdout", "my name is %s.", name);' in C or 'print "my name is ".name."."' in Perl.

So the question is, how to write a output message with variables in structurizer to be language independend or better, how the executer would likes to  have it?

Fine regards
Rolf

**Comment by codemanyak** [comment]
How the executor would like it is very clear:
```
OUTPUT "my name is ", name
```
The export of this instruction should also produce something sensible:
bash: `echo "my name is " ${name}`
Perl: `print "my name is ", $name, "\n";`
C: `printf("TODO: specify format", "my name is ", name); printf("\n");`
C++: `std::cout << "my name is " << name << std::endl;`
Java: `System.out.println(("my name is ") + (name));`
Python: `print("My name is ", name, sep='')`

By the way a nice example what virtuosity Structorizer is to offer. :wink:

**Comment by GitMensch** [comment]
To add to the virtuosity COBOL export should be `DISPLAY "my name is " name` :-)
