### ISSUE TITLE
Where is the "Hello World" tour for newbies?

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#459]
Hi,
when I open latest version of structorizer the first time a modal window ask for reduced menu and a guide tour with a "Hello world" example.
When accept this offer, the menu is reduced but I found no clickable way for the tour.
What do I wrong?

Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf, just follow the hints in the Analyser report area. They guide you step by step through the creation of a Hello World program. If that is done, the IPO guide will be activated and you may either start with a new diagram or try to enrich the current one according to the recommendations.
I had decided to (ab)use the Analyser for the guided tours. This may not be optimal, but draws the attention to the means and tools already existing instead of introducing additional assistents, which will then no longer be used.
Well, it's a first draft and open for discussion and critics.
First evident drawback: Apparently it's not as obvious as I had thought.

**Comment by reks99** [comment]
Hi Kay,

I found some checkboxes in the menu _prefereces | settings_, but no point to start the tutorial - what do you mean with the "Analyser report area"? How can this reached by the menu (icons)?

Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf,
The "Analyser report area" is the list view at the bottom of the Structorizer window. On start it used to be enabled. Otherwise press F3. Please have a look into the [User Guide](http://help.structorizer.fisch.lu/index.php?menu=82&page=#guided_tours).

Just as a matter of curiosity: Do you always delete your structorizer.ini before you test a new Structorizer version?

**Comment by codemanyak** [comment]
Just follow the recommendation (replace the "???") and you will see...

**Comment by codemanyak** [comment]
@reks99 
> Of course I delete the ini-File

I usually don't unless I want explicitly test how Structorizer "bootstraps". I would have thought that most people adhere to their settings... (But well, then you wouldn't even have seen the welcome message.)

**Comment by reks99** [comment]
Hi Kay,

my first program ;) runs.
Fine regards
Rolf

**Comment by GitMensch** [comment]
@reks99 Do you have a suggestion for making the "tour" more clear to the user? Any message / note that could be improved?

**Comment by reks99** [comment]
Hi,

> Do you have a suggestion for making the "tour" more clear to the user? Any message / note that could be improved?

It would be fine, if the text is more elaborated and can be shown in a separate (none modal) window

But I'f got a better idea just to make more tutorials possible - outside of structorizer.

First of all an API to structurizer which offers (at least) three informations is needed. These are:

- an element-ID (for uniqe identification of the element)
- the type of the element and
- the content of the command-field.
optionally an information about deleted element.

So an external tool can control where the tutorial user is and check if he/she did it right. It might be enough if always the information of the current element will be send perhäps if something changed (modification or selection of an element).

Ideas for the API are:
- In Unix-environments it could be an UNIX-socket or
- a networked server with an absolutly minimal protocol (three or four 2 letter commands) or
- an output via stderr that can be catched by the external tool. 
The data might be separated by colon or tab or the first two have fixed length

Hope this can be realised and give you ideas for enhancements

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
First of all: Thanks for your ideas and proposals. Though the idea isn't quite clear for me.

> It would be fine, if the text is more elaborated and can be shown in a separate (none modal) window

What would be more elaborated? Could you please give an example? Why would a separate window be better?

> So an external tool can control where the tutorial user is and check if he/she did it right.

Hardly. To be able to do this the entire diagram tree would heve to be accessible. Otherwise the element id doesn't help in any way.

> It might be enough if always the information of the current element will be sent perhaps if something changed (modification or selection of an element).

If the user inserts a new element, you would not only need the information about the new element but also about the "Subqueue" (this is the element class representing an Element sequence) it was added to and at what position. The Subqueue id in turn doesn't help while you don't know where it resides. So if a compound element, say a Case element is inserted you must also know the number and ids of all its branches (for later identification of insertions, deletions, movements etc.).
This way you will have to program a complete external tracking of all activitis within the diagram.  All this only in order to find out what happens.
The external logic needed for consistency checks, variable checking etc. would have to be reeinvented (though Analyser already incorporates it).

The user's attention would have to switch among the external tutorial tool, the Structorizer, the Analyser report and the more or less elaborated remarks emerging from the external tool. Do you rally think that makes sense?

> Ideas for the API are:
> -    In Unix-environments it could be an UNIX-socket or
> -    a networked server with an absolutly minimal protocol (three or four 2 letter commands) or
>-    an output via stderr that can be catched by the external tool. The data might be separated by colon or tab or the first two have fixed length

This would mean that for sevaral OS and environments different tools would have to be realised, servers to be hosted, the standard error stream to be redirected etc. And you could still not even control Structorizer, would only try to interpret and reflect what happened. I'm not sure how this perspective should convince me that it's easier, better and more portable than a built-in engine based on the existing mechanisms and able to use them intrinsicly.

So I would like you first to give a rough scenario how such a tutorial could look like (independently of its technical implementation) before I start to frickle some vague APIs or interfaces. Maybe some good example for another tool? I'm looking forward to your inspiring elucidation that could motivate me to go in that direction.

**Comment by codemanyak** [comment]
@reks99 
Just an additional technical remark: The element id may change on undoing or redoing something because in this case the diagram is replaced by a copy from the undo or redo stack.

**Comment by reks99** [comment]
Hi Kay,

> What would be more elaborated? Could you please give an example? Why would a separate window be better?

Let's say the tutorial get more attention - as you noticed even me has to ask three times to follow the tutorial.

> Hardly. To be able to do this the entire diagram tree would have to be accessible or trackable. Otherwise the element id doesn't help in any way.
Not in my opinion. I think the actions (select an element, edit the command) itself give (i.e.print out) the information without request, when the tutorial flag is set. No further data requiered. By checking the content of the command text, the tool can see, if there was a correct (or better the wanted) input.

> The user's attention would have to switch among the external tutorial tool, the Structorizer, the Analyser report and the more or less elaborated remarks emerging from the external tool. Do you really think that makes sense?

My proposal should/could help to build **simple** tutorials or can become a test environment, for a more featured API or to cancle this external possibility.

> This would mean that for sevaral OS and environments different tools would have to be realised, servers to be hosted, the standard error stream to be redirected etc.

No! The best in my mind would be a small tcp/ip server bound to localhost but it is a litle bit more complex then just print out the wanted information (perhaps via stderr). This will work in every OS.

> So I would like you first to give a rough scenario how such a tutorial could look like (independently of its technical implementation) before I start to frickle some vague APIs or interfaces. Maybe some good example for another tool? I'm looking forward to your inspiring elucidation that could motivate me to go in that direction.

The (external) tool tells what to do - as your tutorial do also - and check via the response of structurizer, if the pupile did as told. The tool (or better the tutorial programmer) itself can handle difference. Then the next to do action is told until end of tutorial.
It is a pitty, that the element id changes then I thought, that a back reference can be given in the tutorial - NO INTERACTION WITH Structorizer here (perhaps for now).

I hope my idea become more clean.
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
Thanks again, but this time it's me who needs more advice.

> The given texts shoud be more elaborate

So you told me. I asked for an example, e.g. how would you formulate the texts for the "Hello world" example to be more insructive? Maybe they should occupy more space than just a single line? On the other hand it's no bad idea to be as concise as possible...

> and with a separate window the tutorial get more attention - as you noticed even me has to ask three times to follow the tutorial.

Okay. Point taken. An initial message window (possibly with an augmented screenshot) might push the pupil with the nose on the Analyser text field - or wherever the steering advice would appear in future. (My idea with the Analyser integration was that this way the tutorial is not forced to have a reaction for any possible mistake because the regular Analyser reports organically fill the gaps and already tell the user what problems arise even if he leaves the track of the tutorial. The user gets accustomed to watch the Analyser helping him. My perspective may of course be wrong. Possibly I'm already too close to Structorizer and its behavioral oddities for newbies.)

>  I think the actions (select an element, edit the command) itself give (i.e.print out) the information without request, when the tutorial flag is set. No further data/interaction requiered. By checking the content of the command text, the tool can see, if there was a correct (or better the wanted) input.

A tutorial could also advise to open a given sample diagram and to move or transmute elements there, to do some execution with run data tracking, to push it to the Arranger, to outsource a routine etc. How would you like to inform an external tool about what's going on and which mistakes the pupil might make with just the ID and the text of the currently selected element? I simply can't imagine that. It would even be difficult within Structorizer, but at least feasible.
With one aspect yo are right: The number of possible built-in tutorials will always be very limited and rather fix. With an external API you could create an infinite number of tutorials of any kind for any purpose.
The simplest way would be to work without any technical feedback at all: Just a very detailed descriptin of steps to go in the/a user guide.
From that ground, a little (though poor and insufficient) information from Structorizer would be more than nothing and could help adaptively to react (a little).
More information would allow for more reactivity but this of course complicates the guiding algorithms if they want to make intelligent use of the "big data".

By the way, the stderr channel shpld be reserved for error logs, not be messed up with general logging. The standard output is hardly better. Via both streams several there emerge already several debug information and even stacktraces under certain conditions. Specifically coded information could of course be filtered out, but I'm not quite happy with all these perspectives.

I will ponder this some while. Maybe that other users will also come forward with some proposals or feedback.
So for now I will reopen this issue and label with "nice to have".

**Comment by reks99** [comment]
Hi Kay,

> So you told me. I asked for an example, e.g. how would you formulate the texts for the "Hello world" example to be more insructive? Maybe they should occupy more space than just a single line? On the other hand it's no bad idea to be as concise as possible...

For example: when the tour is selected (either in the first greeting or in the preferences menu) there need to be written (best in a small pop up), that the instructions for the tour are given in the bottom window (a newbee don't know, that it is the "Analyser report array") and keep in mind "nur Weicheier lesen Handbücher".

> A tutorial could also advise to open a given sample diagram and to move or transmute elements there, to do some execution with run data tracking, to push it to the Arranger, to outsource a routine etc. How would you like to inform an external tool about what's going on and which mistakes the pupil might make with just the ID and the text of the currently selected element? I simply can't imagine that. It would even be difficult within Structorizer, but at least feasible.

Perhaps we/you should distinguish between a tutorial to learn structurizer from a tutorial to learn PROGRAMING with strutorizer. My focus is more the second - even while I think that it is really complex to modifiy structurizer for complete remote-control.

> By the way, the stderr channel shpld be reserved for error logs, not be messed up with general logging. The standard output is hardly better. Via both streams several there emerge already several debug information and even stacktraces under certain conditions. Specifically coded information could of course be filtered out, but I'm not quite happy with all these perspectives.

The use of stderr is up to the programmer. I prefer to report errors to a log system or an own logfile. Then stderr could be used for something different (as you can see in the startscript, that java gives its version info on stderr). Also a lot of programs give its --help or usage message via stderr.

> I will ponder this some while. Maybe that other users will also come forward with some proposals or feedback. 
So for now I will reopen this issue and label with "nice to have".

Of course its nice to have such a feature, but it could be hard work (perhaps a big reorganisation of the program) and the proposel was just as you asked.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> Of course its nice to have such a feature, but it could be hard work (perhaps a big reorganisation of the program) and the proposal was just as you asked.

You are right. Well, it was actually Simon who asked in the first place, but I'm grateful he did. And I also thank you for your ideas and perspectives. And indeed I should set up a sensible file logging instead of simply messing up the stderr stream where the messages usually get lost.

**Comment by reks99** [comment]
Hi Kay,

two additional notes:

First: Another comunication chanel (at least in UNIX-evironment and perhaps the MAC) are named pipes which are FIFOs where on program writes into and another program can read.

Second: As next a tutorial about the Strucuritzer syntax (aka HLL) might be helpful not only for newbees.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> First: Another communication chanel (at least in UNIX-evironment and perhaps the MAC) are named pipes which are FIFOs where one program writes into and another program can read.

UNIX, Windows, and Mac all know named pipes but their handling and whereabouts differ. It needs a so-called native interface in Java to access them. Particularly difficult is the creation of named pipes from Java. In addition, the respective thread would block until some other process reads from the pipe. Thus the costs tend to be high.

> Second: As next a tutorial about the Structorizer syntax (aka HLL) might be helpful not only for newbies.

Do I read some mocking here? No, earnestly: I will keep this proposal in mind.

**Comment by codemanyak** [comment]
@reks99 
> For example: when the tour is selected (either in the first greeting or in the preferences menu) there need to be written (best in a small pop up), that the instructions for the tour are given in the bottom window

Implemented in version 3.27-03. The next version will come with another popup when one tutorial is exhausted and the next begins.

**Comment by codemanyak** [comment]
> Implemented in version 3.27-03. The next version will come with another popup when one tutorial is exhausted and the next begins.

Due to a file placement mistake the dialog drawing the attention to the Analyser report panel isn't rendered. This will be fixed in version 3.27-04.

**Comment by GitMensch** [comment]
This ticket can likely be closed or do we need a full 3.28 release before (3.27-04 is not found in the releases)?

**Comment by codemanyak** [comment]
Some suggestions of the issue originator (Rolf) haven't been addressed yet. So I'd like to wait for an OK from Rolf here.

**Comment by reks99** [comment]
Hi,
As I wrote the suggestions have been an answer of a question from Simon and I thougt that they can be, but need not to be implemented. So you can do with my ideas what you want - i.e. close the ticket.

Fine regards
Rolf

**Comment by codemanyak** [comment]
So okay, I'll close it for now but keep the error logging in mind.
