### ISSUE TITLE
Structorizer for Java 1.7

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#463]
@fesch 
Hi Bob,

is it possible to get latest Structurizer compiled for Java 1.7? Reason: With java 1.8 in a 32-bit virtual machine the VM will be killed immediatly after starting Structorizer - and so I can't find any error reports.

Fine regards
Rolf

**Comment by codemanyak** [comment]
This would be VERY inconvenient because at least the public DiagramController interface now relies on Java 8 default methods.
As discussed on behalf of issue #459, I'd rather redirect the error messages to a log file than downgrade to an obsolete Java SE version, now since OpenJDK is available in versions 8 and even 9.

**Comment by reks99** [comment]
Hi Kay,

when you write all the error messages into a file, be shure, you allways open the file for append and close it suddenly, when message has been written. So the log file may has the data, even wenn the VM crashes.

Fine regards
Rolf

**Comment by fesch** [comment]
It has been compiled with Java 8 with Java 8 as destination format too.

Will try to get a 32 bit VM to test later ...

**Comment by codemanyak** [comment]
I made a first approach to convert all messages written to standard output and standard error into logging actvities via the SLF4J Façade (based on the java.util.logging modules). But after having realised that the configuration is not handled by the SLF4J package but must be done in the underlying framework, I tend to kick the SLF4J packages out again and reimplement the logging directly in the J.U.L. API.

**Comment by codemanyak** [comment]
The log configuration mechanism delivered with version 3.28-02 doesn't work for Java WebStart, not even if the logging.properties file is placed in the webstart location of the Homepage - simply because Structorizer isn't aware that it might be a web-based resource.
So the mechanism to provide the logging configuration will be re-implemented as follows:
- The default logging.properties file for Structorizer is no longer placed in the Structorizer.app/Contents/Java folder of the downloadable product but provided as resource in package lu.fisch.structorizer.
- On starting up, Structorizer checks, whether there is a "logging.properties" file in the ini directory (subfolder `.structorizer` of the user's home directory). If not then the default configuration will be copied from the resource to that ini directory.
- If the file "logging.properties" is now found in the ini directory then its path will specified as system property "java.util.logging.config.file" and the LogManager instance will be forced to read the configuration.

This way, the user may modify the configuration in .structorizer, and te user-specific configuration will be preserved until the user renames or removes it. This mechanism should also work for Java WebStart.
The update will be delivered with version 3.28-03.

**Comment by fesch** [comment]
A Java app started by JWS is aware of this, meaning that this can be tested. I've created even something very perverted: a JWS app that, if it detects that it is being started by JWS, it restarts itself with the local JRE ;)

Just saying...

**Comment by codemanyak** [comment]
@reks99 
You requested:
> when you write all the error messages into a file, be sure you always open the file for append and close it suddenly, when message has been written. So the log file may stay, even wenn the VM crashes.

Unfortunately, the standard logging mechanism of Java doesn't work this way. Instead it buffers, and flushes rather sporadically. Yet I prefer to adhere to the J.U.L. rather than writing a proprietary mechanism.

**Comment by codemanyak** [comment]
@reks99 
Is this issue still relevant?

**Comment by fesch** [comment]
@reks99 
I close the present issue. If it is still relevant to you, please let me know, so I'll reopen it.

**Comment by GitMensch** [comment]
@codemanyak you may want to reinvestigate part of this:

~~~
java.io.FileNotFoundException: /home/appveyor/.structorizer/Structorizer.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:276)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:220)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:170)
	at Structorizer.main(Structorizer.java:135)
~~~

**Comment by codemanyak** [comment]
@GitMensch 
Oops, how embarrassing! This has nothing to do with Java 7 but with my incompetence... Opened an new issue for it: #603
