### ISSUE TITLE
NEWS: Structorizer on OpenHub

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#464]
https://www.openhub.net/p/structorizer

Bob/Kay, you may want to claim your contributor IDs at https://www.openhub.net/p/structorizer/contributors/summary.

Bob may want to add some of the [Widgets](https://www.openhub.net/p/structorizer/widgets) somewhere (for example to the website).

If possible at all I'd like to see either Bob or Kay maintaining the project there (mostly means changing the settings if needed, but also be directly visible as Maintainer).

**Comment by codemanyak** [comment]
> If possible at all I'd like to see either Bob or Kay maintaining the project there

What would that mean exactly? If I understand this OpenHub well, then the maintenance of the code continues to be performed in its original repository. OpenHub only analyses and reports it, right? So what is to be maintained in OpenHub? What consequences does it have to be signed in or to have claimed one's contributor ID? I've read (and listened to) a lot of advertisement but no clear balance of advantages (if any) or even effects against risks and drawbacks.
Does maintenance of the project mean e.g. the correction of the spelling of "Shneiderman" (instead of "Schneidermann") in the tags or somehow to deny that the the DSN projects NSD and Unbound have anything to do with Structorizer. That kind of things?

**Comment by GitMensch** [comment]
Claiming a contributor ID mainly means to possibly group your contributions to all projects listed on OpenHub and ensure that no other person claims your id.

Maintaining the project there means more or less be able to change anything that is in there and not calculated (like the commits or "similar projects" [which get calculated from the tags you choose]), for example tags, links, descriptions, code repositories, ...

**Comment by GitMensch** [comment]
> the correction of the spelling of "Shneiderman"

Actually it is spelled wrong in the GitHub description above :-)

**Comment by codemanyak** [comment]
This is a misunderstanding. "Shneiderman" is the correct spelling. The tag in OpenHub is misspelled.

**Comment by codemanyak** [comment]
> Claiming a contributor ID mainly means to possibly group your contributions to all projects listed on OpenHub and ensure that no other person claims your id.

Okay, I'm scanning the Terms of Use.

**Comment by GitMensch** [comment]
Don't fell any pressure (other than fixing the GitHub description, but this is likely something @fesch has to do).

**Comment by codemanyak** [comment]
> ... fixing the GitHub description ...

Oh sure. I thought you referred to the README.md.

**Comment by GitMensch** [comment]
:-) so everything is fine, both here and on the homepage now.

Concerning the "related" projects on OpenHUB - it got a little bit better when removing the "nsd" tag and even better when adding the "not that good matching" tag "flowchart".

**Comment by codemanyak** [comment]
Having spent a little time in OpenHub now, I really appreciate your initiative.

**Comment by GitMensch** [comment]
You're welcome. Can you request management for the project at https://www.openhub.net/p/structorizer/managers?

**Comment by GitMensch** [comment]
The URL and / or [widgets](https://www.openhub.net/p/structorizer/widgets) may be added to the documentation somewhere (and @fesch *could* consider using this site to prevent others claiming his commits).
Otherwise than this everything is done here and the issue can be closed.

**Comment by fesch** [comment]
small widget added at the left bottom under the menu

**Comment by codemanyak** [comment]
This OpenHub sucks. It had failed to update the code locations for over five months now, such that the regularly done analysis (on old code!) reports continuously decreasing project activity. An attempt to remove the code location in order to force an update by re-adding failed, too. That is, removal worked but new registration is constantly averted (telling that the location ist already registered with project, though it is definitely gone).
I just read in the OpenHub forum that problems with the location updates and additions have occurred and been reported for years now.
