### ISSUE TITLE
Code import (COBOL) - Shouldn't LINKAGE SECTION items be stored in an includable diagram?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#473]
The auto-creation of an "includeable diagram" "_shared" for working-storage items works fine. But for LINKAGE not.

[printrunreport.cbl](https://github.com/fesch/Structorizer.Desktop/files/1505656/printrunreport.cbl.txt)

leads to an unknown type:

![grafik](https://user-images.githubusercontent.com/6699539/33264800-591978ac-d36f-11e7-81eb-5e588a1af5a9.png)

and unknown variables:

![grafik](https://user-images.githubusercontent.com/6699539/33264840-7813633a-d36f-11e7-8199-f217ae256ffd.png)

As this actually works for multi-program sources I assume something is missing (but I couldn't find it).

This is also the reason (or at least the first issue) that the worldcities3 sample doesn't work after adding the "external" program (nsd generated from separate source file) to the arranger.

For completeness the generated NSDs:
[worldcities3.arrz](https://github.com/fesch/Structorizer.Desktop/files/1505665/worldcities3.arrz.zip)

**Comment by codemanyak** [comment]
First approach to cope with LINKAGE sections committed to bugfix branch.

**Comment by codemanyak** [comment]
A real problem arises due to the lacking type concept in COBOL, e.g. on importing sample file cgiform.cob, the calls of routine COB2CGI_POST operate with three different types for the result value:
![cgiform_part](https://user-images.githubusercontent.com/15326471/33584706-e51826b8-d960-11e7-8554-99c592ea4a0c.png)
Figure 1: The two calls of COB2CGI_POST

![cob2cgi_post-1_part](https://user-images.githubusercontent.com/15326471/33584728-fc5424f8-d960-11e7-8a49-1ef58721e675.png)
Figure 2: The header of routine diagram COB2CGI_POST

![cob2cgi_post_argtypes](https://user-images.githubusercontent.com/15326471/33584776-39b4a11a-d961-11e7-9971-f15b3e132390.png)
Figure 3: The result type definition (from LINKAGE section) in an includable diagram

![cgiform_shared_part2](https://user-images.githubusercontent.com/15326471/33584829-856b712e-d961-11e7-875b-38155111fa74.png)
![cgiform_shared_part](https://user-images.githubusercontent.com/15326471/33584837-8f2b724a-d961-11e7-91e4-5ffc9a6d686a.png)
Figure 4, 5: The definitions of the target variables and their types

So, structurally the three types are congruent, but formally not identical. So the resulting diagram set is semantically broken.

**Comment by codemanyak** [comment]
Perhaps a postprocessing might clean this chaos a little by analysing assignment relations and unifying the involved record types.
