### ISSUE TITLE
FR: Code import from clip-board / manual insert

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#474]
The idea is to add a minimal Dialog with a text field and a pull-down for the language selection.
This way "complicated" code parts may be changed to a diagram and can be analyzed / tweaked from there.

Especially with big sources this may be a much faster approach than parsing the complete file (which may aborts because of syntax errors and result in multiple big NSDs) and would be much faster and nicer than the current workaround (creating an additional file with the file-prefix matching Structorizer's language mapper, import this, delete this afterwards).

**Comment by codemanyak** [comment]
@GitMensch 
We may do so, though I doubt the "much" in:

> would be much faster and nicer than the current workaround (creating an additional file with the file-prefix matching Structorizer's language mapper, import this, delete this afterwards)

because using an external good editor with syntax support (e.g. Notepad++ or Emacs) and manipulating the code snippet (extracted to a file of the appropriate extension) there is more convenient and sustainable in my eyes. (This is what I used to do with COBOL or other sources on import testing, I wouldn't have liked to do so in a dull text area of Structorizer instead.) But well people's preferences are different, of course.

**Comment by codemanyak** [comment]
Closed as requested in #607
