### ISSUE TITLE
Multi-line expressions are always indented 

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#481]
![grafik](https://user-images.githubusercontent.com/6699539/33549257-34fd209c-d8ea-11e7-8fca-c3271d5377d0.png)

leads to

![grafik](https://user-images.githubusercontent.com/6699539/33549190-f8638c16-d8e9-11e7-800b-ade328c52d63.png)

[Multi-line_expression_sample.nsd.txt](https://github.com/fesch/Structorizer.Desktop/files/1526722/Multi-line_expression_sample.nsd.txt)

Especially when the expression is more complex / longer this looks quite strange.

Not sure if this has anything to do with the following quote from @codemanyak in #416
> The draw method might force some minimum indentation for consecutive lines if the continuation lines don't already start indented.

Is it possible to keep the indentation in expressions, too?

**Comment by codemanyak** [comment]
You are right, in instructions the consecutive lines are automatically indented. I will have a look if a existing indentation can be respected.
In Alternatives and CASE elements, however, it's different. Not only the backslashes are hidden (since the text is used in concatenated form anyway), but each line is centred (or right-bound in CASE elemets without default branch) accordig to the triangular header shape, otherwise the element would extend unnecessarily.

**Comment by codemanyak** [comment]
@GitMensch 
I had a look to the indentation mechanism, and indeed: any existing indentation that exceeds the configured  minimum indentation for continuation lines (= 4 spaces) will be preserved in multi-line instructions.
I think this should be okay, shouldn't it?

**Comment by GitMensch** [comment]
@codemanyak It seems we didn't understand each other. Given an indent of 5 spaces:

![grafik](https://user-images.githubusercontent.com/6699539/33659076-317b025e-da7f-11e7-8b21-d23a8606b698.png)

leads to

![grafik](https://user-images.githubusercontent.com/6699539/33659093-3a543508-da7f-11e7-8b4a-1e3b5180ec3f.png)

I've expected something like

![grafik](https://user-images.githubusercontent.com/6699539/33659154-7ade5e50-da7f-11e7-931a-e71a0d28f3aa.png)

Side note: Where is the magical number "4" set-up? It would be clean to have it in the Structure Preferences in a new option "General -> Minimum manual indentation", " similar to "CASE statement -> Min. branches for rotation":

![grafik](https://user-images.githubusercontent.com/6699539/33659253-c88fc9b8-da7f-11e7-96e4-616ee5eb4efe.png)

**Comment by codemanyak** [comment]
@GitMensch 
> It seems we didn't understand each other. Given an indent of 5 spaces [...]

Obviously not. Once more: In Alternative and CASE headers, there is no indentation control but the lines are centred within the triangular shape in order to optimize element width (at least in general).

The indentation applies Instruction elements where normally each line would comprise an entire statement. The indentation depth of 4 was an empirical value, being sufficiently noticeable on the one hand and not expanding the element too much.

> Where is the magical number "4" set-up? It would be clean to have it in the Structure Preferences in a new option "General -> Minimum manual indentation"

You are right from a theoretica point of view. But an inflationary number of configuration trifles makes using of such a tool by no means easier for newbies. (In contrast, the setting for the CASE branch rotation had tremendous impact.)
