### ISSUE TITLE
COBOL import: constants should be imported to upper-case

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#482]
The current import leads to a warning message:

> The variable <<imported_varname>> must be written in uppercase!

As using constants in all caps is a good idea (this would be good to do on import (where we actually lower-case any variable...)

**Comment by codemanyak** [comment]
Structorizer doesn't make a difference in name style between constantes and variables.
What possibly might be done is that the Analyser check status requesting upper case variable and diagram names (a LUX/MEN preference) be used to decide whether all respective names are to be converted to upper-case. But then we would have to do this for all import languages, which may cause trouble with languages that distinguish case and may use different names only differing in case. (And what about the Analyser rule that argument names be capitalized and prefixed with a lower-case p?) So I decided better not to do any code-style-driven name manipulations.
If it's to be a specific import option for COBOL, so we might of course decide otherwise (e.g. you had already converted all names to lower-case). Of course it might also be the default to capitalize constant names on COBOL import if you like.

**Comment by GitMensch** [comment]
It seems that code import should convert to whatever the Analyzer is expecting (which seems to be upper-case) and the code export should convert to whatever the language is expecting (which is for java: lower-case if not a constant, for COBOL and BASIC it doesn't make a different and should be an export setting, Shell: upper-case [as lower-case will result in calling builtin-functions like in `test var`], ...)

What is the reason that the Analyzer warns about lower-case names?

**Comment by codemanyak** [comment]
> What is the reason that the Analyzer warns about lower-case names?

This is a naming convention used in Luxembourgish schools. The respective Analyzer checks (marked with "LUX/MEN") are no longer enabled by default (since version 3.27-02, I think):
![preferences_analyser_window3 27-04b](https://user-images.githubusercontent.com/15326471/33555050-381c0d82-d8ff-11e7-9dfc-3fd8fc5cd26d.png)

> It seems that code import should convert to whatever the Analyzer is expecting (which seems to be upper-case)

... only if this option is enabled (see above).

> the code export should convert to whatever the language is expecting (which is for java: lower-case if not a constant

No, Java doesn't expect anything. It's a mere code style convention. And CamelCase is even more usual, where the case of the initial letter depends on the kind of identifier etc. etc.

No, actually I wouldn't meddle with naming conventions unless it's syntactically necessary (like substituting hyphens with underscores on COBOL import or prefixing variables with '$' on shell or Perl export). I think it's better that the user recognizes his/her identifiers after an import or export.
Of course, there might be an import preference to regard e.g. the current status of the current LUX/MEN Analyser settings, which would be dangerous or even a No-Go in case of C or Java, however. And so we better leave it in general. And it would not mean to convert to lower-case while the Analyzer checks are off!

**Comment by GitMensch** [comment]
Agreed (locally changed property according to your screenshot) - no conversion for now, maybe recreate a new one later about "change variable/program/sub-names" to uppercase according to LUX options.

The warning does not occur, not (directly) COBOL import related, closed.
