### ISSUE TITLE
NULL / null => uninitialized variable?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#488]
After code import (in this case from C) I was prompted with a lot of warnings

> The variable >>NULL<< has not yet been initialized!"

Changing this to Java "null" leads to 

> The variable >>null<< has not yet been initialized!

Is there any option to support this somehow? If this is already handled internally than this should be considered an Analyzer bug.

**Comment by codemanyak** [comment]
I am sorry.
If an evaluation returns null then this is regarded as an evaluation error in Executor. This is the way Structorizer works with the BeanShellInterpreter. Neither buiilt-in NULL nor null are supported in Structorizer as aren't pointers.
To define a ordinary variable "NULL" is possible. The use of "null" as a variable, however, raises other warnings and causes an error on execution: 
![null_error](https://user-images.githubusercontent.com/15326471/33662505-458dfeba-da8c-11e7-984d-001c79fcb76c.png)

I don't think I will do anything about it.
For documentation purposes you may put whatever you like in the element texts. Just ignore the warnings or switch Analyser off. For an executable diagram there is a limitation here.

**Comment by codemanyak** [comment]
If you want to have an unset variable then just declare it without initializing it.

**Comment by codemanyak** [comment]
Hm. If we handle "NULL" (C) and "null" (Java) specifically, then we might as well have to build in something for "nullptr" (C++), "NIL" (Pascal), "undef" (Perl) etc. pp.? See the problem?
I understand that you want some literal for undefined values. But this doesn't make much sense unless we introduce the concept of pointers or explicit references as well.
The first sentence of your proposed warning text is essentially the same as the existing one, whereas the second sentence teaches an unskilled user to produce unset variables, while we better should suggest her/him the opposite.
Of course, on code import there is a gap we can't fill. Actually, it's by far not the only one. As is with function pointers, variable redefinitions, and unions, for instance. Or BCD arithmetics. We will have to live with such limitations. Some half-boiled workaround won't make you happy, either, I'm sure.
(Remember the record type scenario: We spent a lot of efforts to enable this concept, and now you want an option to switch it all off in order to return to the initial situation because of the heavy declaration stuff. Don't let me be mis-understood: I don't complain, I don't regret the enhancement but it made the formerly simple tool a lot more complicated, and we will never ever overcome all limitations.)

**Comment by codemanyak** [comment]
Won't do anything about this issue.
