### ISSUE TITLE
Structorizer 3.28 does not generate Pascal code for record

### ISSUE THREAD

**Issue by desmethans** [fesch/Structorizer.Desktop#520]
Structorizer 3.26 generates correct Pascal code for the definition of a record.
Structorizer 3.28 does not generate Pascal code at alle for the definition of a record.

[example.zip](https://github.com/fesch/Structorizer.Desktop/files/1802369/example.zip)

**Comment by codemanyak** [comment]
Well, before version 3.27, there was no specific support fpr record types such that an element containing lines like 
![pseudorecord](https://user-images.githubusercontent.com/15326471/37292066-5f46eacc-2610-11e8-8968-92934ecefa44.png)
might just have passed them unchanged to the target code.
When we introduced specific support for record / struct types, a supported syntax was defined that is a mixture of Pascal and C. If you adhere to this syntax described in the [User Guide](http://help.structorizer.fisch.lu/index.php?menu=130&page=#record_support), you will be enabled both to execute and to export it.
I modified your example accordingly such that the type definition will be expressed in a correct way on export (not only for Pascal!):
![schrijfbestand_3_28](https://user-images.githubusercontent.com/15326471/37293013-75791124-2612-11e8-92db-fefd0f644a85.png)
The backslashes are only used to break the lines without actually splitting the definition into several instruction lines, you could write it in a single line as well:
```
type personeel = record{ nr: integer; name: string }
```

(But on this occasion I realised another bug regarding the treatment of the variable declarations, possibly an unwanted side effect of another recent bugfix.)

**Comment by codemanyak** [comment]
@desmethans 
Yet if you happen to have selected the export option "no conversion of the expression/instruction contents" (see screenshot) then it might indeed be seen as a bug that a type definition conversion is tried at all.
![export_option_520](https://user-images.githubusercontent.com/15326471/37316586-4403c87a-2660-11e8-83c1-f9c4e1a307bf.png)

**Comment by codemanyak** [comment]
@desmethans 
Just a comment: Of course you know that the exported file you may have obtained from your diagram with previous versions of Structorizer (e.g. 3.26) cannot have been correct Pascal code (neither in mode "No conversion ..." nor in normal export mode) because the type definitions and var declarations would have occurred inside the program body, contained syntactically misplaced semicolons and multiple keywords VAR etc.
With 3.28 and its successor version you may produce more correct code in normal export mode, provided you adhere to the speific syntactic restrictions described in the User Guide.
Nevertheless, I am working on the "No conversion ..." mode to reduce the unwanted impacts of the introduction of the new syntactic features. Such that the outcome in "No conversion ..." mode will be the same in version 3.28-01 as had been before 3.28 (cf. #521).
