### ISSUE TITLE
Output concatination with "string" + var + "string" exported wrong to C++

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#54]
The export is:
std::cout << "string"  + 5 + "string" << std::endl;
and should be:
std::cout << "string" << 5 << "string" << std::endl;

**Comment by codemanyak** [comment]
We know. For the time being, some manual post-processing will remain necessary - as has always been with the exported code.
The specific difficulty here is that you can't just replace all '+' operators by '<<' operators because some of them might really mean an addition like in:
Ausgabe 5 + 7
This would require some reverse interpretation of Java syntax.
The better solution seems to be to allow comma-separated lists of expressions after an output keyword. In this case, it will be definitely easier to convert the top-level commas (not those in parameter lists of called functions, of course) into the correct mechanisms for the target language or the executor. Actually, the use of the Java concatenation operator has only been a handy workaround for the lacking possibility to accumulate several expressions within a single output instruction.
Actually, it was just yesterday when Bob and me agreed that this would be the recommenable way to handle it.
I'm working on it.

**Comment by codemanyak** [comment]
Tasks to accomplish:
[x] Executor 
[ ] C generator and descendants (C++, C#, Java)
[ ] Pascal generator
[ ] Oberon generator
[ ] Basic generator
[ ] Shell generators (KSH, BASH)
[ ] Perl generator
[ ] Tex generator
[ ] PHP generator
[ ] Python generator
[ ] integrate in new release

**Comment by codemanyak** [comment]
Basic: PRINT instruction copes with separator ',' but it should better be converted to ';' lest tabulation should be induced.

**Comment by codemanyak** [comment]
Basic Generator: PRINT now gets ';' as separator.

**Comment by elemhsb** [comment]
Year, i will test it ...

**Comment by codemanyak** [comment]
The Oberon result looks ugly and still requires manual postprocessing (typed Out methods). But this will never be possible to avoid completely. It should not be forgotten that most of the translation is guessing from undefined and ambiguous syntax.
