### ISSUE TITLE
Create de Debian package for simple deplyoment

### ISSUE THREAD

**Issue by fesch** [fesch/Structorizer.Desktop#585]
As suggested by @KimBrodowski  ...

**Comment by fesch** [comment]
If anyone want's to test what I did, here's the link to some deb file:

https://www.fisch.lu/Php/download.php?file=structorizer.deb

PLEASE BE AWARE THAT I DID NOT YET TEST THIS MYSELF AND THAT THIS FILE MIGHT KILL OR DESTROY YOUR SYSTEM. PLEASE USE A VIRTUAL MACHINE TO TEST WHERE YOU CAN RESTORE YOUR PREVIOUS STATE.

I will do some testing as soon as I can, but maybe some of you are faster ...

**Comment by KimBrodowski** [comment]
Haven't installed it yet, but took a quick look at the contents. This is by no means a complete list, just a couple of important bits. All-in-all I'd assume it's usable though.

The `Description` field should be two lines. The first is the title followed by one or more line with a long description. Those are indented by one space.

`Priority: optional` is missing.

The `Version` field should not contain hyphens. Technically this is allowed by Debian Policy for native packages, but may cause issues down the line. 

Dependencies are missing. Since this package is supposedly aimed at both Ubuntu and Debian I'd have to look up how to declare those for best compatibility.

There are a couple of more things I'm not going into here (e.g. missing a Debian-style changelog etc.).

**Comment by fesch** [comment]
Okay, the file has now been tested by myself and seams to work using 
`dpkg -i structorizer.deb`

If no Java is installed, you have to launch this command to download and install dependencies:
`apt-get -f install`

**Comment by fesch** [comment]
Okay, we are getting closer. I still get some warnings, but I think some of them can be ignored ;)

`W: structorizer: wrong-name-for-changelog-of-native-package usr/share/doc/structorizer/changelog.Debian.gz
W: structorizer: extra-license-file usr/share/structorizer/license.txt
W: structorizer: unknown-java-class-version usr/share/structorizer/Structorizer.app/Contents/Java/Structorizer.jar (Structorizer$1.class -> 52)
W: structorizer: binary-without-manpage usr/bin/arranger`

**Comment by speedy-10** [comment]
Hi, I tested on 18.04 and it worked, if I disable the line in.
{{{sudo vim /etc/java-11-openjdk/accessibility.properties}}}
Thanks.

**Comment by fesch** [comment]
Link has bee integrated onto homepage

**Comment by fesch** [comment]
Two more to go ;)

```
W: structorizer: wrong-name-for-changelog-of-native-package usr/share/doc/structorizer/changelog.Debian.gz
W: structorizer: binary-without-manpage usr/bin/arranger
```
