### ISSUE TITLE
Java 8+ raises unchecked warning

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#594]
Nothing of priority, I've just noticed this in https://github.com/fesch/Structorizer.Desktop/issues/537#issuecomment-418258560 and rechecked:

javac says:
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.

Doing so results in 58 Warnings: [Xlint_unchecked.log](https://github.com/fesch/Structorizer.Desktop/files/2388206/Xlint_unchecked.log)

**Comment by codemanyak** [comment]
More than two thirds of the warnings are generated by the stevesoft Regex package.
According to a benchmark this is one of the slowest regex libraries anyway and all links I found for it (in order to see whether there might be an updated version) seem to have gone stale.
So we might certainly replace the remaining references with java.util.regex equivalents and kick that library out.
Since java.util.regex isn't the most performant library either (but still at least twice as performant), we might consider to use another, more performant free library instead, but that's optional.
For the executor warnings it get's tricky to overcome than (except by switching off the warnings - I had tried). I will have a look into the goldengine warnings. Maybe there it's similar, maybe not.

**Comment by GitMensch** [comment]
Sounds good. Note: regex in COBOLParser was done with java.util.regex and the performance increase by creating the Pattern/Matcher only once was recognizable (even on a "modern" system). I suggest to watch out for this when changing the Regex package.
And If performance is not a real problem in those places I'd prefer to stay with "less dependencies" and also assume that java.util.regex is getting even more robust and increases performance over time (at least more than most third-party libraries).

**Comment by codemanyak** [comment]
All raw types in GOLDParser qualified for type inference - warnings there should now be gone. So only the tricky cases in Executor remain where I might have a look at most recent BeanShellInterpreter [release 2.0b6]( https://github.com/beanshell/beanshell/releases) from the beanshell project on GitHub.

**Comment by codemanyak** [comment]
Replacing bsh-2.0b4.jar with bsh-2.0b6.jar works fine but doesn't solve the problem with Executor: There are some casts to do (e.g. from `Object` to `HashMap<String,Object>`) for which there is no safe way nor a sufficient `instanceof` test.
Annotations `@SuppressWarnings("unchecked")` would of course eliminate the warnings but not the risks. I would have to place comments at these positions with practically the same warning content.
So then what should we hide the warnings for? So the better stay in place because that's what they are for.

By the way as I cannot detect execution problems with the newer bean shell release I suggest to let it replace bsh-2.0b6.jar now. I will prepare it in the bugfix branch.
In Eclipse it requires to modify the classpath-relevant library settings after a merge (bsh-2.04b4.jar must explicitly be removed and bsh-2.0b6.jar explicitly added even if the jar files themselves have already been replaced in the lib directory):
![grafik](https://user-images.githubusercontent.com/15326471/45689541-8b173100-bb54-11e8-92ca-90fa8140f8e2.png)

**Comment by GitMensch** [comment]
> In Eclipse it requires to modify the classpath-relevant library settings after a merge (bsh-2.04b4.jar must explicitly be removed and bsh-2.0b6.jar explicitly added even if the jar files themselves have already been replaced in the lib directory)

Hm, no? It will be just replaced in https://github.com/fesch/Structorizer.Desktop/blob/bugfix/.classpath, along with https://github.com/fesch/Structorizer.Desktop/blob/master/makeStructorizer and https://github.com/fesch/Structorizer.Desktop/blob/master/makeBigJar (I'd recommend to change the later two after the merge of my changes in there...)

**Comment by codemanyak** [comment]
Remark: Wiith the former versions of Java, these warnings had been raised, too, of course.

**Comment by codemanyak** [comment]
@GitMensch wote in https://github.com/fesch/Structorizer.Desktop/issues/594#issuecomment-422398015:
> Hm, no? It will be just replaced in https://github.com/fesch/Structorizer.Desktop/blob/bugfix/.classpath, along with https://github.com/fesch/Structorizer.Desktop/blob/master/makeStructorizer and https://github.com/fesch/Structorizer.Desktop/blob/master/makeBigJar (I'd recommend to change the later two after the merge of my changes in there...)

So would I have expected, too. Yet it failed to work. Maybe it was a Monday's fault. But it might occur to others, too. Anyway, you are warned and we will be fine if it doesn't cause trouble after the merge. In any case, the Eclipse project should be cleaned after the checkcout/update.
