### ISSUE TITLE
TypeCasting Char to Int

### ISSUE THREAD

**Issue by natrius** [fesch/Structorizer.Desktop#633]
How can i achieve that?
I tried it with "- 48", with "- "0"" and with "- '0'" and it did not work

![javaw_2018-10-24_15-07-19](https://user-images.githubusercontent.com/7243447/47432539-a81bd100-d79e-11e8-9c89-0bb380ca0874.png)

I was also not able to find something like TypeCasting in the documentation. 

EDIT: Or do i have to use the workaround? https://github.com/fesch/Structorizer.Desktop/issues/530#issuecomment-392655514

**Comment by codemanyak** [comment]
May I ask what exactly you are intending? Are you trying to derive the character code of e.g. '4' or do you want to know what number is represented by a literal string "4" (or "-48" or whatever)?
If you want to convert a string assumed to contain a number literal as text value into the represented numerical value then this is essentially a number conversion from a (decimal) string into a (binary) internal representation. If you don't want to write a conversion algorithm in Structorizer but to use something built-in then indeed you may have to use the appropriate workaround https://github.com/fesch/Structorizer.Desktop/issues/530#issuecomment-392655514.
if `charZahl` is to hold such a string representation of a number then type `char` is wrong, by the way, since `char` stands for a single character, not a character string of arbitrary length.
Your last instruction rather suggests you want to find out the code difference of the digit character `'4'` to `'0'` (which would work fine in C but not in Java or Pascal where `char` is not a numerical type). Here, the best way is to use the built-in Pascal functions to convert from char to code and vice versa:
```
intZahl <- ord(charZahl) - ord('0')
```

**Comment by GitMensch** [comment]
> Or do i have to use the workaround? #530 (comment)

Yes, you do as "this isn't C (and actually you put the String `"4"` in there)

**Comment by natrius** [comment]
I want to take the Character "4" and convert it to the integer 4. Just one single character.
One way is it (at least in C afaik) to just substract 48 from the char "4" (= ASCII 52) because that would result in a 4 as integer. 

The goal i want to achieve at all is to build a ISBN10 checker. Write it in (with the "-") and so on.

**Comment by codemanyak** [comment]
@natrius 
> I want to take the Character "4" and convert it to the integer 4. Just one single character.
One way is it (at least in C afaik) to just substract 48 from the char "4" (= ASCII 52) because that would result in a 4 as integer.

Okay, then the expression with the `ord` function given in https://github.com/fesch/Structorizer.Desktop/issues/633#issuecomment-432657039 is what you need.

**Comment by GitMensch** [comment]
I suggest to let @natrius close this issue.
