### ISSUE TITLE
Concatenation of one-letter-strings went wrong on newer version

### ISSUE THREAD

**Issue by slytab** [fesch/Structorizer.Desktop#645]
Given the following in Version 3.28-11
S <- 'a' + '3'
PRINT S

I really was surprised when this results in: 116.
In older Versions this results to: 'a3' (and this is what you will expect)

If one of the strings has more than one character the result is the usual concatenation of the two strings.

**Comment by codemanyak** [comment]
The effect is at least explainable: The ASCII codes are added: ord('a') = 65, ord('3') = 51, so the sum is indeed 116.
In eralier versions Structorizer didn't make a difference between characters and strings. Now it tries to do so according to the quoting rules of C and Java.
As soon as at least one of the operands is delimited by quotes instead of apostrophs, itwill work according to your expectations very well. Try:
`S <- "a" + '3'`
or
`S <- 'a' + "3"`
or (to force a string concatenation for unknown operands)
`S <- "" + 'a' + '3'`.

I don't think this is an actual bug. It is just a consequence of operand `+` being overloaded like the dependency of the division operator effect on the operand types.

**Comment by slytab** [comment]
Hi, there.Thanks for the reply, now I understand.
There is a statement in the user guide (section about syntax) (*):

    >>The meaning of "Other character sequences enclosed in quotes or apostrophes are string literals (if it's not a character literal).<<
Unfortunatly, the phrase in parentheses is important, but didn't receive my attention.
For the sake of clearness, would it be a good idea to mention the difference in the list of examples, like

* 'a' is a character literal, not a string literal. Use "a" for string literal.
(*) referring to https://help.structorizer.fisch.lu/index.php?menu=130
Regards,sly

    Am Montag, 17. Dezember 2018, 16:23:40 MEZ hat Kay Gürtzig <notifications@github.com> Folgendes geschrieben:  
 
 
The effect is at least explainable: The ASCII codes are added: ord('a') = 65, ord('3') = 51, so the sum is indeed 116.
In eralier versions Structorizer didn't make a difference between characters and strings. Now it tries to do so according to the quoting rules of C and Java.
As soon as at least one of the operands is delimited by quotes instead of apostrophs, itwill work according to your expectations very well. Try:
S <- "a" + '3'
or
S <- 'a' + "3"
or (to force a string concatenation for unknown operands)
S <- "" + 'a' + '3'.

I don't think this is an actual bug. It is just a consequence of operand + being overloaded like the dependency of the division operator effect on the operand types.

**Comment by codemanyak** [comment]
@slytab 
Thanks for the suggestion. I just added the examples to the user guide.
