### ISSUE TITLE
Structorizer canvas should be scrollable with mouse wheel like Arranger is.

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#65]
Structorizers canvas isn't scrollable with mouse wheel
Arrangers canvas is vertical scrollable with mouse wheel 
but not horizontable. Some mice models support this.

**Comment by codemanyak** [comment]
The mouse wheel in Structorizer had been dedicated to a different purpose: It is used to collapse or uncollapse a selected (large) element. It might be debatable if that was a wise decision and it is poorly documented. Anyway, an additional button or menu toggle to achieve the same effect would certainly be helpful.
It may not seem very clever, however, to make the effect of the mouse wheel dependent on whether or not an element is selected.
The horizontal scrollability of the Arranger canvas will be examined. But wouldn't this be a rather exotic functionality?

**Comment by fesch** [comment]
I do not stick to the collapse / expand feature. This has been asked / proposed by some other use.

**Comment by codemanyak** [comment]
Maybe a new diagram menu toggle will determine which effect the mouse wheel should have?

**Comment by fesch** [comment]
Why not ;-)

**Comment by elemhsb** [comment]
Mouse scrolling in both directions is a must, becourse there is no autoscrolling near canvas boundaries when dragging items on big structures.

**Comment by codemanyak** [comment]
I might say, decompose your algorithm if it gets to large for the canvas... (but I don't, of course :wink:).
By the way: Sensible workarounds are decreasing the font size and collapsing large elements.
But well, just a question: would activating autoscroll behaviour be an option? It is also supposed to get very tricky with element dragging, but would at least work with all conventional mouse models.
(I'm still trying to work out how horizontal redirecting the mouse wheel effect is supposed to be achieved - both by user and programmer. Most approaches I have found so far are related to the browser.)

**Comment by codemanyak** [comment]
Okay, I learned, the redirecting might be triggered by the pressing of the shift key. This should be feasible.

**Comment by elemhsb** [comment]
It will be also very usefull in combination arranger / executer to test a lot of subroutines ... 
@fesch How to trigger the collape / expand function at the moment ?

**Comment by fesch** [comment]
Each element has a method setCollapsed(boolean)

**Comment by elemhsb** [comment]
Ok, but with mouse wheel ?

**Comment by fesch** [comment]
Yes, the mouse wheel triggers this method.

**Comment by elemhsb** [comment]
@fesch My mouse wheel does nothing under linux

**Comment by fesch** [comment]
I know that there are some differences between Mac and Windows too regarding the Drag&drop with the mouse under Java, so I'm not really surprised that there are some differences with Linux too.

I'll have to install some Linux distribution to test this ...

**Comment by codemanyak** [comment]
Investigation results:
1. As it turns out, the wheel rotation value is one of the decisive differences between Windows and Linux mouse wheel handling here: Under Windows you may get integer values in a practically unlimited range from MouseWheelEvent.getWheelRotation() -- depending on the scrolling speed, I observed at least -30 ... 30! --, whereas under Linux (I tested under OpenSuse with KDE) I can only get -1 or +1, not even 0 is observed in contrast to Windows. Unfortunately the detection thresholds for collapsing in method Diagram.mouseWheelMoved() were set to < -1 and > 1, respectively, which was certainly fine to avoid hypersensitiveness under Windows but explains why **elemhsb** didn't see _any_ effect under Linux. (I will perform some more tests in order to find out if perhaps only some system-dependent unit or block scroll settings make the difference -- then we might be able to unify the behaviour).
2. I tested autoscroll mode under Windows and Linux, which worked surprisingly stable with dragging of Elements under both systems - and even works if Diagram listens to Mouse Wheel events (which causes the missing mouse wheel reaction of the JScrollPane, by the way). Enabling autoscrolling in Diagram would satisfy most of the demands stated above, I guess. Hence, I will activate it for the next version.
3. Under both platforms, the Swing components ignore completely any horizontal "wheel" activities on Notebook touchpads (no MouseWheelEvent is triggered at all!).
4. Mouse wheel motions with pressed shift button trigger MouseWheelEvents on both platforms (modifier mask is 1 on the MouseWheelEvent), but the JScroolPane class -- and this is really stunning -- igores this event under Linux, whereas it actually scrolls horizontally under Windows. (I will investigate whether this might be due to some configured sensitiveness threshold as discussed above, since horizontal scrolling is always more tenacious than the vertical scrolling - you get way less events in comparison).
5. Some GUI enhancements to support collapsing/expanding by menu items and toolbar buttons are in progress. Whether the mouse wheel controls scrolling or collapsing may be switched at runtime, as I could prove. So a respective option might be added to the menu if we don't drop the mouse wheel cpnrol for this purpose entirely: Instead of mouse wheel triggering, the collapsing might be controlled by accelerator keys Shift+Num+ / Shift+Num- (in addition to the mentioned menu items and toolbar buttons).

Out of the findings listed above, a satisfying solution will be implementable pretty soon.
Moreover, I will make a proposal for a modified drawing of collapsed Elements, opening a new issue.

**Comment by codemanyak** [comment]
The combination (i.e. product) of wheel rotation and scroll amount was sufficient to get over the collapsing threshold in Linux as well.
The enhancement and bugfix package of today doesn't solve the horizontal mouse wheel scrolling insufficiency under Linux, though.
Of course, I could write a workaround for the lacking Java.awt.Swing behaviour and have the Diagram class itself carried out all mouse wheel scrolling (instead of relying on JScrollPane). Some test shows it might work, but due to lack of time I'm just not very inclined to do refine this to release stability now.
With functioning autoscroll mode and the existing possibility to scroll via the scrollbar, the situation doesn't seem entirely catastrophic anymore, does it?
@elemhsb please test this out after Bob will have uploaded the prepared version 3.23-09.

**Comment by fesch** [comment]
3.23-09 is uploaded ...

**Comment by elemhsb** [comment]
Sorry for the latency. I tested now version 3.23-10 a very smooth version. :-) Works like expected.

**Comment by codemanyak** [comment]
@elemhsb Thank you for your response. I close the issue.
