### ISSUE TITLE
language dependend critical key words

### ISSUE THREAD

**Issue by AG407** [fesch/Structorizer.Desktop#658]
Is it possible to define some other (language dependend) key words, which are marked in the structorizer red (as the EXIT key word)?
I searched in the Structorizer properties, but found no solution for that.

**Comment by codemanyak** [comment]
It is prepeared internally but hasn't been enabled so far (because nobody had requested it and it doesn't make parsing easier or faster of course).
But we could enable this with the next version if you request it.

**Comment by codemanyak** [comment]
Additional remark:
As written before, the internal mechanisms for the configurability of these key words have already been in place since enhancement issue #23 (implemented 2016).
So, as a temporary workaround for the current Structorizer version, you might open the file "structorizer.ini" (you find it in the folder shown as "Ini folder" in the "Paths" tab of the About dialog (menu Help > About...) with a text editor (make sure you have Structorizer closed before) and look for the properties "ParserPreExit", "ParserPreReturn", and "ParserPreLeave". There you may configure the respective key words.
Make sure you have enabled the Import Preference for NSD files "Replace keywords on loading a diagram (refactoring)". Then modified keywords will have the following impacts:
- When you load diagrams previously stored with the old keywords ("exit", "return", "leave") then the keywords will automatically be replaced by your new keywords.
- With new diagrams you create, your new keywords will be detected (and expected) instead of the standard ones.

When the GUI supports the configuration of the `exit`, `return`, and `leave` keywords, it will look like this (alos prepared but disabled):

![grafik](https://user-images.githubusercontent.com/15326471/50536636-bb5c6b80-0b56-11e9-87ec-e902e909761e.png)

**Comment by AG407** [comment]
Thanks for the quick response, editing the INI file is an easy way and was successful in my tests.

**Comment by AG407** [comment]
So the issue is resolved for me.

**Comment by codemanyak** [comment]
Either way, the GUI support will be enabled in the next version. I'll upload the changes to the bugfix branch this afternoon.
