### ISSUE TITLE
Python Export: Function call name and '(' missing in export > version 3.29-03

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#706]
The NSD:
```
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:nsd="https://structorizer.fisch.lu" version="3.29-06" preRepeat="until " postFor="to" preReturn="return" postForIn="in" preWhile="while " output="OUTPUT" input="INPUT" preFor="for" preExit="exit" preLeave="leave" ignoreCase="true" preForIn="foreach" stepFor="by" author="pi" created="2019-03-19" changedby="pi" changed="2019-03-19" origin="Structorizer 3.29-06" text="&#34;PythonExport( verbose := 0 )&#34;" comment="&#34;Demo File&#34;" color="ffffff" type="program" style="nice">
	<children>
		<call text="&#34;FotoMachen( verbose := verbose )&#34;" comment="&#34;Ein Foto machen&#34;" color="ffffff" disabled="0"></call>
	</children>
```
Produces:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# PythonExport( verbose := 0 ) 
# generated by Structorizer 3.29-06 
import math

# Demo File 
# Ein Foto machen 
verbose = verbose )
```
Missing FotoMachen(
and
a NEWLINE after ) is generally welcome.

**Comment by codemanyak** [comment]
Could you please attach nsd files in zipped form in future? The text you cited was defective. Fortunately it wasn't so difficult to repair it as far as allowing it to load (the NullPointerException raised is induced by the syntactic irregularities explained below during analysis - so the code will have to be hardened against them):
![grafik](https://user-images.githubusercontent.com/15326471/54645177-85ff5400-4a9b-11e9-9f98-5a257493ea3c.png)

So, what's the problem with it? Structorizer performs a very simplified syntax analysis, based on some assumptions. One of these assumptions is that an assignment operator doesn't occur within the argument list of a function call. One of the first parsing activities is to split a line at an assignment operator. The part to the left of it is assumed to be a variable name or a declaration, the part to the right of it is supposed to be the expression. In your case this causes the output you see.  (The uneven parentheses balance would only be detected on an execution attempt.)
Like Pascal, Structorizer does not support assignments within expressions.
Assignment operators are not accepted in parameter lists, in particular. Next thing is, that a parameter list is not expected in a diagram of type "program".
By the way I can't see the sense of assigning a variable to itself on the fly while passing it to a function, not even in Python. Well, maybe it was just a quick example.
If you want to write a function with default arguments (which is supported by Structorizer just since the very version 3.29-06 according to enh. requ. #385) then you should write it with a mere equality sign:
![grafik](https://user-images.githubusercontent.com/15326471/54646368-1ab78100-4a9f-11e9-8388-d35f6ead1734.png)

**Comment by elemhsb** [comment]
#### Copy / Paste
Ok, i see it's the missing newline 0a at position 2b7.

```
 00000290:  73 61 62 6c 65 64 3d 22  30 22 3e 3c 2f 63 61 6c  sabled="0"></cal
 000002a0:  6c 3e 0a 09 3c 2f 63 68  69 6c 64 72 65 6e 3e 0a  l>..</children>.
 000002b0:  3c 2f 72 6f 6f 74 3e --  -- -- -- -- -- -- -- --  </root>---------
```

I did a `$ cat PythonExport.nsd` on linux terminal and got the output **without** the last line !
So I can say:  A newline '\n' 0x0a at end of file is always expected. NSD and Export files too.

#### Python Function Declaration Parameters
I need a "=" sign in exported code to assign default values to missing parameters:
```def Fn( param1 = None ):```

##### Python Positional parameters vs. Named parameters
Also i need a "=" sign in exported code for function calls to assign a local value to a named parameter:
```FnCall( fn_param_name = external_param_name )```

##### '=' will be '==' it's no solution
```FnCall( a = a )```
is exported to 
```FnCall( a == a )```

**Comment by codemanyak** [comment]
Named parameter assignment isn't supported in Structorizer, it handles only positional parameters. So if you want to express Python-specific syntax, the export option "no translation" might be the right thing for you?

**Comment by codemanyak** [comment]
@elemhsb 
> So I can say: A newline '\n' 0x0a at end of file is always expected. NSD and Export files too.

I'd rather say: `cat´ doesn't work properly. A text file should not be required to end with a newline character as far as I know. Thousands of applications cope with text files not ending with a newline no problem. You simply used an unsuited tool... ;-)
Well no. You are right that the Posix standard indeed suggests that non-empty text files should (not must) end with an "eol" character. (Which is a character sequence in the Windows world, btw.)
It is a kind of philosophical question: Is the newline character (sequence) a line termonator oder a line separator? In the UNIX world indeed the former is assumed. 
In fact I had already to do with applications that reacted rather allergical to an "empty line" (i.e. a superfluous line separator) at the end of a file. Unfortunately I don't remember anymore which ones these were. But there are programs producing e.g. an empty array entry on reading data from a text file if this ends with a newline.
Whatsoever. I just checked that the XML parser does not run havoc if we spend the nsd file a termonating newline. And compilers shouldn't, either. So be it then.

**Comment by codemanyak** [comment]
I have now checked with some older Structorizer versions, what they produced on python export for the call:
Versions 3.19 ... 3.22-31:
`Fomachen( version = version )()`
(note the missing "to" in the name and the surplus parentheses)
Version 3.23-16:
`Fotomachen( verbose = verbose )()`

Version 3.24-03:
` verbose = verbose )()`

Since at least version 3.26:
`verbose = verbose )`

So it has some history. But Structorizer had never produced the code you intended. It will certainly be possible to write some workaround that lets the named parameter assignemnt pass to Python. But it would definitely cost too much effort consistently to support named parameter passing in general (i.e. on code export to all languages, on executing, with Analyser etc. pp.)

**Comment by codemanyak** [comment]
Well, I tweaked something in the code of the assignment detection such that the next version will let pass the calls with named argument mapping to Python export.
