### ISSUE TITLE
Python Export: name mangling with "" -0 -1 -0-1 is confusing 

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#707]
I have got over time and parameter changes a lot of new default export names.
"", -1 and today -0-1 for previous -1 files. 
Today 3.29-06 version i got for new files with 1 parameter "" mangeling.
I am confused and would prefer no mangeling and therefore a one.nsd to one.py imaging.
btw. one-1.nsd to one-1.nsd is also ok.

**Comment by codemanyak** [comment]
The "name mangling" follows very clear rules:
Subroutine diagrams append the number of arguments to the diagram name, connecting both with a hyphen (or minus sign if you like). Since version 3.29-05/06, subroutines with optional arguments are supported (#385, as already mentioned for #706). An optional argument is designated by a provided default value. **The operator sign between a parameter name or declaration and the default value must be an equality sign, not an assignment symbol.** You might regard this as inconsistent with assignments and constant definitions, but it is the way all programming languages I know handle it.
Optional parameters must always be placed at the end of the parameter list, in a contiguous sequence.
Hence, a subroutine with optional parameters has a minimum and a maximum number of accepted arguments. These two values are both appended to the function name in a file name proposal, e.g. a function declaration like `foo(a, b, c = 0, d = 1)` will produce a file name proposal "foo-2-4.nsd".
(I simply avoided to use parentheses in file names - though nowadays operating usually tolerate nearly all UTF characters -, otherwise the file name proposal might have enclosed the argument number in parentheses instead of appending it after a hyphen: "foo(2-4).nsd".)
Why these proposed file name appendices? Because Structorizer allows diagram name overloading, i.e. you may have several diagrams with same name but different argument number. Hence, if the proposed file name didn't reflect the different signatures the user would be at risk inadvertently to overwrite one diagram file with that of a different diagram having the same name, particularly on "mass saving" at the end of a session.
A possible disdadvantage of the file name proposal is that it doesn't reflect signature changes to a diagram having been saved before. "Save as", however, will immediately propose a file name according to the new signature.
I just checked the file name proposal mechanism for several examples again and cannot see a defect or "mangling" or, say, a deviation from the naming rules stated above. Again: The decision to reflect the argument number(s) in the file name proposal was made in order to prevent the user from inadvertent losses due to unnoticed file name conflicts. The user is alwas free to modify the proposal before actually saving.

Of course, with implementation of enhancement #385, there arises an ambiguity on subroutine calls which is due to possible argument number range overlapping. Image you have a function `foo´ with 2 through 5 arguments and another one with same name but 4 through 7 arguments. Both will have different proposed fine names, obviously. But which of them is to be used for a call of `foo´ with 5 arguments? Both could apply. So I implemented the (more or leass arbitrary) rule that the function with the closest upper argument number limit is chosen. (Which will not help, of course, if only the lower argument number limits differ.)
In one of the next versions group membership will get priority (this requires some internal API changes, though), but this will still leave ambiguous situations since diagrams can be member of more than one arrangement group at a time.
So if you don't provide some examples of defective file name proposals, I would like to close the issue.

**Comment by codemanyak** [comment]
@elemhsb 
I wrote:
> So do you request to propose the base name of an associated nsd file on e.g. export instead of the standard file name proposal for new files? (Please confirm this.) 

The inconvenience of this request (if I got it right) is that the file name proposal method would have to be made context-dependent, i.e. we would have to distinguish for what purpose a file name proposal is requested, or should we propose the old file name, too, if e.g. "Save as" is requested?

**Comment by elemhsb** [comment]
@codemanyak 
#### Question
>Why these proposed file name appendices? Because Structorizer allows diagram name overloading, i.e. you may have several diagrams with same name but different argument number. Hence, if the proposed file names didn't reflect the different signatures the user would be at risk inadvertently to overwrite one diagram file with that of a different diagram having the same name, particularly on "mass saving" at the end of a session. And I thought it would help keeping the overview if the routine signatures are reflected in the file names.

* Don't worry, you have the "File exists" dialog, do you want to overwrite it?

#### Timeline

* I needed a little bit time to test the new behaviour with version 3.29.06.
  * First: I have learned, only subroutines does filename mangling. No "-n", my mistake.
  * Second: Version 3.29.03 only use one -0, -1, -N
    * Big Problems see Attention
  * Third: Version 3.29.06 use -0-1
    * Escalation

* But whats about **return** value signature ?
  * Python can do: ```a, b, n = Fn()```
  * It should be implement also, that would **complete** the magling thing generally.

#### Attention 
* **Python** can't import subroutines with **"-"** in the module filename !
  * Change '-' -> '_' ?
* The filenname in Python is also the **namesspace** were the function / class exists
  * You have to call ```Fn-0-1.Fn(1)``` which is also an illegal name.
* Sure, there is a **no standard** \_\_import\_\_() way with subsequent namespace renaming, but afterwards getting new names again,  horrific

#### Situation for **python** programmers
* These filenames with "-" are not reliable usable as python modules.
* At the moment i use a Makefile as workaround to fix the EOF problem and
  then concat all *.py to a new main.py skript.
  * there is also a additional issue shown with text changing while exporting
   output(src) -> OUTPUT(export)

```Makefile
fixnoeol:
	@for i in *.py; \
	do \
	    ex -sc '$$s/$$//|w|q' $$i; \
	    sed -i 's/GPIO\.OUTPUT/GPIO.output/' $$i; \
	done
```

#### Closing (for python programmers):
* The filenames for python modules are importent:
  * there name should be fix for "import modulname"
  * no "-" in it's name **source** and **exported** *.nsd and *.py
  * file content need to be ended with "EOL" see #706

#### Possible Solutions
* General solution:
  * Filename mangling should be generaly deactivatable.
    * (work for diagram and export filenames)
* Minimal solution:
  *  for "Export to Python" should not use mangling and exports directly to diagramname.py.
     The User manages alone the diagram name.

#### btw. 
* Structorizer works **very well** on Raspberry Pi as java webstart app.
  * Displaying remote in Linux desktop.

**Comment by codemanyak** [comment]
@elemhsb 
>     * Don't worry, you have the "File exists" dialog, do you want to overwrite it?

Fine. I in turn might say: Don't worry, you have always the FileChooser dialog where you may adapt the proposed file name before saving. But polemics doesn't lead anywhere. So let's look for solutions. Only some justifying remarks: Of course you get that warning "File exists etc.". But you know how users are like (espacially myself). You are leaving the computer, somewhat in a hurry, quickly try to save all and then you get that warning. Rather than beeing aware of the possble name clash, you quickly press "yes" (of course you want to overwrite a former version of the file...) and - oops! - the damage is done! So I preferred to keep the users on the safer side. And I still think this is the better option.
>       * First: I have learned, only subroutines are subject of filename mangling. No "-n", my mistake.

What exactly do you mean with file name mangling? Just that the proposed file name may differ from the pure diagram name? From a programmer's point of view, overloading in mind, the pure routine name is only part of the signature, and the file name should somehow involve all significant information to be unambiguous. And we talk only about the **proposed** file name. You are never forced to accept he proposal, you know? In auto-save mode, however, you might have to change the file names afterwards.
>       * Third: Version 3.29.06 use -0-1

As already outlined, for routines without optional arguments the file name proposal hasn't changed at all between version 3.29-04 and 3.29-06, still only one suffix is produced, e.g. -2. Since Structorizer hasn't coped with optional arguments before, I deemed the risk of confusing users with the new filename proposals for diagrams with optional arguments neglectable. What existing diagrams could have been implicated? Okay, obviously I was wrong.
>     * But what's about **return** value signature ?

Usually, programming languages don't allow overloading routines, only differing in the result type. Routines with identical name and argument type sequence may no coexist in the same namespace, no matter whether their result types differ. So the result type (and number?) were left out of the "file name mangling", particularly since Structorizer doesn't force you to declare result types. The only halfway reliable hint might be the existence of some result or return mechanism in the algorithm itself.
>       * Python can do: `a, b, n = Fn()`

I know this. Structorizer and most programming languages can't, in contrast. So you will be able to convert a correct Structorizer diagram into (more or less) correct Python code but certainly not the other way round if multiple results are involved.
Workaround in Structorizer: return an array (already a problem for C export!) or a record (struct) in Structorizer. (And this is what I would do for a hypothetical Python import and what Structorizer does on subroutine extraction, named "outsourcing".)
>       * It should also be implemented, that would **complete** the mangling thing generally.

Now, here is my Bartleby response: "I'd prefer not to" (as substantiated above). We would get into deep trouble on code export to nearly all other languages.
>     * **Python** can't import subroutines with **"-"** in the module filename !
>       * Change '-' -> '_' ?

Okay, this is something I hadn't on my screen. We might consider this on Python export specifically (as you suggested further below as a minimal solution). In order not to confuse all the rest of the users I'd like to adhere to the traditional fle naming scheme for all other languages and the diagrams (i.e. the nsd files) themselves. Indeed, I had intentionally chosen hyphens because they may not be part of the diagram name (not at least if the user adheres to the suggested identifier naming rules, and yes, I know that e.g. COBOL and PowerShell use hyphens as part of names...).
>     * The filenname in Python is also the **namesspace** were the function / class exists
>       * You have to call `Fn-0-1.Fn(1)` which is also an illegal name.

Well, as already mentioned, this could be solved by changing the file name proposal for Python export. By the way, having an expert here: What about dots in the file name? (On batch export, dots are used to produce new file names if files with the proposed output file names are already existing, unless option `-f` is used. User interception is difficult on console level.)
>       * there is also a additional issue shown with text changing while exporting
>         output(src) -> OUTPUT(export)

You must have been using an obsolete Structorizer version for this export. This was a bug fixed with version 3.26-04 (since when the export became compatible with Python 3).
>       * no "-" in it's name **source** and **exported** *.nsd and *.py

I don't see what problem the nsd file name might cause for Python programmers.
>       * file content need to be ended with "EOL" see #706

Okay, I will care for this. I think this doesn't need a new preference.
>       * Filename mangling should be generaly deactivatable.

Well, I propose the introduction of a new export option that allows
1. to disable the "mangling" and
1. to specify the separator character to be used if it's enabled.

The Structorizer default setting will be:
1. enabled,
1. '-'.

Is this acceptable?

>     * Structorizer works **very well** on Raspberry Pi as java webstart app.
>       * Displaying remote in Linux desktop.

Thanks for this information. :smile:

**Comment by codemanyak** [comment]
I decided that the proposed new preferences rather belong to the saving options. This is the preview:
![grafik](https://user-images.githubusercontent.com/15326471/54779706-24b0bf80-4c18-11e9-87a2-981e718d33e5.png)

**Comment by elemhsb** [comment]
@codemanyak 
good solution, I'm looking forward to test the new version. :-)
