### ISSUE TITLE
export to python, variables have leading "=" in version 3.29-08

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#716]
#### Diagram block with
```
myvar := 0
```
#### Export to python
```
= myvar = 0
```
#### Preferences setting
[  ]  No Convertion ( is off )

**Comment by codemanyak** [comment]
I could detect the mistake. An operator unification step get lost on the bugfix #706. I had only tested with operator `<-`. Excuse me, please.

**Comment by codemanyak** [comment]
@elemhsb 
Can you live for some time (meaning days, not months) with the workaround to use the assignment operator `<-` instead of `:=`? Then I would prefer to fix as many problems as possible (e.g. #717 if reproducible) and to spend some more time for intensive tests before issuing the next version.
