### ISSUE TITLE
Arranger load-dialog loads already existing structures multiple times.

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#78]
Arranger load dialog loads already existing structures multiple times.

Load from *.arr file double structograms in arranger, klick on these (shadow) diagrams will open a **new** structorizer window overlapping the old on at the same place. Close one of these windows (X) closed all instances of structorizer.

**Comment by codemanyak** [comment]
It was just a provisional solution intended to allow to restore a proviously saved arrangement.
It only works on the same machine context and was thought to be used in a practically bare Arranger. Since the diagrams are restored from file, they are new objects and the identity check against already (or still) placed diagrams necessarily fails. If a mere equality check shoukd replace the identity check in this case (seems to make sense) then of course the concept of equality among diagrams will have to be defined. Possible alternatives are:

1. mere signature (name, argument number, possibly types);
2. signature and file path (doesn't make much sense for the planned enhancement of saving to portable i.e. relocatable archives);
3. recursive structural and textual equality (no regarding checkpoints, collapsing and other temporary attributations) - the more exact the criteria the closer to identity... 

I guess the third proposal will come closest to your expectations? It will result in a mixed world, though: some modified diagrams would not be recognised such that saved (possibly obsolete) copies of them will be loaded, others (unchanged ones) will remain without concurring copies.

What about the dependency on closing a window now?
There is always an initiating main frame - maybe (usually) a Structorizer instance or an Arranger instance (if initially started). While the latter is a singleton, there may be several Structorizer instances. If you launch auxiliary Structorizer instances from Arranger (e .g. in order to edit a diagram just loaded from file and hence not assoiciated with a Structorizer instance) these will be vulnerable to killing when closing their owner frame. I'm hesitant to change this behaviour.

**Comment by codemanyak** [comment]
A patch that avoids the loading of structurally equivalent diagrams is now available (on the bugfix3.23 branch). Integration request is in progress.
