### ISSUE TITLE
Language changes when auto creating subroutines

### ISSUE THREAD

**Issue by enricoKoschel** [fesch/Structorizer.Desktop#805]
When creating a subroutine with CTRL+ENTER on a non-existing function call, the language changes.

**Comment by codemanyak** [comment]
Thanks for your report. Obvously, this happens if you had changed the language within the session and haven't saved this prefernce yet. The new Structorizer instance opened for editing the subroutine then gets its language from the ini file (which still provides the previous settings) and this overrides the current settings, among them the language. The same happens if you create a new diagram in the Arranger and double-click it.
I think, the best might be to save all current preferences into the ini file before an additional Mainform is opened. (The loss might not only affect the language, but also other recently modified preferences.) I will check the consequences.

**Comment by codemanyak** [comment]
Will be fixed with the next version (3.30-05).
@enricoKoschel 
As temporary workaround please make sure to have saved all preference changes (e.g. via Preferences > Save or load preferences > Save now) before you generate a subroutine from CALL.
