### ISSUE TITLE
Export and Reimport of C-Program

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#806]
Hi Bob and Kay,

I still work with structorizer and I still love it - especially the feature to show the generated code in a window.

Then I made the "Hello World" program as described in the Tutorial and exported the nsd to C-Code and reimported it. That works fine.
In the generated nsd the first comment line of the C-code becomes part of the output message? So the output becomes longer and longer when repeating this - the first comment will be added. Is there a reason for this behavior?

Fine regards
Rolf

**Comment by codemanyak** [comment]
Well, basically export and import have been designed as different features. Both are incomplete, so it seemed sensible to automatically to insert comments where some doubts or trouble occurred during conversion. In addition, there were enhancement requests to add specific comments like copyrights etc. on exporting.
A repetitive export - import loop hadn't been intended or was regarded as rather unlikely. So idempotency was not a primary goal, though it might seem to offer a nice test for soundness. Actually, I am really glad that reimport now happens to work at all in many cases.
I see some possible approaches to improve the situation:
1. We might try to implement some fancy intelligence component that attempts to identify automatic export and import comments and to suppress them on the reverse operation. I think this task could be facilitated a little by marking those automatic comments with specific character sequences.
2. We might introduce export / import preferences to suppress any automatic comments.
3. We might write the additional comments into a separate window or log file instead of inserting comments into the result itself, if this wouldn't make analysis of the outcoming way more difficult (requires complicated references and is invisible in a possibly defective result).
4. Maybe a combination of some the above approaches.

Yet the comments are not the only components of the results that may inflate - have a look at the output instruction: The dummy format string will be reimported as a string to be output (which is not entirely wrong as it may not only contain format specifiers after adjustment), on re-export, however, an additional dummy format string will be inserted etc. The same, but way more drastically would happen with complex replacement surrogates for algorithmic structure that are not directly convertible (e.g. parallel sections, try instructions, or jumps or the like). In any these cases repetitive export / reimport will inflate the original algorithm to a syntactice monster, and we can do little about it, can we?
And actually, I am becoming hesitant to add more and more preferences lest beginners should get lost in configuration hell.

**Comment by reks99** [comment]
Hi Kay,

Many thanks for your explanation.

I wouldn't test reimport but I hadn't a C program by hand to test the import function - and yes I assume, that the generated C program code can be imported without trouble.
There is nothing against the generated comments in the exported program, but add the (first) comment to the print message adulterated the intened of the code i.e. comments should be comments, not messages.

Fine regads
Rolf

**Comment by codemanyak** [comment]
@reks99 
> [...] but add the (first) comment to the print message adulterated the intent of the code [...]

Oh, well, now I understand what you were arguing against:
![grafik](https://user-images.githubusercontent.com/15326471/74150236-c6af1100-4c09-11ea-8bf0-78bdaf2082d2.png)

Okay, this can be fixed, of course. It was simply the practical experience that students used to ignore the explanations given in the comment but wondered why there was no output at all when running the exported program. Hence, leaving the format string empty did not adulterate the output but spoiled it as well. My idea was that the program output "TODO: Specify format" rings a bell and just helps to identify and overcome the defect quickly.
One intention with issue #800 is to infer as many required specifiers for the format string as possible, such that a halfway meaningfull format string could emerge.

**Comment by reks99** [comment]
Hi Kay,

Yeah, that's it.

Fine regards
Rolf.

**Comment by codemanyak** [comment]
Just an additional remark: When the exported program is corrected (i.e. the TODO text has been replaced by format specifiers, e.g.: `printf("%s\n", "Hello World");`) then the import even makes sense of it (where empty strings and the endstanding newline should still be eliminated):
![grafik](https://user-images.githubusercontent.com/15326471/74152715-2b209f00-4c0f-11ea-8830-74f5b7877951.png)

**Comment by codemanyak** [comment]
On fixing this issue I realized that an empty output instruction has no longer been translated correctly, either, since version 3.30-01. Instead it produces a line
```c
printf("TODO: specify format\n", );
```

**Comment by reks99** [comment]
Hi Kay,

Nice, that you fixed it so fast. Is it possible to get the fixed version if you like send me the link by PM.

While I'm working on lager tutorial for work with Structorizer (current title: Programmieren lernen – auf eine etwas andere Art) - perhaps for proLinux. That is why I test the functionally.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> Is it possible to get the fixed version if you like send me the link by PM.

Well, I just put the jar file of a first 3.30-05alpha version temporarily here,
[Structorizer_3.30-05alpha.zip](https://github.com/fesch/Structorizer.Desktop/files/4186675/Structorizer_3.30-05alpha.zip)

> While I'm working on lager tutorial for work with Structorizer (current title: Programmieren lernen – auf eine etwas andere Art) - perhaps for proLinux. That is why I test the functionality.

Sounds interesting. Would you mind making your accomplished "lager" (?) tutorial available to us?
Your tests are very helpful.

**Comment by codemanyak** [comment]
> [...] Is it possible to get the fixed version if you like send me the link by PM.

This is a preview jar (modified 3.30-05 alpha version, contains bugfix #811):
[Structorizer_3.30-05alpha1.zip](https://github.com/fesch/Structorizer.Desktop/files/4191123/Structorizer_3.30-05alpha1.zip)

**Comment by reks99** [comment]
Hi,

I need a hint, how to run the exported java programm.

Fine regards
Rolf
