### ISSUE TITLE
Import in Python exports

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#807]
Hi Kay,

I also exported the "Hello World" program to python and one reason it didn't run is the missing library "recordtype". I can't find any corresponding lib in the debian repositories.

Where do you get them from or where is it included in.

Fine regards
Rolf

**Comment by codemanyak** [comment]
This refers to library https://pypi.org/project/recordtype/, this seemed to be the closest approach to what records/structs could be (see also https://stackoverflow.com/questions/5227839/why-does-python-not-support-record-type-i-e-mutable-namedtuple).

If this is too exotic an approach then of course I might translate a record to a simple Python dictionary instead, but this would require more fundamental syntactic alterations.

**Comment by reks99** [comment]
Hi,

I think, that the documentation should mention this as well or a message printed by the first program start can stated so.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> I think, that the documentation should mention this as well or a message printed by the first program start can give that info.

Of course I might mention this in the User Guide but I thought it makes more sense to leave the comment directly above the import directive that might cause trouble, wouldn't you agree?

> Why don't you leave it to the programmer to define the libs, which should be included?

I can hardly do this if the exported code requires a certain lib. Well, with *recordtype 1.3* it does so only in case a record variable is used. But it turned out to be very difficult to detect this in advance. Therefore the import directive occurs in every Python export file, not only in case of necessity. As outlined before, we could try to avoid "foreign" libraries by restricting ourselves to the basic data structures of Python, which induces more efforts but should still be feasible.

**Comment by reks99** [comment]
Hi,

> avoid "foreign" libraries by restricting ourselves to the basic data structures of Python

I prefer this, so beginners can work with other teaching sources as well.

Fine regards
Rolf
