### ISSUE TITLE
Include DPI awareness

### ISSUE THREAD

**Issue by Advanium** [fesch/Structorizer.Desktop#81]
Structorizor currently is not DPI aware and won't scale up as expected.
Are there any plans to implement DPI awareness?

My use case includes an Apple MacBook Pro with retina display (2560x1600) hosting a Windows 10 guest using bootcamp with an upscale of 200% for Visual Studio et cetera to compensate lacking DPI awareness of other apps.

**Comment by fesch** [comment]
There are no plans to implement this, but I will leave open the issue for the case that somebody will try to do it.

**Comment by codemanyak** [comment]
The trouble here is that a) Java Swing is not DPI-aware, b) usually the DPI information obtained fro the OS is not correct (apparently due to lacking driver feedback). As research shows, nothing has improved here for years.
To rely on a more or less DPI-adaptive Java GUI framework, all Structorizer GUI might have to be re-implemented using JavaFX, but because of b) it is not sure that such a heavy transformation will cleanly solve the problem. It still depends on the look and feels' cooperation.

**There is an interim workaround at least for the icons**, though: Just insert a line "ScaleFactor=2" or "ScaleFactor=3" into your structorizer.ini file. You may have to experiment a little to find the optimum factor for your resolution. This will scale the icons accordingly from the next Structorizer start on. They may look a little blurry, though. In theory, the factor might be any double value but Structorizer rounds it to the next integral value anyway.
I'm trying to find a way to scale the default font size correspondingly, and as soon as this works, the scale factor might be added to the preferences configurable via the Structorizer GUI itself - which still represents a workaround, though.

**Comment by codemanyak** [comment]
Fixing is in progress, first test version available under branch bugfix3.25-0.

**Comment by codemanyak** [comment]
A workaround including accomplished icon and font scaling is filed for version 3.25-05. To activate it, a manual insertion of a line "scaleFactor=2" (once) into the structorizer.ini file remains necessary before Structorizer is started.
The effect strongly depends on both the OS and the Look and Feel, though, and requires a restart of Structorizer. (Under Windows, most scaling works more or less consistently, under Linux, however, checkboxes aren't scaled with some Look and Feel, accelerator hints remain tiny with some other Look and Feel etc.)
Because of these restrictions, an integration of a control to change the scale into the GUI doesn't make much sense.
On the long term, a GUI redesign using a different framework (JavaFX) won't be avoidable. To maintain a differentiated workaround strategy for every possible combination of OS version and Look and Feel isn't feasible, obviously.

**Comment by codemanyak** [comment]
Version 3.25-07 will improve the workaround by including checkboxes and radiobuttons on many dialogs in the scaling mechanism.

**Comment by codemanyak** [comment]
It turned out that the workaround for the checkbox sizes caused that with "Nimbus" look & feel checkboxes do never show a selected status anymore. Hence, the checkbox resizing attempt must be suppressed for "Nimbus" look & feel until a "Nimbus-aware" workaround is found.

**Comment by GitMensch** [comment]
Note: This is partly overlapping with #4 as it would be nice to use 32x32 or 64x64 Icons as "base" for the scaling. Scaling the current ones with a graphics program using "next neighbour" calculations lead to clean icons (I could batch the current ones for providing all current icons in 16,24,32,64,128) while using scaling inside the GUI leads to blurred icons.

**Comment by codemanyak** [comment]
@GitMensch 
If you volunteer, I won't reject the offer :wink:. There may be some icons, though, where this automatic approach will not lead to acceptable results because they had been downshrinked to 16x16 pixels with losses. For some of them I may have a larger versions, for some of them a redesign will be necessary anyway, but fine if the latter wouldn't hold for all of them.

**Comment by GitMensch** [comment]
Yes, I volunteer to provide a clean iconset for 6,24,32,64,128,256 given the following prerequisites:
* there is no redesign of the icons in sight - otherwise we should better wait for this
* you provide me with all the larger versions you have (ideally via Git)
* someone (likely you) *will* adjust the ScaleFactor code to use the nearest possible filesize as starting point and maybe add an extra option for double-sized toolbar (should I open a new FR for this?)
* they will be included in the binary release (does @fesch still create the jar files?)

If we want to go this route then create a new branch, commit all the larger versions you have (whatever size these are), I'll fork this branch, add the changed files and create a merge request and you can modify the scaling parts afterwards. I suggest to use sub-folders and plain names (do we need the numeric prefixes?):

~~~
structorizer\gui\icons
structorizer\gui\icons\arranger.png
structorizer\gui\icons\...
structorizer\gui\icons_16\jumpbefore.png
structorizer\gui\icons_16\...
structorizer\gui\icons_32\jumpbefore.png
structorizer\gui\icons_32\...
structorizer\gui\icons_64\...
structorizer\gui\icons_128\...
structorizer\gui\icons_256\...
~~~

The search for the icons should start in the biggest folder according to the scale and go up until a file is found. Is this a plan for changing this soon or "nice to have for some time later"?

**Comment by fesch** [comment]
Yes, I still create the JAR files published on the site ;-)

I'm OK with your plan. :-)

**Comment by codemanyak** [comment]
The cascaded icon directory approach proposed by @GitMensch has mostly be implemented with version 3.27-07 (delivered on 2018-02-08). Also see #4.

**Comment by codemanyak** [comment]
Well, I think, as far as I see, we won't get much closer to DPI awareness as with the implemented GUI scaling capability. So I close this issue for now. Who wants to object may reopen it.

**Comment by codemanyak** [comment]
Just for the record: This [StackExchange thread](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display) is one of the best explained workaround recommendations for fixing the feigned DPI awareness of Java/Swing on the system level I could find so far, though it primarily addresses Windows and Linux, but also promises that from Java version 9 or 10 on the problem will have been fixed in the JDK:
[How do I run Java apps upscaled on a high-DPI display?](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display).

**Comment by codemanyak** [comment]
The GUI scale option implemented in Structorizer as a wobbly workaround to somehow circumvent the lacking DPI awareness of Java 8 had put the theme somewhat out of focus, such that the DPI revision had been forgotten when we changed to Java 11. Whereas Swing now copes to scale the GUI on DPI changes of the operation systems, the icons simply get magnified from the low-resolution (16 pixels) resource provided by the code

Now it's time to address this inconvenience eventually. By using the new class/API `MultiResolutionImage`, adaptive icons can be provided now, which makes a significant difference (click on the screenshot in order to see it without downscaling):

<img width="910" height="462" alt="Image" src="https://github.com/user-attachments/assets/d5164222-0abb-4256-a24d-68b1bd11baea" />

Some additional tests and measures are still required before the DPI awareness upgrade can be rolled out with Structorizer 3.32-35. Temporarily the DPI scale option will be preserved as it might be used for product-specific purposes (e.g. for Beamer presentations in the class room relatively independent from the DPI setting of the whole Desktop).
