### ISSUE TITLE
Is there a "continue" operator?

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#813]
Hi,
I build the following programm for my tutorial. In the default branch of the case stucture the loop should be contiuned without an output of (non existing) result. Is it possible to have the keyword "continue" (and its functionallity) as a valid value in the branch symbol.
![Taschenrechner](https://user-images.githubusercontent.com/18035140/74449922-95d71200-4e7d-11ea-8984-b157df527534.png)

Fine regards
Rolf

**Comment by codemanyak** [comment]
There is no continue instruction. The obvious clean workaround is to assign a boolean variable "doPrint" (or the like) with true before the CASE element and to set it false iun the default branch. Then the output can be done in dependency of it. I upload a solution since there are some further "bugs" in your diagram:
![grafik](https://user-images.githubusercontent.com/15326471/74453625-ea30c080-4e82-11ea-84e8-a2b4c519e255.png)
(A backslash doesn't do any good if placed at the beginning of a line or within a string literal, `exit` needs an argument.)

**Comment by reks99** [comment]
Thanks. 

I found the backslash error after upload and the comment "Schleife erneut ausführen" could have been useful, if a continue is possibel.
I will rewirte the programm with an if clause to check the operator and ir it is not "x" the case is executed.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Another possible variant without any EXIT at all:
![grafik](https://user-images.githubusercontent.com/15326471/74482350-9e970a80-4eb4-11ea-8803-fc33b55a4a3b.png)
