### ISSUE TITLE
Why can Arranger not be started with an arrz-file as argument?

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#815]
Hi,

I fight nearly the whole day with Arranger, to work with functions. So I often have to start it again and the existing *.arrz need to be loaded from the gui.
BTW: When an *.arrz file should be loaded it isn't visible in the file list titled "Aranger Files". I have to switch to "Portable Aranger Zip-Files" or  "show all files".

Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf,
1. You can call Structorizer from the command line with an .arrz file as argument;
1. You may open a recently saved or loaded archive via the menu `File > Open recent file >`;
1. You may open it via the menu item `File > Open ...` where of course the .nsd filter is the default setting, so you must change the filter as you already have found out;
1. You may load an .arrz file via the Arranger button "Load Arr.", where you also have to select the filter "Portable Arranger Zip Files" or "All Files"/"Alle Dateien".

It may be inconvenient having to change the file filter, but it works. We might think about finding a way to provide combined filters (letting pass all .nsd, .arr, and .arrz files), though.

**Comment by reks99** [comment]
Hi Kay, 

Many thanks for your explantations.

I expected the filter for arr or arrz files is set, when "Schema laden" in arranger is clicked. In structorizer expect *.nsd files shown.

Greetings
Rolf

**Comment by codemanyak** [comment]
@reks99 
> I expected the filter for arr or arrz files is set, when "Schema laden" in arranger is clicked. In structorizer expect *.nsd files shown.

That's exactly the way it works: Via "Schema laden" / "Load Arr." you will find filters for Arrangement list files ("Arranger Files") and "Arrangeer Zip Files" in the choice list where "Arranger Files" is pre-selected:
![grafik](https://user-images.githubusercontent.com/15326471/74604854-3fa6e080-50c2-11ea-97c5-6274b1c4545a.png)
In the File > Open... dialog of Structorizer, however, all three filters for "NSD Files", "Arranger Files", and "Arranger Zip Files" are available where the "NSD Files" are pre-selected.

I can can offer to add combined filters initially selected, which will then look like:
![grafik](https://user-images.githubusercontent.com/15326471/74604808-b1caf580-50c1-11ea-8fa3-9acbb475bed5.png)
or
![grafik](https://user-images.githubusercontent.com/15326471/74604905-dbd0e780-50c2-11ea-9dee-ab41813d9eb9.png),
respectively. I propose to modify the filter descriptions a little in order to make things a little clearer perhaps (see screenshots). Would you welcome this change?

**Comment by codemanyak** [comment]
Applied the additional combined file filters.
