### ISSUE TITLE
Still problems with bash export

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#816]
When you export the attached program to bash, the script has a lot errors.

1. Access data of a variable requires a $-sign - a lot are missing
2. Assign data to a variable is not possible with ":="
3. There must not any space between the name of the variable, the assign operator and the value.
4. Bash functions do not return a value with an return statement, so a return can be ignored on export and an assignment after a function call is not needed or useful either. Bash variables are global by default.
5. Calling a function needs no paratheses and the arguments should not be separated by commas

The zip-file has a running version, so you can compare the script with the output of structorizer - especially where $-signs are missing.
[taschenrechner.zip](https://github.com/fesch/Structorizer.Desktop/files/4209712/taschenrechner.zip)
I hope you can extend the exporter a little bit with this information.

**Comment by codemanyak** [comment]
@reks99 
Many thanks for your comments. They will help improve the outcome, particularly with respect to function definitions and calls. Some remarks from my part, though:
> 1. Access data of a variable requires a $-sign - a lot are missing

So? Where exactly? (I think we may forget about differences between $wert1 and ${wert1} - they are supposed to be equivalent.) But I haven't seen any missing $ on comparing the Structorizer export and your corrected version (see screenshot below).

> 2. Assign data to a variable is not possible with ":="

I know and Structorizer does as well on bash export. Just a moment! Is it possible that you forgot to disable the export option "No conversion of the expression/instruction contents"?

> 3. There must not be any space between the name of the variable, the assignment operator, and the value.

Well, there isn't - ???

> 4. Bash functions do not return a value with a return statement, so a return can be ignored on export and an assignment after a function call is not needed or useful either. Bash variables are global by default.

Okay, point taken. I had overseen this actually. This causes a bold problem, though. It is not only utterly difficult to insert a sensible instruction after the function call in order to fetch the result, we cannot avoid side effects of function calls with respect to variables meant to be local in Structorizer but aren't in bash. To rename all "local" variables within the function definition into something cryptic is the only viable wayout, I am afraid. So the return instruction could be replaced by something like `result624fa30814=${ergebnis}`, and instead of `ergebnis=berechnen "${befehl}" "${wert2}" "${wert1}"` the correct CALL replacement would be
```bash
berechnen "${befehl}" "${wert2}" "${wert1}"
ergebnis=${result624fa30814}
```
(Btw. the `function` keyword is optional, so this difference isn't anything you ought to blame Structorizer for.)
> 5. Calling a function needs no paratheses and the arguments should not be separated by commas

See remark above, it seems you have forgotten to unselect an export option which is only useful if the diagram already contains shell syntax.

The file comparison screenshot shows the current Structorizer export on the left-hand side and your corrected result on the right-hand side (the cut-off lines at the end are identical):
![grafik](https://user-images.githubusercontent.com/15326471/74605259-cb227080-50c6-11ea-8cae-c7c89463d36f.png)

**Comment by codemanyak** [comment]
@reks99 
By the way, there is a bug in your diagrams: You permuted the arguments on calling the `berechnen` function, i.e. on extracting (outsourciung) the function, Structorizer offered you an arbitrary order of the needed parameters. Then you reordered them apparently only in the call but left the proposed order in the function diagram, such that you map `wert1` (main program) to local `wert2` (function) and vice versa, thus swapping the operands.

**Comment by codemanyak** [comment]
Fixed the function calls and result mechanism (for boolean functions, however, this did not improve the result, rather the opposite). Locality of function variables has not be enforced so far.

**Comment by reks99** [comment]
Hi Kay,

Your are right - as allwas - I had the mentioned export flag set. Without the flag the export looks very good and with your fixes it might be even better. BTW is the link for the test version still valid?

I decided to use the calculator program for further exports, because it has all standard Nassi-Shneiderman elements. I will check it further with Perl, Python, C and java to see what has to be done to get the exports running (until now Perl gives errors - I will report later)

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> BTW is the link for the test version still valid?

The new version 3.30-05 was just delivered (you may download it from the home page), so the alpha1 version has already become obsolete (though it can still be accessed).

**Comment by codemanyak** [comment]
Function arguments and array initializer items are unduly put within `$(  )` if they are neither variables nor arithmetic expressions but e.g. literals. This would mean command exection and hence provoke an error or -- even worse -- collateral damage.
