### ISSUE TITLE
How to rename the internal name of a function

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#818]
Working with the calculator program, the main program insists on the subfunction "berechnen(3)". Because I further developed the function it has a new name. But even when I rename the function the nsd is still referred as with a different number.

So how can this be changed to test it with arranger?

Many thanks for your help
Rolf

**Comment by codemanyak** [comment]
Both routine name and argument number must match between declaration and CALL. (And of course the routine diagram must be present in Arranger.) That's all.
Semantically you must make sure that argument order matches too between declaration and call.

The file name is of no importance for Arranger, except that Structorizer always proposes a file name that consists of diagram name and argument number (separated by a hyphen, e.g. `foo-3.nsd`) or both minimum and maximum argument number in case of optional arguments (e.g. `bar-2-5.nsd`). If you change the signature afterwards then the file name will no longer reflect the signature properly, of course. I think you will already have found out.

By the way, though Structorizer doesn't provide a real refactoring tool, the Find & Replace dialog may help you a lot to keep a group of diagrams consistent, i.e. if you plan to rename a routine you should consider doing it via the Find & Replace dialog to adapt all relevant references as well.

**Comment by reks99** [comment]
Thanks Kay,

I still fight with arranger. Even when I rename newer versions of the function nsd and load it, structorizer didn't accept this - and most of the time the debugger died silently and without any hint.

The function has been created with "Auslagern" and some times it works like a charme but most I have to fight.

Rolf

**Comment by codemanyak** [comment]
I am afraid you will have to describe the failing scenario into more detail if am to do anything about it. I have no clue what you might have done wrong.

**Comment by reks99** [comment]
Hi Kay,

I think I found out, that the signatur was different and I had delete the assignment of the function return, that was, whet the debugger don't like.

About error messages, there are a lot of zero pointer exceptions in the window - not written to a logfile - when started arrager by the command line.

Many thanks for your help.
Rolf

**Comment by codemanyak** [comment]
You know that you can open the Arranger from a running Structorizer instance, don't you?
You achieve this simply e.g. by loading some arrangement file (.arr, .arrz), by importing a source file containing more than one function, by pushing the current diagram to Arranger (e.g. via menu item `File > Arrange` or `Datei > Im Arranger anordnen`, respectively), by outsourcing a sequence of elements from a diagram, by invoking the editor for the routine that is referenced by a CALL element.
But of course it is also okay to start Arranger via command line. Would you mind sending me the NullPointerException traces from the terminal?

**Comment by reks99** [comment]
Hi Kay,

>  Would you mind sending me the NullPointerException traces from the terminal?
of course. I try to rebuild the session and, if you like send the two diagrams as well.

See you later
Rolf

**Comment by reks99** [comment]
Hi Kay,

Attached you find to archives. The *.bad.zip has bad diagrams and the error messages from the standard error path.
Wenn try to debug the diagram, the executer immediately stops.

[Rechner-bad.zip](https://github.com/fesch/Structorizer.Desktop/files/4213442/Rechner-bad.zip)

The second archiv is what I will use for export to different language - just as a referenz when report errors.
[Rechner-good.zip](https://github.com/fesch/Structorizer.Desktop/files/4213443/Rechner-good.zip)

Hope that helps.
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
It's getting mysterious: On Windows, I have no problems to execute the Rechner-bad example (AdoptOpenJDK 11), on an older SuSeLinux with openjdk version 1.8.040, Arranger fails tio find the routine `berechnen(4)`. Same Structorizer version! And several exception tracebacks occur. At least I can reproduce your trouble now.

**Comment by codemanyak** [comment]
Bug identified, fix will be delivered with version 3.30-06.

**Comment by reks99** [comment]
Hi Kay,

I'm interested in the fixed version, because "Arrager" is my current fight and I like bug hunting. ;-)

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> I'm interested in the fixed version, because "Arrager" is my current fight and I like bug hunting. ;-)

I can offer you an alpha version again. Here you find its zipped jar file:
[Structorizer_3.30-06alpha.zip](https://github.com/fesch/Structorizer.Desktop/files/4226046/Structorizer_3.30-06alpha.zip)

**Comment by reks99** [comment]
Hi Kay,

for you information I attached the messages from 3.30-06-alpha when started with my config file - which is in the zip too.

[30-6.alpha.zip](https://github.com/fesch/Structorizer.Desktop/files/4230132/30-6.alpha.zip)

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
The two tracebacks you sent (30-06alpha.zip, error.zip) are due to racing hazards in the swing system. For the first of them I could at least establish a try context to prevent the exception from showing in the log. The problem shown in error.zip cannot suppressed this way. As you can see, only java-internal classes are involved, the trouble orignates asynchronusly from the event queue. So there is nothing that could control it except perhaps some heuristical delays or acceleratons in the setup code, but this is really hard, we have already tried.

The trouble on execution you showed in the video is caused by some preceding error during execution that left Executor in a kind of zombie state. Press "Yes" when you are asked whether you want to abort the running debug session (about second 0:20). If that doesn't help then shut Structorizer down and start it again. This should get you rid of the problem.

**Comment by reks99** [comment]
Hi Kay,

my problem is, how to show a newbie a way to work (neraly reliable) with Arranger and the debugger. The debugger is an excellent feature but it is hard to explain, when it goes into the "zombie state".

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
It is indeed somewhat tricky as the executor is a concurrent runnable, and sometimes it may get locked by internal errors. I had already tried my best to detect such situation and the unfamous dialog
![grafik](https://user-images.githubusercontent.com/15326471/74966089-b58aaf00-5416-11ea-8a4a-7f03e92e864f.png)
is a measure against it that allows in many cases to reset the debugger but unfortunately it still doesn't always succeed. (It pops also up in case of editing attempts during debugging - in this case the user may actually decide whether to give up the editing or to stop the debugger, which usually works.)
I might try to distinguish cases where the debugger detects a running state when starting (which often is a zombie state because otherwise the start button shouldn't be active) and then to add an additional remark "If aborting doesn't succeed please save all changes, close down Structorizer and open it again," or the like (I avoided the term "start" lest it should get confused with the debugger start button. I think this may be more at the point than to "hide" some laborious text in the User Guide (which might also be done, though).

**Comment by codemanyak** [comment]
So well, I just finished to add a respective subsection "[Starting Trouble](https://help.structorizer.fisch.lu/index.php?menu=94&page=#debugger_starting_trouble)" to the Executor page in the User Guide. The clear detection of a zombie situation turned out to be a little more difficult as you may possibly understand after having read the User Guide passage.
