### ISSUE TITLE
Problems with bash export too

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#832]
Hi Kay,

the bash export of the parallel test program shown in the previous report ( #831) has unexpected code.

First - the for loop can't be code like in c more than in python as `for i in $(seq 0 ${param2});` (see https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-7.html)

Second - the for-line at least misses a semi colon.

Third - the arguments for the thread must not have parentheses or dollar signs before the arguments. Shell functions are like normal command calls from the linux shell, they also have no parentheses around the arguments. So they should look like `test 2 10`

Fine regards
Rolf

FYI: The exports to Java and Perl run out of the box

**Comment by codemanyak** [comment]
@reks99
> the bash export of the parallel test program shown in the previous report ( #831) has unexpected code.

It may look unexpected at first glance (some empty lines removed) but is working flawlessly (I tested it with bash version 4.4.12(1)):
```bash
#!/bin/bash
# (generated by Structorizer 3.30-06) 

function test() {
 declare -i param1=$1
 declare -i param2=$2

 # TODO: Check and revise the syntax of all expressions! 
 declare -i i
 for (( i=0; i<=${param2}; i++ ))
 do
  echo ${param1}
 done
}

# TODO: Check and revise the syntax of all expressions! 
# ========================================================== 
# ================= START PARALLEL SECTION ================= 
# ========================================================== 
pidsd4c77e82=""
(
 test 2 10
) &
pidsd4c77e82="${pidsd4c77e82} $!"
(
 test 5 10
) &
pidsd4c77e82="${pidsd4c77e82} $!"
(
 test 7 10
) &
pidsd4c77e82="${pidsd4c77e82} $!"
wait ${pidsd4c77e82}
# ========================================================== 
# ================== END PARALLEL SECTION ================== 
# ==========================================================
```
> **First** - the for loop can't be code like in c more than in python as `for i in $(seq 0 ${param2});` (see https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-7.html)

I don't get your point. The generated C-like style of FOR loop may not have been listed by the linked HOWTO site but is absolutely correct in bash. (With respect to your Python reference: in contrast to the Python `range()` function - cf #831 -, the bash `seq` command will enumerate *including* the second argument, if that answers your complaint...) 
 
> **Second** - the for-line at least misses a semi colon.

No, it doesn't. A semicolon (after the duplicate parentheses?) would only be necessary if the `do` command followed in the same line: `for (( i=0; i<=${param2}; i++ )); do`.

> **Third** - the arguments for the thread must not have parentheses or dollar signs before the arguments. Shell functions are like normal command calls from the linux shell, they also have no parentheses around the arguments. So they should look like `test 2 10`

They do look that way, don't they?

So, I am somewhat puzzled and tend to change the label from "bug" to "invalid".

**Comment by codemanyak** [comment]
Just an idea: Please confirm that you exported with Structorizer version 3.30-06.

**Comment by reks99** [comment]
Hi Kay,

find attached the for-loop-example from the previous report ( #831) as bash code and its output
[bash_fortest.zip](https://github.com/fesch/Structorizer.Desktop/files/4305559/bash_fortest.zip)

At least it didn't work here
Fine regards
Rolf

**Comment by reks99** [comment]
Hi Kay,

I tested the Parallel-test with bash again (Structorizer 3.30-06) and it didn't work. The echo command in line 8 make an array access on a simple integer. The program is running, when the part in the square brackets is removed.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> I tested the Parallel-test with the bash export again (Structorizer 3.30-06) and it didn't work. The echo command in line 8 make an array access on a simple integer.

Well, bash needs a completely different mechanism to pass an array as parameter, otherwise the argument will just be the first element. Structorizer is not smart enough to guess that `param1` is meant to be an array by extrapolating from the subsequent index access. You should have declared `param1` as an array in the argument list:
![grafik](https://user-images.githubusercontent.com/15326471/76242068-56120900-6236-11ea-88a0-a527d903704d.png)
You find the corrected arrangement and the resulting export in the attached zip file.
[Issue832_corrected.zip](https://github.com/fesch/Structorizer.Desktop/files/4308186/Issue832_corrected.zip)

> The program is running, when the part in the square brackets is removed, even with the c-like for-loop definition.

Of course, in this case `param1`, being the first element of the array, can be echoed as many times as you like...

> A few words about the loop count: In the generated code for the bash script the end of the loop is defined as _lower than or equal_ so it runs one time more than wanted.

Yes, because your Structorizer loop runs one time more than sensible. See #831.

> In Structorizer it is written as `for i <- 0 to param2`

Yes, exactly this is your mistake...

> and so a translation to "_lower than_" is also possible - or even better.

It could be if your Structorizer loop would end at `param2 - 1`, but as you specified `i` to run from 0 through `param2` (i.e. *including* `param2`!), the bash generator cannot guess you were wrong and silently correct your loop. No, no, and no: _less than or equal to `param2`_ is the exact equivalent of your defective FOR loop. End of the story.

You cannot blame Structorizer for your own bugs. Sorry having to say that.

**Comment by reks99** [comment]
Hi Kay,

so you tell me, that all my programs of the last 30 years are wrong? I can't believe.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
You will have observed that the bash export tries to solve the array passing problem via a name reference (`declare -n`). In our example this will fail because the formal parameter name `param1` equals the passed-in array name. The user must solve this conflict ("circular name reference") by renaming either the local parameter or the array in the main program. Structorizer can hardly do this automatically because of its principal unawareness of how and by whom a function might be called.
This interference between inner and outer context is a problem with name reference or with using global variables. Unfortunately, bash does not offer call by value or call by reference for things like arrays or associative arrays (which are our export workaround for struct types) in a sensible way.
The attached archive contains the manually adapted (and running) export file.
 
[For_Test2.zip](https://github.com/fesch/Structorizer.Desktop/files/4309381/For_Test2.zip)

**Comment by codemanyak** [comment]
@reks99 
> so you tell me, that all my programs of the last 30 years are wrong? I can't believe.

No Rolf, I don't. Certainly not. What I told you is that your understanding of the FOR loop in Structorizer with respect to your own examples is wrong. And this may consequently also apply to the FOR loop in Pascal, Oberon, BASIC, Algol, PL/I, Fortran etc. because all these languages use a similar syntax and semantics.
A loop `FOR i := 1 TO 5` runs through the values 1, 2, 3, 4, *and* 5, a loop `for k <- 0 to 4` iterates over 0, 1, 2, 3, *and (inclucing)* 4.
Structorizer is only about 14 years old (less than 30), the mentioned programming languages are older than 30. I don't know what programming languages you may have used all the time, but there are syntactic and semantic differences between many of them. I, for instance, was very surprised when I realised (several years ago) that the `range(a, b)` function in Python does *not* include the value of `b`. In C you formulate an explicit comparison, so you are relatively free, but the *usual* way to terminate a FOR loop in C (and in related languages) is indeed to specify a not included end value (by using the `<` operator). If you have preferably coded in C and shell syntax all the time you will certainly have done a great job (without realising that there is a backside of the moon with languages of differing syntactical understanding).

**Comment by reks99** [comment]
Hi Kay,

I tested all exports and only Pascal, Oberon and Basic uses the "upper bound include" version of loop ranges. So the question raises aren't this more or less academical languages?  All other loop controls are forced with a "low or equal" decision to do so too. 
A real special case is the (in my eyes little obscure) range method Python uses.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
Please don't drive me nuts.
> [...] only Pascal, Oberon and Basic uses the "upper bound include" version of loop ranges.

This is not about majority among a more or less arbitrary set of export languages. It is about a well-established loop paradigm. This FOR loop paradigm is shared by many programming languages, among them Pascal, Simula, Oberon, BASIC (including Visual Basic), Algol, FORTRAN, PL/I, and more. In Ada, you would write `for J in 0 .. 17`, and it would of course include 17, and so on.

> So the question raises aren't these more or less academical languages? For all other languages loop controls are forced with a "low or equal" decision to do so too.

This discussion is not going anywhere, Rolf. As programmer or Structorizer user you have to realise, what loop paradigm the language or tool supports and you will have to adhere to it. Structorizer cares for correct interpretation and conversion, and that is all to it. "All other languages" are neither forced nor violated in any way. The C-style FOR loop is very flexible (in fact so flexible that it can be abused in any imaginable way - which makes it unsuited as standard FOR loop paradigm in Structorizer, by the way), such that Structorizer can manage to produce a logically equivalent export to C-inspired target languages. It would not work the other way round.

So what ware we talking about here? You proved that Structorizer does its job.
