### ISSUE TITLE
Option to change the syntax from Pascal to C#

### ISSUE THREAD

**Issue by BloodyRain2k** [fesch/Structorizer.Desktop#872]
It would be nice if there could be an option added that lets one turn the operators like := for assigning into sane ones like just = and comparison from = to ==.

I know there's already the option to alter the templates like the iteration loop for example. Extending this to the point where you can just write C# like into the blocks without it constructing a bunch of non-sense in the code preview because it expects Pascal would be really nice.

**Comment by codemanyak** [comment]
Technically this ought to be feasible. It might just get a little tricky to avoid cyclic substitutions and semantic clashes (if one configures different operators with identical symbols). Whereas the prerefence dialog already averts homonyms among the keywords, awkward cyclic name changes of the FOR and FOR-IN loop keywords have indeed proven to cause trouble in some cases. Let us be aware, however, that if we allow operator symbol configuration, then the traditional synomymity between assignment operator symbols `<-` and `:=`, comparison operators `=` and `==`,  logical operators `&&` vs. `and` etc. in Structorizer is at stake. In addition, more configuration stuff tends to reduce the ease of usage, particularly for beginners. So possibly we should think twice here.

Last but not least, we should mind our language here: Despite of the wide spreading of C-like idioms, other programming languages with different operator symbols are not "insane", not in particular Pascal.

**Comment by codemanyak** [comment]
@BloodyRain2k 
Just a question. If it is only about code preview: Have you considered the effect of the export option "No conversion of the expression/instruction contents" as workaround? In this case, you could fill the elements with e.g. C# code and it would mostly just passed through as is on export (which of course would produce nonsense on choosing any other export language and would not work in the Debugger).

**Comment by codemanyak** [comment]
Well, after pondering your request some nights, I think it would not do any good to allow free configuration of all operator symbols. A sensible approach might be a binary switch concerning just assignment and equality comparison between the following two options:

| Operator type | Traditional | C-Style |
| -------------- | ----------- | ------- |
| Assignment    | `<-`, `:=`    |  `<-`, `=` |
| Equality          | `=`, `==`   | `==`        |

On switching among the modes, a refactoring will take place: the assignment operator symbols except `<-` will be substituted (`:=` <--> `=`) and equality signs used as comparators will be replaced by double equality signs from left to right and vice versa. I think, other than with the keywords, this refactoring should not be optional but mandatory.
What about the usual Nassi-Shneiderman assignment symbol `<-` now? I suggest to preserve it on switching. So only `:=` will be replaced by `=`and vice versa on refactoring assigments. This way, these refactorings will be nearly reversible.

I will think about certain mode indicator in the Structorizer GUI (maybe in the toolbar and the element editor), lest users should get confused. The standard mode will be the traditional one in Structorizer.

I still feel somewhat uneasy about it because it might confuse users. But well, it would not be very different from the keyword preferences you should also be aware of on issuing INPUT / OUTPUT instructions or JUMP elements of certain types.

**Comment by codemanyak** [comment]
The introduction of an assignment symbol choice with refactoring mechanism will have a broader impact on syntax analysis mechanisms in Structorizer. So it may take some days to identify and fix all possible collisions.

**Comment by codemanyak** [comment]
After having spent many days to implement the proposed refactoring approach I am increasingly inclined to discard it. The impacts are very deep and touch so many aspects and fine-tuned mechanisms that they bear a tremendous risk of compromising them. In addition, my suspicion the user might get confused by several mutually excluding syntax modes substantiated.

So I propose now to introduc a mere ***display*** switch (via menu toggle item and a toggle button in the toolbar). This would be sound, easy to implement and free of risks. The syntax rules for the input remain the same but the user may (temporarily) display the operators in C style. It would not only apply to assignment and equality comparison symbols but to all operator symbols. Diagrams saved by a newer Structorizer version remain fully compatible with earlier product versions.
This "C" display mode would only work in combination with syntax highlighting and do the following substitutions (only symbols listed where conversions are done):

| Written operator symbol | Display in standard mode | Display in C mode |
| ------------------------- | -------------------------- | ------------------- |
| `<-` | `←` | `=` |
| `:=` | `:=` | `=` |
| `=` | `=` | `==` |
| `<>` | `≠` | `!=` |
| `!=` | `≠` | `!=` |
| `≠` | `≠` | `!=` |
| `<=` | `≤` | `<=` |
| `≤` | `≤` | `<=` |
| `≥` | `≥` | `>=` |
| `not` | `not` | `!` |
| `and` | `and` | `&&` |
| `or` | `or` | `││` |
| `xor` | `xor` | `^` |
| `div` | `div` | `/` |
| `mod` | `mod` | `%` |
| `shl` | `shl` | `<<` |
| `shr` | `shr` | `>>` |

(The `xor` conversion may be a problem as it would only be correct in case a bitwise **xor** is meant, as logical operator `!=` would be appropriate. But Strucorizer cannot differentiate this.)

**Comment by codemanyak** [comment]
New display mode implemented to be delivered with vrsion 3.30-11.

**Comment by codemanyak** [comment]
There is still a flaw in the solution (which made the given up refactoring idea nearly unfeasible as well): type definitions look misleading and degenerate with `==` operators:
![DateDefinitions](https://user-images.githubusercontent.com/15326471/96513882-1fd44780-1263-11eb-96cd-4f9bb7289478.png)
A context-sensitive approach will be necessary (and difficult).

**Comment by codemanyak** [comment]
Another overlooked flaw is the undue conversion of `=` operators to `==` in routine headers (where default values are associated to optional parameters):

![grafik](https://user-images.githubusercontent.com/15326471/103446675-9db0c800-4c82-11eb-8e23-595324c0492a.png)
