### ISSUE TITLE
GUI: Code preview is white on grey

### ISSUE THREAD

**Issue by laalsaas** [fesch/Structorizer.Desktop#966]
If you set look and feel to GTK+ and use a dark theme e.g. "breeze dark", the code preview font has the theme color: white and the background of the code preview still uses the same Blueish grey. This way, you can barely see the code. I think it would be best do set the background color of the code preview also from the GTk-theme
![Screenshot_20210308_150215](https://user-images.githubusercontent.com/43275254/110331520-7f1ed280-801f-11eb-8c3d-a27216bd062e.png)

**Comment by codemanyak** [comment]
Thanks for the hint. It is not really easy to have all the possible look and feel themes in mind all the time for all possible platforms, in particular, as some of them, especially Nimbus, work with unbelievable tweaks around the Swing standard mechanisms.
We will have a look into it.
As a temporary workaround, please just choose another look and feel in Structorizer.

**Comment by codemanyak** [comment]
Just an explanation: The decision _not_ to use the standard background colour was made because with most of the light themes, the code preview would have been fully ablaze next to the diagram, competing with it for th user's attention, which was considered inconvenient, too. We will find a solution that ensures enough contrast between text and "paper".

**Comment by codemanyak** [comment]
The same problem applies to the Arranger index, and even the element editor is hard to use because the cursor is back on very dark gray:
![grafik](https://user-images.githubusercontent.com/15326471/110351258-ec892e00-8034-11eb-9f9c-2f5b00967c75.png)
For these effects Structorizer can hardly be blamed - we use standard behaviour of JTextArea and JTree here! This looks rather as if the coordination between GTK+ theme and Java Swing wouldn't work in an optimal way. As already mentioned: Many look and feels use bypasses. So is it actually the task of the application to compensate this? Our code already containes several workarounds for nasty look and feels. I hesitate to add even more of them.

**Comment by codemanyak** [comment]
It gets even more funny: Two instances of Structorizer in the same process behave differently (see red and green box):
![grafik](https://user-images.githubusercontent.com/15326471/110353784-bef1b400-8037-11eb-8663-69ce42e360f7.png)

**Comment by codemanyak** [comment]
Just some remarks:
- GTK+ leaves ridiculously much space around the toolbar buttons - stealing it from the work area...
- Many of our icons are not particularly suited for dark themes (as to be seen in the screenshots).
- It is hard to react to live L&F changes - because of timing problems and because of the Swing bypasses: When exactly or from where may we obtain the L&F standard background and text colour for a certain type of components and when will we have the chance to correct them after the L&F has been established?
- After a L&F change there will likely be remnants of the former L&F (this is not just a guess, I know this!), which makes it even harder to find a guaranteed way to adapt all settings consistently.
-

**Comment by codemanyak** [comment]
After having isntalled a fresh Debian 10, it wasn't so mysterious anymore (and the toolbar layout looks normal again, the icon are artefacts still ugly, though) and the solution for the L&F change notification turned out easier than expected. The problem of the highlighting remains — see screenshot:

I see three possible solutions:
1. We dim down all highlight colours (selection, execution etc.). Disadvantage: the highlighting in the diagram and the code would no longer correspond.
2. The text colour in the highlighted regions would have to be inverted — impossible with a JTextArea, we would have to replace it by e.g. a TextPane, which makes the handling more complex.
3. We set the usual colours for text and background (i.e. black on light gray), no matter, what the theme defaults are.

I will try approach 2 and have workaround 3 as fallback in mind.

**Comment by codemanyak** [comment]
Well, approch 3 yields the best ratio between effect and effort for the code preview and will be implemented with version 3.31-03:
![grafik](https://user-images.githubusercontent.com/15326471/110468422-8ce45e80-80d8-11eb-8d50-f2f65ab957d1.png)

In other related cases (like Find & Replace, see screenshot below) we may just dim the highlight colours instead.
![grafik](https://user-images.githubusercontent.com/15326471/110468708-f06e8c00-80d8-11eb-97ef-58673562784f.png)

**Comment by codemanyak** [comment]
In case of a dark theme the inactive highlighting in Find&Replace will just be gray, the emphasized highlighting remains orange:
![grafik](https://user-images.githubusercontent.com/15326471/110514173-5245ea80-8107-11eb-91d9-efa2629954c6.png)

**Comment by codemanyak** [comment]
Most of the untidy icons have now been revised such that they are functional in dark L&F theme. This included some slight colour modifications or sets of alternative icons for dark themes (like the snap mode icons in the Turtleizer status bar):
![grafik](https://user-images.githubusercontent.com/15326471/110827822-ba770680-8296-11eb-8511-6b3cc2a83801.png)

On this occasion I became aware that there is no dark standard L&F for Swing that would step in on a Windows platform, which happens to be run in dark color mode.
A possible solution might be to integrate a free product like [FlatLaf](https://www.formdev.com/flatlaf/) by FormDev GmbH (which is known for its JFormDesigner). Then Structorizer could always offer two dark (and two additional light) Look and Feels. The price for this "fashion service" would be a size increase by about half a MiB.
