### ISSUE TITLE
Processing import: null not defined

### ISSUE THREAD

**Issue by hkiel** [fesch/Structorizer.Desktop#971]
Importing the following Processing (Java) code
```
PVector p = null;

void setup() {
  p = new PVector();
}
```
leads to a warning `The variable «null» has not yet been initialized!`

**Comment by codemanyak** [comment]
Well, that is because `null` has not been supported as something special by Structorizer, not in particular as the Java blind-refeence literal. This has nothing to do with Processing code import.
I will have a look whether support for the Java (and Processing) literal `null` could be added to Executor and Analyser but this might raise further questions as OOP and pointer support in general, and what about Pascal `nil`, C `NULL`, C++ `nullptr` etc. etc. then?

**Comment by hkiel** [comment]
C `NULL` is a define in some header file.
C++ `nullptr` seems to be a keyword since C++11, same for Python. I'm not familiar with Pascal and others.

**Comment by hkiel** [comment]
Ok, different approach. Consider the following code:

```
PVector p = new PVector();
void setup() {
  if (p!=null) {
    println(p.x);
  }
}
```

I get `The variable «null» has not yet been initialized!` again and additionally I get `The variable «new» has not yet been initialized!`. Maybe the latter is because (Processing-)class `PVector` is unknown to structorizer (though new is a Java keyword).

The check for null pointer is inevitable in languages with pointers/references and I would expect tools to not complain about unknown null symbol.

**Comment by codemanyak** [comment]
> The check for null pointer is inevitable in languages with pointers/references and I would expect tools to not complain about unknown null symbol.

True but neither Java nor Structorizer do support pointers. (At least not by now.) If Structorizer did, then there would be the choice among different language-specific conventions, `null` and `new` are just the ones for Java and the don't mean pointers but references. Though both being addresses, their handling differs significantly (see C++ where both coexist in a single language). One could argue for derefencing operators like prefix `*` (C, C++), poszfix `^` (Pascal) or infix `->` (C, C++), pointer arithmetics and so on. With all the hassle of pointer arithmetics? There were reasons to restrict the interpretable apparatus.

In Structorizer you have basically two options:
1. You may write supported code that is meant to be interpreted by the Executor component, where it is recommendable to watch out for the Analyser warnings. The code generators work hard to achieve as useful results as possible.
2. Or you may write whatever text you want into the elements - in this case you may simply switch off Analyser as a whole, some of the checks, or just the alarming red markers ("driehoekjes"). Code export will only establish the algorithmic skeleton according to the diagram structure. The contained text may be exported chiefly as is or as comments. In any other case the resulting code is likely to be mutilated.

In contrast to e.g. UML, NSD diagrams are not made to express OOP aspects like inheritance, member fields, class relationships, etc.
So you shouldn't expect Structorizer to be a universal OOP IDE. Recent enhancement focussed on supporting advanced procedural programming issues, complex data types like records/structs, and enumeration types on the one hand and some surrogates for representing global definitions (or class member variables) for the import from OOP languages like Java and Processing on the other hand. Fully functional OOP support seems over the top.

By the way, I just checked for chance to support some (configurable?) `null` literal but this turned out more complicated than tought at first glance: The `null` expression is already passed to the built-in interpreter (despite the warnings) but that used to return null when the evaluation of some expression fails (the error message you see is a consequence of it). So we would not get much farther, as `null` is not necessarily used as literal but might as well be the content of a variable or the result of a function omitting to return an expected value. It would get hard to tell defective expression results from intended null values.
Therefore it had been reasonable to reject `null` as a regular value in Structorizer. Sorry having to tell this. There are limitations we may have to get along with. At least it would require a very fundamental re-invention of the tool to functionally support explicit references (`null` is an explicit reference value) or even pointers.
